

OUTER_SET anim_beetle = 0 // 30720 gibb for testing 
ACTION_IF enhanced_edition BEGIN 

  STRING_SET 9560 @7011 // obg2 class descriptions don't include abilities
  OUTER_SET anim_beetle = 57888
  COPY ~iwdification/data/anim/e220.ini~             ~override~
       ~iwdification/dw_iwdspells_resource/anim/bam~ ~override~
       ~iwdification/dw_iwdspells_resource/anim/wav~ ~override~
       
END ELSE BEGIN

  ACTION_IF MOD_IS_INSTALLED ~INFINITYANIMATIONS/SETUP-INFINITYANIMATIONS.TP2~ ~500~ BEGIN // 'more base animations'

    ACTION_IF IDS_OF_SYMBOL (~animate~ ~BEETLE_BLACK~) > 0 THEN BEGIN
      OUTER_SET anim_beetle = IDS_OF_SYMBOL (~animate~ ~BEETLE_BLACK~)
    END
  
  END

END  

OUTER_SPRINT first_ss cdidrnw // if no beetle, keep wolf shapeshift
ACTION_IF anim_beetle BEGIN OUTER_SPRINT first_ss cdidrubb END
  
ACTION_CLEAR_ARRAY cd_druid_poly
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_druid_poly BEGIN

  // item/creature => spell
  cdia480 => cdidrbb
  cdia481 => cdidrpb
  cdia482 => cdidrww
  cdidree => cdidree
  cdidrfe => cdidrfe
  cdidrwe => cdidrwe
  cdidrbr => cdidrbr // alternative black bear for boring beetle
  
END

ACTION_PHP_EACH cd_druid_poly AS res => spell BEGIN  

  // clone wolf shapeshifting to others
  COPY ~iwdification/spl/cdidree.spl~  ~override/%spell%.spl~
    SAY 0x08 @9005 // boring beetle
    SAY 0x50 @9006
    WRITE_ASCIIE 0x3a ~%res%b~ #8
    LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%res%b~ END
    LPF ALTER_EFFECT INT_VAR match_opcode = 111 STR_VAR resource = EVAL ~%res%~ END // give weapon
    
  COPY ~iwdification/bam/%res%.bam~  ~override~ 
       ~iwdification/bam/%res%b.bam~ ~override~
       ~iwdification/cre/%res%.cre~  ~override~
       ~iwdification/itm/%res%.itm~  ~override~

END  

COPY_EXISTING ~cdidrpb.spl~ ~override~  
  SAY 0x08 @9007 // polar bear
  SAY 0x50 @9008

COPY_EXISTING ~cdidrww.spl~ ~override~  
  SAY 0x08 @9009 // winter wolf
  SAY 0x50 @9010

COPY_EXISTING ~cdidree.spl~ ~override~  
  SAY 0x08 @7003 // earth elemental
  SAY 0x50 @7006

COPY_EXISTING ~cdidrfe.spl~ ~override~  
  SAY 0x08 @7002 // fire elemental
  SAY 0x50 @7005

COPY_EXISTING ~cdidrwe.spl~ ~override~  
  SAY 0x08 @7004 // water elemental
  SAY 0x50 @7007

COPY_EXISTING ~cdidrbr.spl~ ~override~  
  SAY 0x08 #19792  
  SAY 0x50 @7008

COPY_EXISTING ~cdia480.cre~ ~override~  
  SAY 0x08 @9001 // boring beetle
  SAY 0x0c @9001
  WRITE_LONG 0x28 anim_beetle

COPY_EXISTING ~cdidrwe.cre~ ~override~     
  SAY 0x08 @7009 // water elemental
  SAY 0x0c @7009

COPY ~iwdification/spl/cdidrif.spl~ ~override~   
  SAY 0xfe @7010
  
COPY_EXISTING ~clabdr01.2da~ ~override~
  REPLACE_TEXTUALLY ~[ %TAB%]GA_SPCL611[ %TAB%]~ ~ GA_%first_ss% ~ EVALUATE_BUFFER
  PATCH_FOR_EACH res IN SPCL612 SPCL613 SPCL924 SPCL925 SPCL926 SPCL927 BEGIN
    REPLACE_TEXTUALLY ~[ %TAB%]\(GA\|AP\)_%res%[ %TAB%]~ ~ **** ~
  END  

APPEND ~clabdr01.2da~
~ABILITYX   ****       ****       ****       ****       GA_cdidrww ****       ****       ****       GA_cdidrpb ****       GA_cdidrfe ****       GA_cdidree ****       GA_cdidrwe CDREPLACE
ABILITYY   ****       ****       ****       ****       ****       ****       ****       ****       AP_SPCL924 ****       ****       ****       ****       ****       AP_cdidrif CDREPLACE~

COPY_EXISTING ~clabdr01.2da~ ~override~
  COUNT_2DA_COLS cols
  FOR (index = 17 ; index < cols ; ++index) BEGIN
    REPLACE_TEXTUALLY ~CDREPLACE~ ~**** CDREPLACE~
  END
  REPLACE_TEXTUALLY ~CDREPLACE~ ~****~
  PRETTY_PRINT_2DA
  BUT_ONLY