ACTION_IF !VARIABLE_IS_SET sfo_installed BEGIN

  OUTER_SET sfo_installed=1


///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Sanity check for AUTO_EVAL_STRINGS
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

 OUTER_SPRINT var testers
 OUTER_SPRINT players var
 ACTION_IF !"%%players%%" STRING_EQUAL testers BEGIN
      FAIL "AUTO_EVAL_STRINGS is not set (you need to include it in your tp2 preamble to use SFO)"
 END



///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Set default values of control parameters
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

 ACTION_IF !VARIABLE_IS_SET scsroot BEGIN
      OUTER_SPRINT scsroot "%TP2_BASE_NAME%"
 END
 ACTION_IF !VARIABLE_IS_SET workspace BEGIN
      OUTER_SPRINT workspace "stratagems_external/workspace"
 END
 ACTION_IF !VARIABLE_IS_SET inifile BEGIN
      OUTER_SPRINT inifile "%scsroot%/%scsroot%.ini"
 END
 ACTION_IF !VARIABLE_IS_SET ssl_loc BEGIN
      OUTER_SPRINT ssl_loc "ssl"
 END
 ACTION_IF !VARIABLE_IS_SET sfo_loc BEGIN
      OUTER_SPRINT sfo_loc "sfo"
 END

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Make the workspace directory if it doesn't already exist
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

MKDIR "%workspace%"

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Set the debug variable if it isn't already set; run silent if it's set to zero
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ACTION_IF !VARIABLE_IS_SET debug_variable BEGIN
   OUTER_SET debug_variable=0
END
ACTION_IF debug_variable=0 BEGIN SILENT END

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Set defaults for component_loc and local_loc
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  OUTER_SPRINT ~component_loc~ ~~
  OUTER_SPRINT ~local_loc~ ~~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////               
/////////////              Define some symbols
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

OUTER_SPRINT ~percentage~ ~%~
OUTER_SPRINT ~atsymbol~ ~@~
OUTER_SPRINT ~tilde~ "~"
OUTER_SPRINT ~minus_one~ "-1"
OUTER_SPRINT ~arrow~ ~=>~

<<<<<<<< .../stratagems-inline/blank
>>>>>>>>

OUTER_SPRINT former "0"
ACTION_FOR_EACH val IN z y x w v u t s r q p o n m l k j i h g f e d c b a 9 8 7 6 5 4 3 2 1 0 BEGIN
    OUTER_SPRINT $alphanumeric_next("%val%") "%former%"
    ACTION_TO_UPPER val
    ACTION_TO_UPPER former
    OUTER_SPRINT $alphanumeric_next("%val%") "%former%"
    OUTER_SPRINT former "%val%"
END

///////////////////////////////////////////////////
// check what install we're running on
///////////////////////////////////////////////////


  OUTER_SET enhanced_edition = ( GAME_IS ~bgee bg2ee eet~ ? 1 : 0)
  OUTER_SET is_bg1 = ( GAME_IS ~bgee tutu tutu_totsc bgt eet~ ? 1 : 0)
  OUTER_SET is_bg2 = ( GAME_IS ~tutu tutu_totsc bgee~ ? 0 : 1)
  OUTER_SET is_tutu = ( GAME_IS ~tutu tutu_totsc~ ? 1 : 0)
  OUTER_SET is_eet = ( GAME_IS ~tutu tutu_totsc~ ? 1 : 0)

  ACTION_IF !VARIABLE_IS_SET tutu_var BEGIN
     ACTION_IF is_tutu BEGIN
        OUTER_SPRINT tutu_var "_"
     END ELSE BEGIN
        OUTER_SPRINT tutu_var ""
     END
  END
  
  ACTION_IF GAME_IS "eet" BEGIN
     OUTER_SPRINT eet_var "_"
  END ELSE BEGIN
     OUTER_SPRINT eet_var ""
  END

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// a few resource fixes
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// correct missing section in kensai clab file
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

COPY_EXISTING clabfi04.2da override
   // diagnostic: can we read entry 40 from the second row with at least 10 entries?
   PATCH_SILENT
   PATCH_TRY
      READ_2DA_ENTRY 1 40 10 blah
   WITH DEFAULT
      SET_2DA_ENTRY 1 39 40 "**** ****"
      PRETTY_PRINT_2DA
   END
BUT_ONLY

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Some IDS entries are present on some but not all versions of the game
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////


ACTION_IF !FILE_EXISTS "override/spell.ids" BEGIN
       COPY_EXISTING spell.ids override
END
ACTION_DEFINE_ASSOCIATIVE_ARRAY spell_ids_missing BEGIN
   4611=>DRUID_SHAPESHIFT_BROWNBEAR
   4612=>DRUID_SHAPESHIFT_WOLF
   4613=>DRUID_SHAPESHIFT_BLACKBEAR    
   4632=>AVENGER_SHAPESHIFT_SWORDSPIDER
   4633=>AVENGER_SHAPESHIFT_BABYWYVERN
   4634=>AVENGER_SHAPESHIFT_FIRESALAMANDER
   2490=>WIZARD_POLYMORPH_NATURAL_FORM
   2491=>DRUID_SHAPESHIFT_NATURAL_FORM
   2493=>WIZARD_POLYMORPH_FLIND
   2494=>WIZARD_POLYMORPH_OGRE
   2495=>WIZARD_POLYMORPH_SPIDER
   2496=>WIZARD_POLYMORPH_MUSTARD_JELLY
   2497=>WIZARD_POLYMORPH_BROWN_BEAR
   2498=>WIZARD_POLYMORPH_BLACK_BEAR
   2499=>WIZARD_POLYMORPH_WOLF
   4732=>HELM_TRUE_SIGHT
   3101=>INNATE_CURE_LIGHT_WOUNDS
   3102=>INNATE_SLOW_POISON
   3103=>INNATE_DRAW_UPON_HOLY_MIGHT
   3104=>INNATE_LARLOCHS_MINOR_DRAIN
   3105=>INNATE_HORROR
   3106=>INNATE_VAMPIRIC_TOUCH
   4212=>PALADIN_DETECT_EVIL
   4212=>PALADIN_PROTECTION_FROM_EVIL
   4721=>TALOS_STORMSHIELD
   4722=>TALOS_LIGHTNING_BOLT
   4238=>SUN_SOUL_FLAMING_FISTS
   4103=>BLACKGUARD_AURA_OF_DESPAIR
   4935=>BLACKGUARD_SUMMON_FALLEN_DEVA

END
ACTION_PHP_EACH spell_ids_missing AS code=>name BEGIN
      ACTION_IF !FILE_CONTAINS_EVALUATED ("override/spell.ids" "%code%[ %TAB%]+%name%") BEGIN
         APPEND "spell.ids" "%code% %name%"
      END
END

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// some third-party mods unhelpfully map WIZARD_DISPEL_MAGIC to SPWI326; change this back
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ACTION_IF enhanced_edition BEGIN
  COPY_EXISTING spell.ids override
    COUNT_2DA_ROWS 2 rowcount
    FOR (i=1;i<rowcount;i+=1) BEGIN
       READ_2DA_ENTRY i 1 2 ids
       PATCH_IF "%ids%" STRING_EQUAL "WIZARD_DISPEL_MAGIC" BEGIN
           SET_2DA_ENTRY i 0 2 2302
       END
    END
  BUT_ONLY
END

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// in case Fixpack hasn't already done it, disable the 0-byte items & broken areas (we do this here for the benefit of the count section)
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

SILENT
ACTION_FOR_EACH bad IN "iplot01k.itm" "iplot04g.itm" "iplot04h.itm" "iplot04i.itm" "xr2400.are" "xr2600.are" BEGIN
   ACTION_TRY
       COPY_EXISTING "%bad%" override
            READ_BYTE 0x0 0
       BUT_ONLY
   WITH DEFAULT
       DISABLE_FROM_KEY "%bad%"
   END
END
VERBOSE


///////////////////////////////////////////////////
// read in ini
///////////////////////////////////////////////////

  ACTION_IF FILE_EXISTS ~%inifile%~ BEGIN
    COPY ~%inifile%~ ~%workspace%~
     READ_2DA_ENTRIES_NOW ~scs_ini_array~ 1
        FOR (i=0;i<~scs_ini_array~;i=i+1) BEGIN
          READ_2DA_ENTRY_FORMER ~scs_ini_array~ ~i~ 0 ~key~
          READ_2DA_ENTRY_FORMER ~scs_ini_array~ ~i~ 1 ~value~
          TO_LOWER key
          SPRINT $scs_ini_hash(~%key%~) ~%value%~
        END
    BUT_ONLY
  END

///////////////////////////////////////////////////
// include core function library
///////////////////////////////////////////////////


  ACTION_BASH_FOR ~%scsroot%/%sfo_loc%/general~ ~lib_.*\.tpa~ BEGIN
         ACTION_IF "%BASH_FOR_EXT%" STRING_EQUAL_CASE TPA BEGIN
            INCLUDE ~%scsroot%/%sfo_loc%/general/%BASH_FOR_RES%.tpa~
         END
  END

///////////////////////////////////////////////////
// include file-specific function library
///////////////////////////////////////////////////

  ACTION_BASH_FOR ~%scsroot%/%sfo_loc%/filetype~ ~lib_.*\.tpa~ BEGIN
         ACTION_IF "%BASH_FOR_EXT%" STRING_EQUAL_CASE TPA BEGIN
             INCLUDE ~%scsroot%/%sfo_loc%/filetype/%BASH_FOR_RES%.tpa~
         END
  END

 
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Initialise SSL variables
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

OUTER_SPRINT ~sslvariables~ ~%percentage%scsroot%percentage%=%scsroot%&%percentage%tutu_var%percentage%=%tutu_var%~
LAF check_ini STR_VAR ini=library_override RET value END
ACTION_IF "%value%" STRING_EQUAL_CASE none BEGIN
   OUTER_SPRINT ssllibrary "%scsroot%/%ssl_loc%/library"
END ELSE BEGIN
   OUTER_SPRINT ssllibrary "%value%"
END

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Define swap code to move between EE and vanilla SSL
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  DEFINE_PATCH_FUNCTION ssl_ee_to_vanilla  BEGIN
     // SPLSTATE to ToBeX extended stats
     REPLACE_TEXTUALLY "!CheckSpellState(\([^,]*\),\([^)]*\))" "CheckStat(\1,0,\2)"
     REPLACE_TEXTUALLY "CheckSpellState(\([^,]*\),\([^)]*\))" "CheckStatGT(\1,0,\2)"
     // vanilla doesn't have RunAwayFromNoLeaveArea
     REPLACE_TEXTUALLY RunAwayFromNoLeaveArea RunAwayFrom
     REPLACE_TEXTUALLY NinthFarthestEnemyOf NearestEnemyOf
     REPLACE_TEXTUALLY EighthFarthestEnemyOf NearestEnemyOf
     REPLACE_TEXTUALLY SeventhFarthestEnemyOf NearestEnemyOf
     REPLACE_TEXTUALLY SixthFarthestEnemyOf NearestEnemyOf
     REPLACE_TEXTUALLY FifthFarthestEnemyOf SecondNearestEnemyOf
     REPLACE_TEXTUALLY FourthFarthestEnemyOf ThirdNearestEnemyOf
     REPLACE_TEXTUALLY ThirdFarthestEnemyOf FourthNearestEnemyOf
     REPLACE_TEXTUALLY SecondFarthestEnemyOf FifthNearestEnemyOf
     REPLACE_TEXTUALLY FarthestEnemyOf SixthNearestEnemyOf


  END

END


