//ACTION_IF !GAME_IS "eet bgee bg2ee iwdee" BEGIN  // enforce enhanced-edition
//   FAIL "Requires enhanced edition"
//END

////////////////////////////////////////////////////////
////////////////////////////////////////////////////////
//// 	Things to do only once
////////////////////////////////////////////////////////
////////////////////////////////////////////////////////

ACTION_IF !VARIABLE_IS_SET ~initialise~ BEGIN
    OUTER_SET initialise=1


////////////////////////////////////////////////////////
//// set up the ini
////////////////////////////////////////////////////////

	INCLUDE "%MOD_FOLDER%/lib/lib_ini.tpa"
//    OUTER_SPRINT ini_to_read "%MOD_FOLDER%/%MOD_FOLDER%.ini"
    LAF SFO_read_ini_file STR_VAR ini_to_read = EVAL ~%MOD_FOLDER%/%inifile%~ RET_ARRAY SFO_reserved_ini_hash END

////////////////////////////////////////////////////////
//// general variables, macros and functions
////////////////////////////////////////////////////////
  
  ACTION_IF !VARIABLE_IS_SET do_not_biff BEGIN
     OUTER_SET do_not_biff=0
  END

  ACTION_IF !VARIABLE_IS_SET sfo_loc BEGIN
      OUTER_SPRINT sfo_loc "sfo"
  END
  ACTION_IF !VARIABLE_IS_SET sfo_loc BEGIN
      OUTER_SPRINT ssl_loc "ssl"
  END
  INCLUDE ~%MOD_FOLDER%/%sfo_loc%/install_sfo.tpa~

  OUTER_SPRINT ssllibrary "%MOD_FOLDER%/%ssl_loc%/library.slb"

	////////////////////////////////////////////////////////////////////////////////
    // third-party content check
	////////////////////////////////////////////////////////////////////////////////

        // Detect Spell Revisions

        ACTION_IF FILE_EXISTS_IN_GAME ~dvimhere.mrk~ THEN BEGIN
           OUTER_SET demivrgvs=1
        END ELSE BEGIN
           OUTER_SET ~demivrgvs~=0
        END

////////////////////////////////////////////////////////
//// On BG2EE, include DS
////////////////////////////////////////////////////////

//  ACTION_IF GAME_IS "bgee bg2ee eet" BEGIN
     LAF include STR_VAR file="ds.tph" location="%iwdspells_lib%" END
//  END

END
