INCLUDE ~iwdification/lib/spell_prep.tpa~

/////                                                  \\\\\
///// WIZARD_EMOTION_HOPELESSNESS                      \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_EMOTION_COURAGE~) OR override_arcane) BEGIN // checking courage to see if emotion series is already present, since hopelessness is a vanilla bg2 spell

  ADD_PROJECTILE ~iwdification/pro/cdi255.pro~

  COPY ~iwdification/spl/cdia411.spl~ ~override/spwi411.spl~ // hopelessness
    SAY 0x08 @3001
    SAY 0x50 @3002
    SAY 0x18e @3003
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi255 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 1280 parameter1 = string_stunned END
    PATCH_IF !ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
    END

  COPY_EXISTING ~scrl5h.itm~ ~override~
    SAY 0x0c @3001
    SAY 0x54 @3002
    WRITE_BYTE 0x2d BIT3 // invoker flag
    LPF ALTER_ITEM_HEADER INT_VAR range = 50 target = 4 END
  
  COPY ~iwdification/bam/cdia411a.bam~ ~override~
       ~iwdification/bam/cdia411b.bam~ ~override~
       ~iwdification/bam/cdia411c.bam~ ~override~
       ~iwdification/bam/cdienchx.bam~ ~override~
       ~iwdification/bam/cdiparal.bam~ ~override~
       ~iwdification/vvc/cdigench.vvc~ ~override~
       ~iwdification/vvc/cdiparal.vvc~ ~override~
       ~iwdification/wav/cdiarm21.wav~ ~override~
       ~iwdification/wav/cdiee05.wav~  ~override~
       ~iwdification/wav/cdiem05.wav~  ~override~

END

/////                                                  \\\\\
///// WIZARD_POLYMORPH_SELF                            \\\\\
/////                                                  \\\\\

// these generally 'clean out' the poly self subspells
COPY_EXISTING ~bhaal4a.spl~  ~override~ // resurrection
              ~ohbraise.spl~ ~override~ // nsi
              ~slayerw3.itm~ ~override~ // slater weapon
              ~spja01.spl~   ~override~ // harper's call
              ~sppr504.spl~  ~override~ // raise dead
              ~sppr550.spl~  ~override~ // recall spirit
              ~sppr712.spl~  ~override~ // resurrection
              ~sppr729.spl~  ~override~ // mass raise dead
              ~spwish10.spl~ ~override~ // mass raise dead
  PATCH_IF anim_beetle BEGIN
    LPF CLONE_EFFECT STR_VAR match_resource = spwi499 resource = cdia480 END // boring beetle
  END
  LPF CLONE_EFFECT STR_VAR match_resource = spwi499 resource = cdia481 END // polar bear
  LPF CLONE_EFFECT STR_VAR match_resource = spwi499 resource = cdia482 END // winter wolf
  BUT_ONLY IF_EXISTS

// add new forms to poly self
COPY_EXISTING ~spwi416.spl~  ~override~ // poly self
  PATCH_IF anim_beetle BEGIN
    LPF CLONE_EFFECT STR_VAR match_resource = spwi499 resource = cdia480 END // boring beetle
    SAY 0x50 @3004
  END ELSE BEGIN
    SAY 0x50 @3014
  END
  LPF CLONE_EFFECT STR_VAR match_resource = spwi499 resource = cdia481 END // polar bear
  LPF CLONE_EFFECT STR_VAR match_resource = spwi499 resource = cdia482 END // winter wolf

COPY ~iwdification/spl/cdia481.spl~ ~override~ // polar bear
  SAY 0x08 @3007
  SAY 0x50 @3008

COPY ~iwdification/spl/cdia482.spl~ ~override~ // winter wolf
  SAY 0x08 @3009
  SAY 0x50 @3012

COPY_EXISTING ~cdia481.spl~ ~override~
              ~cdia482.spl~ ~override~
  PATCH_FOR_EACH res IN spin122 spin123 spin124 spin150 spin151 spin160 spin160 spin160 spin529 spin667 spin718 spinhum spmdslay spwi489 spwi490 spwi491 BEGIN
    LPF CLONE_EFFECT INT_VAR match_opcode = 172 STR_VAR match_resource = spin974 resource = EVAL ~%res%~ END
  END
  LPF ALTER_EFFECT INT_VAR match_opcode = 135 opcode = 171 timing = 1 STR_VAR resource = spwi490 END // move polymorph ops to the claws
  LPF DELETE_EFFECT INT_VAR match_opcode = 144 END // move delete button to claws, too

//LAF cd_animation STR_VAR code = 7203 END // 29187 MBER_PO bear_polar
COPY ~iwdification/cre/cdidrupb.cre~ ~override~
  SAY 0x08 @3015
  SAY 0x0c @3015

//LAF cd_animation STR_VAR code = 7b03 END // 31491 MWLF_WI wolf_winter
COPY ~iwdification/cre/cdidruww.cre~ ~override~
  WRITE_LONG 0x08 string_wwolf
  WRITE_LONG 0x0c string_wwolf

COPY ~iwdification/itm/cdiplypb.itm~ ~override~
     ~iwdification/itm/cdiplyww.itm~ ~override~
  WRITE_LONG 0x08 string_attack
  WRITE_LONG 0x0c string_attack

COPY_EXISTING ~cdiplypb.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 144 target = 1 parameter2 = 7 timing = 2 END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 135 target = 1 timing = 2 STR_VAR resource = cdidrupb END

COPY_EXISTING ~cdiplyww.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 144 target = 1 parameter2 = 7 timing = 2 END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 135 target = 1 timing = 2 STR_VAR resource = cdidruww END

COPY ~iwdification/bam/cdia481b.bam~ ~override~
     ~iwdification/bam/cdia482b.bam~ ~override~
     ~iwdification/bam/cdiplypb.bam~ ~override~
     ~iwdification/bam/cdiplyww.bam~ ~override~

ACTION_IF anim_beetle BEGIN

  COPY ~iwdification/spl/cdia480.spl~ ~override~ // boring beetle
    SAY 0x08 @3005
    SAY 0x50 @3006
    PATCH_FOR_EACH res IN spin122 spin123 spin124 spin150 spin151 spin160 spin160 spin160 spin529 spin667 spin718 spinhum spmdslay spwi489 spwi490 spwi491 BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 172 STR_VAR match_resource = spin974 resource = EVAL ~%res%~ END
    END
    LPF ALTER_EFFECT INT_VAR match_opcode = 135 opcode = 171 timing = 1 STR_VAR resource = spwi490 END // move polymorph ops to the claws
    LPF DELETE_EFFECT INT_VAR match_opcode = 144 END // move delete button to claws, too

  LAF cd_animation STR_VAR code = e220 END // 57888 MBBM beetle_black
  COPY ~iwdification/cre/cdidrubb.cre~ ~override~
    SAY 0x08 @3013
    SAY 0x0c @3013
    WRITE_LONG 0x28 anim_beetle

  COPY ~iwdification/itm/cdiplybb.itm~ ~override~
       ~iwdification/itm/cdis5-20.itm~ ~override~
    WRITE_LONG 0x08 string_attack
    WRITE_LONG 0x0c string_attack
  
  COPY_EXISTING ~cdiplybb.itm~ ~override~
    LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 144 target = 1 parameter2 = 7 timing = 2 END
    LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 135 target = 1 timing = 2 STR_VAR resource = cdidrubb END
  
  COPY ~iwdification/bam/cdia480b.bam~ ~override~
       ~iwdification/bam/cdiplybb.bam~ ~override~

END

/////                                                  \\\\\
///// WIZARD_EXPEDITIOUS_RETREAT                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_EXPEDITIOUS_RETREAT~) OR override_arcane) BEGIN

  ADD_SPELL ~iwdification/spl/cdia126.spl~ 2 1 WIZARD_EXPEDITIOUS_RETREAT
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3010 // name
    SAY 0x50 @3011 // descript
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37787 parameter1 = string_slowed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37638 parameter1 = string_slow END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 36035 parameter1 = string_hasted END
    PATCH_IF !ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia126.itm~
    SAY 0x0c @3010
    SAY 0x54 @3011
    LPF cd_scroll INT_VAR unusable2 = BIT6 target_hdr = 5 range = 1 price = 100 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia126a.bam~ ~override~
       ~iwdification/bam/cdia126b.bam~ ~override~
       ~iwdification/bam/cdia126c.bam~ ~override~

END

/////                                                  \\\\\
///// WIZARD_SNILLOCS_SNOWBALL_SWARM                   \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SNILLOCS_SNOWBALL_SWARM~) OR override_arcane) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi217.pro~

  ADD_SPELL ~iwdification/spl/cdia204.spl~ 2 2 WIZARD_SNILLOCS_SNOWBALL_SWARM
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3020 // name
    SAY 0x50 @3021 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi217 END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdia204 resource = EVAL ~%DEST_RES%~ END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 318 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 12 multi_match = 1 END // delete one of these
      LPF CD_SPLIT_SAVE_DAMAGE END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia204.itm~
    SAY 0x0c @3020
    SAY 0x54 @3021
    LPF cd_scroll INT_VAR unusable1 = BIT1 target_hdr = 4 range = 40 opcode = 148 target_eff = 1 price = 900 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia204a.bam~ ~override~
       ~iwdification/bam/cdia204b.bam~ ~override~
       ~iwdification/bam/cdia204c.bam~ ~override~
       ~iwdification/vvc/cdissswa.vvc~ ~override~ // pro resources
       ~iwdification/bam/cdiswarr.bam~ ~override~
       ~iwdification/bam/cdiswart.bam~ ~override~
       ~iwdification/bam/cdissswx.bam~ ~override~
       ~iwdification/wav/cdirngm2.wav~ ~override~
       ~iwdification/wav/cditra18.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY_EXISTING ~cdi217.pro~ ~override~
      WRITE_BYTE 0x217 14
  
  END

END

/////                                                  \\\\\
///// WIZARD_DECASTAVE                                 \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_DECASTAVE~) OR override_arcane) BEGIN

  ADD_SPELL ~iwdification/spl/cdia216.spl~ 2 2 WIZARD_DECASTAVE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3030 // name
    SAY 0x50 @3031 // descript

  COPY ~iwdification/itm/blank.itm~ ~override/cdia216.itm~
    SAY 0x0c @3030
    SAY 0x54 @3031
    LPF cd_scroll INT_VAR unusable1 = BIT1 target_hdr = 5 range = 1 target_eff = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/itm/cdideca.itm~ ~override~
    SAY 0x08 @3030
    SAY 0x0c @3030
    PATCH_IF !ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 12 opcode = 146 parameter2 = 1 special = 0 dicenumber = 0 dicesize = 0 STR_VAR resource = cdideca END
    END

  COPY ~iwdification/bam/cdia216a.bam~ ~override~
       ~iwdification/bam/cdia216b.bam~ ~override~
       ~iwdification/bam/cdia216c.bam~ ~override~
       ~iwdification/bam/cdideca.bam~  ~override~
       ~iwdification/bam/cdiinvoc.bam~ ~override~
       ~iwdification/vvc/cdiinvoc.vvc~ ~override~
       ~iwdification/wav/cdiee02.wav~  ~override~
       ~iwdification/wav/cdiem06.wav~  ~override~

  ACTION_IF !ee_game BEGIN
    
    COPY ~iwdification/spl/cdideca.spl~  ~override~

  END

END

/////                                                  \\\\\
///// WIZARD_CATS_GRACE                                \\\\\
/////                                                  \\\\\

ACTION_IF ((ee_game OR tobex_game) AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_CATS_GRACE~) OR override_arcane)) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@3040) STR_VAR bam_file = cdia225d RET icon END

  ADD_SPELL ~iwdification/spl/cdia225.spl~ 2 2 WIZARD_CATS_GRACE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3040 // name
    SAY 0x50 @3041 // descript
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14024 parameter1 = string_dexmod END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdia225 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 185 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 328 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 15 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = EVAL ~%DEST_RES%~ END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia225.itm~
    SAY 0x0c @3040
    SAY 0x54 @3041
    LPF cd_scroll INT_VAR unusable2 = BIT6 range = 1 STR_VAR price = 200 spell = EVAL ~%current_spell_res%~ END

  ACTION_IF ee_game BEGIN
    APPEND ~splstate.ids~ ~45 CATS_GRACE~ UNLESS ~^45[ %TAB%]+CATS_GRACE[ %TAB%%LNL%%MNL%%WNL%]+~
  END

  COPY ~iwdification/bam/cdia225a.bam~ ~override~
       ~iwdification/bam/cdia225b.bam~ ~override~
       ~iwdification/bam/cdia225c.bam~ ~override~
       ~iwdification/bam/cdia225d.bam~ ~override~
       ~iwdification/wav/cdiem08.wav~  ~override~

END

/////                                                  \\\\\
///// WIZARD_ICELANCE                                  \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_ICELANCE~) OR override_arcane) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi251.pro~

  ADD_SPELL ~iwdification/spl/cdia327.spl~ 2 3 WIZARD_ICELANCE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3050 // name
    SAY 0x50 @3051 // descript
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 35568 parameter1 = string_stunned END
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi251 END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia327.itm~
    SAY 0x0c @3050
    SAY 0x54 @3051
    LPF cd_scroll INT_VAR unusable1 = BIT1 range = 100 price = 900 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia327a.bam~ ~override~
       ~iwdification/bam/cdia327b.bam~ ~override~
       ~iwdification/bam/cdia327c.bam~ ~override~
       ~iwdification/bam/cdiiceln.bam~ ~override~
       ~iwdification/wav/cditra19.wav~ ~override~

END

/////                                                  \\\\\
///// WIZARD_LANCE_OF_DISRUPTION                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_LANCE_OF_DISRUPTION~) OR override_arcane) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi313.pro~
  
  END ELSE BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi313a.pro~

  END

  ADD_SPELL ~iwdification/spl/cdia328.spl~ 2 3 WIZARD_LANCE_OF_DISRUPTION
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3060 // name
    SAY 0x50 @3061 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdia328 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi313 END
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi313a END
      LPF ALTER_EFFECT INT_VAR match_opcode = 318 opcode = 206 target = 1 parameter2 = 0 STR_VAR match_resource = cdia328 resource = EVAL ~%DEST_RES%~ END
      LPF CD_SPLIT_SAVE_DAMAGE END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia328.itm~
    SAY 0x0c @3060
    SAY 0x54 @3061
    LPF cd_scroll INT_VAR unusable1 = BIT1 target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 600 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia328a.bam~ ~override~
       ~iwdification/bam/cdia328b.bam~ ~override~
       ~iwdification/bam/cdia328c.bam~ ~override~
       ~iwdification/bam/cdiinvoc.bam~ ~override~
       ~iwdification/bam/cdilodis.bam~ ~override~
       ~iwdification/vvc/cdiinvoc.vvc~ ~override~
       ~iwdification/wav/cdiem06.wav~  ~override~
       ~iwdification/wav/cditra59.wav~ ~override~

END

/////                                                  \\\\\
///// WIZARD_BELTYNS_BURNING_BLOOD                     \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_BELTYNS_BURNING_BLOOD~) OR override_arcane) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@3070) STR_VAR bam_file = cdia422d RET icon END

  ADD_SPELL ~iwdification/spl/cdia422.spl~ 2 4 WIZARD_BELTYNS_BURNING_BLOOD
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3070 // name
    SAY 0x50 @3071 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdia422 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 66 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 66 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  9 opcode = 177 parameter1 = 145 parameter2 = 4 STR_VAR resource = cdixa422 END // race = elemental
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixa422 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixa422 END // general = undead
      LPF CD_CONVERT_333 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia422.itm~
    SAY 0x0c @3070
    SAY 0x54 @3071
    LPF cd_scroll INT_VAR unusable1 = BIT2 range = 200 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/spl/cdia422a.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37605 parameter1 = string_berserk END

  COPY ~iwdification/bam/cdia422a.bam~ ~override~
       ~iwdification/bam/cdia422b.bam~ ~override~
       ~iwdification/bam/cdia422c.bam~ ~override~
       ~iwdification/bam/cdia422d.bam~ ~override~
       ~iwdification/bam/cdinecro.bam~ ~override~
       ~iwdification/vvc/cdinecro.vvc~ ~override~
       ~iwdification/wav/cdiem07.wav~  ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixa422.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// WIZARD_SHADOW_MONSTERS                           \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SHADOW_MONSTERS~) OR override_arcane) BEGIN

  LAF cd_new_summon_table STR_VAR descript = "SHADOW_MONSTERS" 2da_file = cdismons RET table END

  ADD_SPELL ~iwdification/spl/cdia426.spl~ 2 4 WIZARD_SHADOW_MONSTERS
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3080 // name
    SAY 0x50 @3081 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      READ_SHORT 0x68 abil_num
      LPF ALTER_EFFECT INT_VAR header = 0 match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdismons END
      FOR (index = 1 ; index < abil_num ; ++index) BEGIN
        LPF ALTER_EFFECT INT_VAR header = index match_opcode = 331 opcode = 127 parameter1 = (index + 7) parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdismons END
      END
      LPF CLONE_EFFECT INT_VAR match_opcode = 127 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia426.itm~
    SAY 0x0c @3080
    SAY 0x54 @3081
    LPF cd_scroll INT_VAR unusable1 = BIT4 target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 1200 STR_VAR spell = EVAL ~%current_spell_res%~ END

  LAF cd_animation STR_VAR code = e400 END // 58368 MGO1 goblin_axe    
  COPY ~iwdification/cre/cdis1gb1.cre~ ~override~
       ~iwdification/cre/cdis1gb2.cre~ ~override~
       ~iwdification/cre/cdis1gb3.cre~ ~override~
    WRITE_LONG  0x08 string_goblin
    WRITE_LONG  0x0c string_goblin

  LAF cd_animation STR_VAR code = e510 END // 58640 MLI2 lizard_man
  COPY ~iwdification/cre/cdis1lz3.cre~ ~override~
       ~iwdification/cre/cdis1lz4.cre~ ~override~
    SAY 0x08 @3082
    SAY 0x0c @3082
    WRITE_LONG 0x28 anim_lizman

  LAF cd_animation STR_VAR code = e0b0 END // 57520 MTRO troll_blue - MTRO doubles with bg2 troll
  COPY ~iwdification/cre/cdis1tr6.cre~ ~override~
       ~iwdification/cre/cdis1tr7.cre~ ~override~
       ~iwdification/cre/cdis1tr8.cre~ ~override~
    WRITE_LONG  0x08 string_troll
    WRITE_LONG  0x0c string_troll
    WRITE_LONG 0x28 anim_btroll

  COPY ~iwdification/itm/cdim1d7s.itm~ ~override~
    WRITE_LONG  0x08 string_attack
    WRITE_LONG  0x0c string_attack

  COPY ~iwdification/2da/cdismons.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

  COPY ~iwdification/bam/cdia426a.bam~ ~override~
       ~iwdification/bam/cdia426b.bam~ ~override~
       ~iwdification/bam/cdia426c.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdimsm1x.bam~ ~override~
       ~iwdification/itm/cdisumrn.itm~ ~override~
       ~iwdification/itm/cditrn20.itm~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~
       ~iwdification/vvc/cdimsm1x.vvc~ ~override~

END

/////                                                  \\\\\
///// WIZARD_EMOTION_COURAGE                           \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_EMOTION_COURAGE~) OR override_arcane) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@3092) STR_VAR bam_file = cdia427d RET icon END

  ADD_PROJECTILE ~iwdification/pro/cdi407.pro~

  ADD_SPELL ~iwdification/spl/cdia427.spl~ 2 4 WIZARD_EMOTION_COURAGE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3090 // name
    SAY 0x50 @3091 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi407 END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdia427 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 187 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 187 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = EVAL ~%DEST_RES%~ END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia427.itm~
    SAY 0x0c @3090
    SAY 0x54 @3091
    LPF cd_scroll INT_VAR unusable1 = BIT3 target_hdr = 4 range = 50 opcode = 148 target_eff = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia427a.bam~ ~override~
       ~iwdification/bam/cdia427b.bam~ ~override~
       ~iwdification/bam/cdia427c.bam~ ~override~
       ~iwdification/bam/cdia427d.bam~ ~override~
       ~iwdification/bam/cdiencha.bam~ ~override~
       ~iwdification/vvc/cdiencha.vvc~ ~override~
       ~iwdification/wav/cdiee03.wav~  ~override~
       ~iwdification/wav/cdiem05.wav~  ~override~

END

/////                                                  \\\\\
///// WIZARD_EMOTION_FEAR                              \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_EMOTION_FEAR~) OR override_arcane) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi255.pro~

  ADD_SPELL ~iwdification/spl/cdia428.spl~ 2 4 WIZARD_EMOTION_FEAR
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3100 // name
    SAY 0x50 @3101 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi255 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 35484 parameter1 = string_panic END
    PATCH_IF !ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia428.itm~
    SAY 0x0c @3100
    SAY 0x54 @3101
    LPF cd_scroll INT_VAR unusable1 = BIT3 target_hdr = 4 range = 50 opcode = 148 target_eff = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia428a.bam~ ~override~
       ~iwdification/bam/cdia428b.bam~ ~override~
       ~iwdification/bam/cdia428c.bam~ ~override~
       ~iwdification/bam/cdiencha.bam~ ~override~
       ~iwdification/bam/cdienchx.bam~ ~override~
       ~iwdification/vvc/cdiencha.vvc~ ~override~
       ~iwdification/vvc/cdigench.vvc~ ~override~
       ~iwdification/wav/cdiarm21.wav~ ~override~
       ~iwdification/wav/cdiee05.wav~  ~override~
       ~iwdification/wav/cdiem05.wav~  ~override~

END

/////                                                  \\\\\
///// WIZARD_EMOTION_HOPE                              \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_EMOTION_HOPE~) OR override_arcane) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@3112) STR_VAR bam_file = cdia429d RET icon END

  ADD_PROJECTILE ~iwdification/pro/cdi407.pro~

  ADD_SPELL ~iwdification/spl/cdia429.spl~ 2 4 WIZARD_EMOTION_HOPE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3110 // name
    SAY 0x50 @3111 // descript
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = spin115 END
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi407 END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 186 parameter2 = icon END
      LPF ALTER_EFFECT STR_VAR match_resource = cdia429 resource = EVAL ~%DEST_RES%~ END
    END ELSE BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 186 parameter2 = 22 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = EVAL ~%DEST_RES%~ END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia429.itm~
    SAY 0x0c @3110
    SAY 0x54 @3111
    LPF cd_scroll INT_VAR unusable1 = BIT3 target_hdr = 4 range = 50 opcode = 148 target_eff = 1 price = 600 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia429a.bam~ ~override~
       ~iwdification/bam/cdia429b.bam~ ~override~
       ~iwdification/bam/cdia429c.bam~ ~override~
       ~iwdification/bam/cdia429d.bam~ ~override~
       ~iwdification/bam/cdiencha.bam~ ~override~
       ~iwdification/vvc/cdiencha.vvc~ ~override~
       ~iwdification/wav/cdiee03.wav~  ~override~
       ~iwdification/wav/cdiem05.wav~  ~override~

END

/////                                                  \\\\\
///// WIZARD_MORDENKAINENS_FORCE_MISSILES              \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_MORDENKAINENS_FORCE_MISSILES~) OR override_arcane)) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdimfm.pro~
  ADD_PROJECTILE ~iwdification/pro/cdimfm2.pro~

  // ADD_PROJECTILE won't add multiple versions of the same projectile, but it's needed for MFM's special projectile chain - do it manually
  OUTER_FOR (index = (cdimfm2 + 1) ; index < (cdimfm2 + 10) ; ++index) BEGIN
  
    APPEND ~projectl.ids~ ~%index% cdimfm2~
  
  END

  ADD_SPELL ~iwdification/spl/cdia430.spl~ 2 4 WIZARD_MORDENKAINENS_FORCE_MISSILES
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3120 // name
    SAY 0x50 @3121 // descript
    LPF ALTER_SPELL_HEADER INT_VAR header =  1 projectile = (cdimfm + 0) END
    LPF ALTER_SPELL_HEADER INT_VAR header =  2 projectile = (cdimfm + 0) END
    LPF ALTER_SPELL_HEADER INT_VAR header =  3 projectile = (cdimfm + 0) END
    LPF ALTER_SPELL_HEADER INT_VAR header =  4 projectile = (cdimfm + 1) END
    LPF ALTER_SPELL_HEADER INT_VAR header =  5 projectile = (cdimfm + 1) END
    LPF ALTER_SPELL_HEADER INT_VAR header =  6 projectile = (cdimfm + 1) END
    LPF ALTER_SPELL_HEADER INT_VAR header =  7 projectile = (cdimfm + 2) END
    LPF ALTER_SPELL_HEADER INT_VAR header =  8 projectile = (cdimfm + 2) END
    LPF ALTER_SPELL_HEADER INT_VAR header =  9 projectile = (cdimfm + 2) END
    LPF ALTER_SPELL_HEADER INT_VAR header = 10 projectile = (cdimfm + 3) END
    LPF ALTER_SPELL_HEADER INT_VAR header = 11 projectile = (cdimfm + 3) END
    LPF ALTER_SPELL_HEADER INT_VAR header = 12 projectile = (cdimfm + 3) END
    LPF ALTER_SPELL_HEADER INT_VAR header = 13 projectile = (cdimfm + 4) END
    LPF ALTER_SPELL_HEADER INT_VAR header = 14 projectile = (cdimfm + 4) END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia430.itm~
    SAY 0x0c @3120
    SAY 0x54 @3121
    LPF cd_scroll INT_VAR unusable1 = BIT1 range = 100 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia430a.bam~ ~override~
       ~iwdification/bam/cdia430b.bam~ ~override~
       ~iwdification/bam/cdia430c.bam~ ~override~
       ~iwdification/bam/cdimfmsx.bam~ ~override~
       ~iwdification/bam/cdimfmt.bam~ ~override~
       ~iwdification/spl/cdia430b.spl~ ~override~
       ~iwdification/vvc/cdimfmsx.vvc~ ~override~
       ~iwdification/wav/cdiarm02.wav~ ~override~
       ~iwdification/wav/cdiem103.wav~ ~override~
       ~iwdification/wav/cditra55.wav~ ~override~

END

/////                                                  \\\\\
///// WIZARD_SHOUT                                     \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SHOUT~) OR override_arcane)) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi315.pro~

  ADD_SPELL ~iwdification/spl/cdia431.spl~ 2 4 WIZARD_SHOUT
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3130 // name
    SAY 0x50 @3131 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi315 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14073 parameter1 = string_deafness END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia431.itm~
    SAY 0x0c @3130
    SAY 0x54 @3131
    LPF cd_scroll INT_VAR unusable1 = BIT1 target_hdr = 4 range = 22 opcode = 148 target_eff = 1 price = 1200 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia431a.bam~ ~override~
       ~iwdification/bam/cdia431b.bam~ ~override~
       ~iwdification/bam/cdia431c.bam~ ~override~
       ~iwdification/bam/cdishout.bam~ ~override~
       ~iwdification/wav/cdiem100.wav~ ~override~
       ~iwdification/wav/cditra08.wav~ ~override~

END

/////                                                  \\\\\
///// WIZARD_VITRIOLIC_SPHERE                          \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_VITRIOLIC_SPHERE~) OR override_arcane) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi316.pro~

  ADD_SPELL ~iwdification/spl/cdia432.spl~ 2 4 WIZARD_VITRIOLIC_SPHERE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3140 // name
    SAY 0x50 @3141 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi316 END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia432.itm~
    SAY 0x0c @3140
    SAY 0x54 @3141
    LPF cd_scroll INT_VAR unusable1 = (BIT0 + BIT3) range = 100 price = 1600 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia432a.bam~ ~override~
       ~iwdification/bam/cdia432b.bam~ ~override~
       ~iwdification/bam/cdia432c.bam~ ~override~
       ~iwdification/bam/cdiacid.bam~  ~override~
       ~iwdification/bam/cdivitst.bam~ ~override~
       ~iwdification/bam/cdivitsx.bam~ ~override~
       ~iwdification/spl/cdia432y.spl~ ~override~
       ~iwdification/spl/cdia432z.spl~ ~override~
       ~iwdification/vvc/cdiacid.vvc~  ~override~
       ~iwdification/vvc/cdivitsx.vvc~ ~override~
       ~iwdification/wav/cdiem34.wav~  ~override~
       ~iwdification/wav/cdiem47.wav~  ~override~
       ~iwdification/wav/cditra60.wav~ ~override~

END

/////                                                  \\\\\
///// WIZARD_SHROUD_OF_FLAME                           \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SHROUD_OF_FLAME~) OR override_arcane) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@3150) STR_VAR bam_file = cdia524d RET icon END

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdishrod.pro~
  
  END ELSE BEGIN
  
    OUTER_SET cdishrod = 216
  
  END

  ADD_SPELL ~iwdification/spl/cdia524.spl~ 2 5 WIZARD_SHROUD_OF_FLAME
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3150 // name
    SAY 0x50 @3151 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdia524 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 333 STR_VAR resource = cdia524b END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 94 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 94 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 328 END
      LPF CD_CONVERT_333 STR_VAR 333spell = cdia524b END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia524.itm~
    SAY 0x0c @3150
    SAY 0x54 @3151
    LPF cd_scroll INT_VAR unusable1 = BIT1 range = 100 price = 1500 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/spl/cdia524b.spl~ ~override~
    SAY 0x08 @3150 // name
    SAY 0x50 @3151 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdishrod END
    PATCH_IF !ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 328 END
      LPF CD_CONVERT_9_255 END
    END

  COPY ~iwdification/bam/cdia524a.bam~ ~override~
       ~iwdification/bam/cdia524b.bam~ ~override~
       ~iwdification/bam/cdia524c.bam~ ~override~
       ~iwdification/bam/cdia524d.bam~ ~override~
       ~iwdification/bam/cdisofl.bam~  ~override~
       ~iwdification/vvc/cdisofl.vvc~  ~override~

END

/////                                                  \\\\\
///// WIZARD_DEMI_SHADOW_MONSTERS                      \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_DEMI_SHADOW_MONSTERS~) OR override_arcane) BEGIN

  LAF cd_new_summon_table STR_VAR descript = "DEMI_SHADOW_MONSTERS" 2da_file = cdidsmon RET table END

  ADD_SPELL ~iwdification/spl/cdia525.spl~ 2 5 WIZARD_DEMI_SHADOW_MONSTERS
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3160 // name
    SAY 0x50 @3161 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      READ_SHORT 0x68 abil_num
      LPF ALTER_EFFECT INT_VAR header = 0 match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdidsmon END
      FOR (index = 1 ; index < abil_num ; ++index) BEGIN
        LPF ALTER_EFFECT INT_VAR header = index match_opcode = 331 opcode = 127 parameter1 = (index + 9) parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdidsmon END
      END
      LPF CLONE_EFFECT INT_VAR match_opcode = 127 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia525.itm~
    SAY 0x0c @3160
    SAY 0x54 @3161
    LPF cd_scroll INT_VAR unusable1 = BIT4 target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 1500 STR_VAR spell = EVAL ~%current_spell_res%~ END

  LAF cd_animation STR_VAR code = e420 END // 58400 MGO3 goblin_elite_axe
  COPY ~iwdification/cre/cdis2gb1.cre~ ~override~
       ~iwdification/cre/cdis2gb2.cre~ ~override~
       ~iwdification/cre/cdis2gb3.cre~ ~override~
    SAY 0x08 @3162
    SAY 0x0c @3162

  LAF cd_animation STR_VAR code = e500 END // 58624 MLIZ lizard_man_elite
  COPY ~iwdification/cre/cdis2lz5.cre~ ~override~
       ~iwdification/cre/cdis2lz6.cre~ ~override~
       ~iwdification/cre/cdis2lz7.cre~ ~override~
    SAY 0x08 @3163
    SAY 0x0c @3163

  COPY ~iwdification/bam/cdia525a.bam~ ~override~
       ~iwdification/bam/cdia525b.bam~ ~override~
       ~iwdification/bam/cdia525c.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdimsm1x.bam~ ~override~
       ~iwdification/itm/cdisumrn.itm~ ~override~
       ~iwdification/itm/cditrn40.itm~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~
       ~iwdification/vvc/cdimsm1x.vvc~ ~override~

  COPY ~iwdification/2da/cdidsmon.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// WIZARD_SUMMON_SHADOW                             \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SUMMON_SHADOW~) OR override_arcane) BEGIN

  LAF cd_new_summon_table STR_VAR descript = "SUMMON_SHADOW" 2da_file = cdishadw RET table END

  ADD_SPELL ~iwdification/spl/cdia526.spl~ 2 5 WIZARD_SUMMON_SHADOW
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3170 // name
    SAY 0x50 @3171 // descript    
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 12 parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdishadw END // shadows are level 4, so p1=12 should mean 3 shadows
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia526.itm~
    SAY 0x0c @3170
    SAY 0x54 @3171
    LPF cd_scroll INT_VAR target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 1500 STR_VAR spell = EVAL ~%current_spell_res%~ END

  LAF cd_animation STR_VAR code = ea20 END // 59936 MSH2 shadow_large
  COPY ~iwdification/cre/cdisshad.cre~ ~override~
    WRITE_LONG 0x08 string_shadow
    WRITE_LONG 0x0c string_shadow
    WRITE_LONG 0x28 anim_shadow_lg

  COPY ~iwdification/itm/cdishdw1.itm~ ~override~
    WRITE_LONG  0x08 string_attack
    WRITE_LONG  0x0c string_attack

  COPY ~iwdification/spl/cdishdw1.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 35593 parameter1 = string_diseased END

  COPY ~iwdification/bam/cdia526a.bam~ ~override~
       ~iwdification/bam/cdia526b.bam~ ~override~
       ~iwdification/bam/cdia526c.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdimsm1x.bam~ ~override~
       ~iwdification/bam/cdinecro.bam~ ~override~
       ~iwdification/itm/cditrn60.itm~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~
       ~iwdification/vvc/cdimsm1x.vvc~ ~override~
       ~iwdification/vvc/cdinecro.vvc~ ~override~

  COPY ~iwdification/2da/cdishadw.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// WIZARD_CONTACT_OTHER_PLANE                       \\\\\
/////                                                  \\\\\

/* awaiting dialogue for cdia528.d
ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_CONTACT_OTHER_PLANE~) OR override_arcane) BEGIN

  ADD_SPELL ~iwdification/spl/cdia528.spl~ 2 5 WIZARD_CONTACT_OTHER_PLANE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3180 // name
    SAY 0x50 @3181 // descript

  COPY ~iwdification/itm/blank.itm~ ~override/cdia528.itm~
    SAY 0x0c @3180
    SAY 0x54 @3181
    LPF cd_scroll INT_VAR unusable2 = BIT7 target_hdr = 5 range = 1 target_eff = 1 price = 500 STR_VAR spell = EVAL ~%current_spell_res%~ END

  LAF cd_animation STR_VAR code = e300 END // 58112 MGHO ghost
  COPY ~iwdification/cre/cdia528.cre~ ~override~
    SAY 0x08 @3182
    SAY 0x0c @3182
    WRITE_LONG 0x28 anim_ghost
    WRITE_ASCII 0x2cc ~cdia528~ #8 // dlg

  APPEND ~state.ids~ ~0x00000FC0 STATE_REALLY_DEAD~ UNLESS ~^0x00000FC0[ %TAB]+STATE_REALLY_DEAD[ %TAB%%LNL%%MNL%%WNL%]~

  COMPILE ~iwdification/baf/cdia528.baf~
          ~iwdification/dlg/cdia528.d~

  COPY ~iwdification/bam/cdia528a.bam~ ~override~
       ~iwdification/bam/cdia528b.bam~ ~override~
       ~iwdification/bam/cdia528c.bam~ ~override~
       ~iwdification/bam/cdidivin.bam~ ~override~
       ~iwdification/eff/cdia528.eff~  ~override~
       ~iwdification/vvc/cdidivin.vvc~ ~override~
       ~iwdification/wav/cdiem01.wav~  ~override~

END
*/

/////                                                  \\\\\
///// WIZARD_CONJURE_FIRE_ELEMENTAL                    \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_CONJURE_FIRE_ELEMENTAL~) OR override_arcane) BEGIN

  APPEND ~spell.ids~ ~2516 WIZARD_CONJURE_FIRE_ELEMENTAL~ // alternate identifier

  LAF cd_new_summon_table STR_VAR descript = "FIRE_ELEMENTAL_WIZ" 2da_file = cdifelmw RET table END

  COPY ~iwdification/spl/cdia531.spl~ ~override/spwi516.spl~
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3190 // name
    SAY 0x50 @3191 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF ALTER_EFFECT INT_VAR index match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdifelmw END
      LPF CLONE_EFFECT INT_VAR match_opcode = 127 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/scrl6x.itm~
    SAY 0x0c @3190
    SAY 0x54 @3191
    LPF cd_scroll INT_VAR unusable1 = (BIT0 + BIT3) target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 1500 STR_VAR spell = EVAL ~%current_spell_res%~ END

  LAF cd_animation STR_VAR code = e24c END // 57932 MELF elemental_fire_iwd
  COPY ~iwdification/cre/cdi8fire.cre~ ~override~
    SAY 0x08 @3192
    SAY 0x0c @3192
    WRITE_LONG 0x28 anim_felem

  COPY ~iwdification/itm/cdifel18.itm~ ~override~
    WRITE_LONG 0x08 string_attack
    WRITE_LONG 0x0c string_attack

  COPY ~iwdification/bam/cdia531a.bam~ ~override~
       ~iwdification/bam/cdia531b.bam~ ~override~
       ~iwdification/bam/cdia531c.bam~ ~override~
       ~iwdification/bam/cdicfelx.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/vvc/cdicfelx.vvc~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~

  COPY ~iwdification/2da/cdifelmw.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// WIZARD_CONJURE_EARTH_ELEMENTAL                    \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_CONJURE_EARTH_ELEMENTAL~) OR override_arcane) BEGIN

  APPEND ~spell.ids~ ~2521 WIZARD_CONJURE_EARTH_ELEMENTAL~ // alternate identifier

  LAF cd_new_summon_table STR_VAR descript = "EARTH_ELEMENTAL_WIZ" 2da_file = cdieelmw RET table END

  COPY ~iwdification/spl/cdia532.spl~ ~override/spwi521.spl~
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3200 // name
    SAY 0x50 @3201 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF ALTER_EFFECT INT_VAR index match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdieelmw END
      LPF CLONE_EFFECT INT_VAR match_opcode = 127 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/scrl7c.itm~
    SAY 0x0c @3200
    SAY 0x54 @3201
    LPF cd_scroll INT_VAR unusable1 = (BIT0 + BIT3) target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 1500 STR_VAR spell = EVAL ~%current_spell_res%~ END

  LAF cd_animation STR_VAR code = e24b END // 57931 MELE elemental_earth_iwd
  COPY ~iwdification/cre/cdi8erth.cre~ ~override~
    SAY 0x08 @3202
    SAY 0x0c @3202
    WRITE_LONG 0x28 anim_eelem

  COPY ~iwdification/itm/cdieelem.itm~ ~override~
    WRITE_LONG 0x08 string_attack
    WRITE_LONG 0x0c string_attack

  COPY ~iwdification/bam/cdia532a.bam~ ~override~
       ~iwdification/bam/cdia532b.bam~ ~override~
       ~iwdification/bam/cdia532c.bam~ ~override~
       ~iwdification/bam/cdiceelx.bam~ ~override~
       ~iwdification/bam/cdieelem.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/vvc/cdiceelx.vvc~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~

  COPY ~iwdification/2da/cdieelmw.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// WIZARD_CONJURE_WATER_ELEMENTAL                   \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_CONJURE_WATER_ELEMENTAL~) OR override_arcane) BEGIN

  LAF cd_new_summon_table STR_VAR descript = "WATER_ELEMENTAL_WIZ" 2da_file = cdiwelmw RET table END

  ADD_SPELL ~iwdification/spl/cdia533.spl~ 2 5 WIZARD_CONJURE_WATER_ELEMENTAL
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3220 // name
    SAY 0x50 @3221 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF ALTER_EFFECT INT_VAR index match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdiwelmw END
      LPF CLONE_EFFECT INT_VAR match_opcode = 127 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia533.itm~
    SAY 0x0c @3220
    SAY 0x54 @3221
    LPF cd_scroll INT_VAR unusable1 = BIT0 + BIT3 target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 1500 STR_VAR spell = EVAL ~%current_spell_res%~ END

  LAF cd_animation STR_VAR code = e24d END // 57933 MELW elemental_water
  COPY ~iwdification/cre/cdi8watr.cre~ ~override~
    SAY 0x08 @3222
    SAY 0x0c @3222
    WRITE_LONG 0x28 anim_welem
    WRITE_ASCII 0x250 ~~ #8 // blank script that makes elementals ignore targets with SHLDBCH, as not relevant outside of IWD

  COPY ~iwdification/itm/cdiwelem.itm~ ~override~
    WRITE_LONG 0x08 string_attack
    WRITE_LONG 0x0c string_attack

  COPY ~iwdification/bam/cdia533a.bam~ ~override~
       ~iwdification/bam/cdia533b.bam~ ~override~
       ~iwdification/bam/cdia533c.bam~ ~override~
       ~iwdification/bam/cdicwelx.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdiwelem.bam~ ~override~
       ~iwdification/itm/cditrn4.itm~  ~override~
       ~iwdification/vvc/cdicwelx.vvc~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~

  COPY ~iwdification/2da/cdiwelmw.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// WIZARD_CONJURE_AIR_ELEMENTAL                    \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_CONJURE_AIR_ELEMENTAL~) OR override_arcane) BEGIN

  APPEND ~spell.ids~ ~2520 WIZARD_CONJURE_AIR_ELEMENTAL~ // alternate identifier

  LAF cd_new_summon_table STR_VAR descript = "AIR_ELEMENTAL_WIZ" 2da_file = cdiaelmw RET table END

  COPY ~iwdification/spl/cdia534.spl~ ~override/spwi520.spl~
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3210 // name
    SAY 0x50 @3211 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF ALTER_EFFECT INT_VAR index match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdiaelmw END
      LPF CLONE_EFFECT INT_VAR match_opcode = 127 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/scrl7b.itm~
    SAY 0x0c @3210
    SAY 0x54 @3211
    LPF cd_scroll INT_VAR unusable1 = (BIT0 + BIT3) target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 1500 STR_VAR spell = EVAL ~%current_spell_res%~ END

//  LAF cd_animation STR_VAR code = 7320 END // 29472 MAIR elemental_air
  COPY ~iwdification/cre/cdi8air.cre~ ~override~
    SAY 0x08 @3212
    SAY 0x0c @3212

  COPY ~iwdification/itm/cdiaelem.itm~ ~override~
    WRITE_LONG 0x08 string_attack
    WRITE_LONG 0x0c string_attack

  COPY ~iwdification/bam/cdia534a.bam~ ~override~
       ~iwdification/bam/cdia534b.bam~ ~override~
       ~iwdification/bam/cdia534c.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/itm/cditrn4.itm~  ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~

  COPY ~iwdification/2da/cdiaelmw.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// WIZARD_ANTIMAGIC_SHELL                           \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_ANTIMAGIC_SHELL~) OR override_arcane) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@3230) STR_VAR bam_file = cdia610d RET icon END

  ADD_SPELL ~iwdification/spl/cdia610.spl~ 2 6 WIZARD_ANTIMAGIC_SHELL
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3230 // name
    SAY 0x50 @3231 // descript
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 35499 parameter1 = string_dispel END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 93 parameter2 = icon END
    END ELSE BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 93 parameter2 = 83 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia610.itm~
    SAY 0x0c @3230
    SAY 0x54 @3231
    LPF cd_scroll INT_VAR unusable1 = BIT5 target_hdr = 5 range = 1 target_eff = 1 price = 600 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia610a.bam~ ~override~
       ~iwdification/bam/cdia610b.bam~ ~override~
       ~iwdification/bam/cdia610c.bam~ ~override~
       ~iwdification/bam/cdia610d.bam~ ~override~
       ~iwdification/bam/cdishelc.bam~ ~override~
       ~iwdification/vvc/cdiamags.vvc~ ~override~
       ~iwdification/wav/cdiafm04.wav~ ~override~
       ~iwdification/wav/cdiee01.wav~  ~override~

END

/////                                                  \\\\\
///// WIZARD_LICH_TOUCH                                \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_LICH_TOUCH~) OR override_arcane) BEGIN

  ADD_SPELL ~iwdification/spl/cdia626.spl~ 2 6 WIZARD_LICH_TOUCH
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3240 // name
    SAY 0x50 @3241 // descript

  COPY ~iwdification/itm/blank.itm~ ~override/cdia626.itm~
    SAY 0x0c @3240
    SAY 0x54 @3241
    LPF cd_scroll INT_VAR unusable1 = BIT2 target_hdr = 5 range = 1 target_eff = 1 price= 1800 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/itm/cdiltou.itm~ ~override~
    SAY 0x08 @3240
    SAY 0x0c @3240
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35606 parameter1 = string_held END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35542 parameter1 = string_paralyzed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35484 parameter1 = string_panic END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 20568 parameter1 = string_mf_panic END
    PATCH_IF !ee_game BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixa626 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixa626 END // general = undead
    END

  COPY ~iwdification/spl/cdia626a.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 109 target = 2 parameter2 = 0 duration = 42 savingthrow = BIT2 STR_VAR                     END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 215 target = 2 parameter2 = 0 timing = 1    savingthrow = BIT2 STR_VAR resource = cdinecro END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 174 target = 2 parameter2 = 0 timing = 1    savingthrow = BIT2 STR_VAR resource = cdiem07  END

  COPY ~iwdification/bam/cdia626a.bam~ ~override~
       ~iwdification/bam/cdia626b.bam~ ~override~
       ~iwdification/bam/cdia626c.bam~ ~override~
       ~iwdification/bam/cdiltou.bam~  ~override~
       ~iwdification/bam/cdinecro.bam~ ~override~
       ~iwdification/vvc/cdinecro.vvc~ ~override~
       ~iwdification/wav/cdiee04.wav~  ~override~
       ~iwdification/wav/cdiem07.wav~  ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixa626.eff~
      WRITE_ASCII 0x30 ~cdia626a~ #8

  END

END

/////                                                  \\\\\
///// WIZARD_MONSTER_SUMMONING_4                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_MONSTER_SUMMONING_4~) OR override_arcane) BEGIN

  LAF cd_new_summon_table STR_VAR descript = "Monster_summoning_IV" 2da_file = cdimsum4 RET table END

  ADD_SPELL ~iwdification/spl/cdia627.spl~ 2 6 WIZARD_MONSTER_SUMMONING_4
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3250 // name
    SAY 0x50 @3251 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 probability1 = 33 dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum4 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 probability1 = 67 dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum4 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0                   dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum4 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia627.itm~
    SAY 0x0c @3250
    SAY 0x54 @3251
    LPF cd_scroll INT_VAR unusable1 = (BIT0 + BIT3) target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 1800 STR_VAR spell = EVAL ~%current_spell_res%~ END

  LAF cd_animation STR_VAR code = e320 END // 58144 MGH3 ghast_greater
  COPY ~iwdification/cre/cdi4ghst.cre~ ~override~
    WRITE_LONG 0x08 string_ghast
    WRITE_LONG 0x0c string_ghast
    WRITE_LONG 0x28 anim_ghast

//  LAF cd_animation STR_VAR code = 9000 END // 36864 MOGR ogre
  COPY ~iwdification/cre/cdi4ogre.cre~ ~override~
    WRITE_LONG 0x08 string_ogre
    WRITE_LONG 0x0c string_ogre

  COPY ~iwdification/2da/cdimsum4.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
      PATCH_IF !anim_yeti BEGIN
        REPLACE_TEXTUALLY ~^3[ %TAB%]+cdi4yeti[ %TAB%%LNL%%MNL%%WNL%]+~ ~~ // delete yeti line from msum table
      END
    END

  ACTION_IF anim_yeti BEGIN // yeti animation (e.g. ee or vanilla bg2 w/ infinity animations)

    LAF cd_animation STR_VAR code = e25d END // 57949 MYET tundra_yeti
    COPY ~iwdification/cre/cdi4yeti.cre~ ~override~
      SAY 0x08 @3252
      SAY 0x0c @3252

  END

  COPY ~iwdification/bam/cdia627a.bam~ ~override~
       ~iwdification/bam/cdia627b.bam~ ~override~
       ~iwdification/bam/cdia627c.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdimsm1x.bam~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~
       ~iwdification/vvc/cdimsm1x.vvc~ ~override~

END

/////                                                  \\\\\
///// WIZARD_OTILUKES_FREEZING_SPHERE                  \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_OTILUKES_FREEZING_SPHERE~) OR override_arcane) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi269.pro~

  ADD_SPELL ~iwdification/spl/cdia628.spl~ 2 6 WIZARD_OTILUKES_FREEZING_SPHERE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3260 // name
    SAY 0x50 @3261 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi269 END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia628.itm~
    SAY 0x0c @3260
    SAY 0x54 @3261
    LPF cd_scroll INT_VAR range = 40 price = 1800 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia628a.bam~ ~override~
       ~iwdification/bam/cdia628b.bam~ ~override~
       ~iwdification/bam/cdia628c.bam~ ~override~
       ~iwdification/bam/cdiofspt.bam~ ~override~

END

/////                                                  \\\\\
///// WIZARD_SHADES                                    \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SHADES~) OR override_arcane) BEGIN

  LAF cd_new_summon_table STR_VAR descript = "Shades" 2da_file = cdishade RET table END

  ADD_SPELL ~iwdification/spl/cdia629.spl~ 2 6 WIZARD_SHADES
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3270 // name
    SAY 0x50 @3271 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      READ_SHORT 0x68 abil_num
      LPF ALTER_EFFECT INT_VAR header = 0 match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdishade END
      FOR (index = 1 ; index < abil_num ; ++index) BEGIN
        LPF ALTER_EFFECT INT_VAR header = index match_opcode = 331 opcode = 127 parameter1 = (index + 12) parameter2 = 0 dicesize = 0 dicenumber = 0 STR_VAR resource = cdishade END
      END
      LPF CLONE_EFFECT INT_VAR match_opcode = 127 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia629.itm~
    SAY 0x0c @3270
    SAY 0x54 @3271
    LPF cd_scroll INT_VAR unusable1 = BIT4 target_hdr = 4 range = 50 opcode = 148 target_eff = 1 price = 1800 STR_VAR spell = EVAL ~%current_spell_res%~ END

  ACTION_IF ee_game BEGIN // use iwdee gaze for ee games

    ADD_PROJECTILE ~iwdification/pro/cdi281.pro~

    COMPILE ~iwdification/baf/cdiuhgaz.baf~

    COPY ~iwdification/spl/cdiumbr1.spl~ ~override~ // gaze staging
         ~iwdification/spl/cditrdie.spl~ ~override~ // ee troll death
    COPY ~iwdification/spl/cdiumbr2.spl~ ~override~ // actual gaze
      SAY 0xce @3273
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi281 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37604 parameter1 = string_confused END
  
  END ELSE BEGIN
  
    COPY_EXISTING ~umbhul01.bcs~ ~override/cdiuhgaz.bcs~ // use bg2 umber hulk scripting
      DECOMPILE_AND_PATCH BEGIN
        REPLACE_TEXTUALLY ~AreaCheck("AR1106")~ ~False()~
      END

  END

  LAF cd_animation STR_VAR code = e420 END // 58400 MGO3 goblin_elite_axe
  COPY ~iwdification/cre/cdis2gb2.cre~ ~override~
       ~iwdification/cre/cdis2gb3.cre~ ~override~
    SAY 0x08 @3162
    SAY 0x0c @3162

  LAF cd_animation STR_VAR code = e500 END // 58624 MLIZ lizard_man_elite
  COPY ~iwdification/cre/cdis2lz5.cre~ ~override~
       ~iwdification/cre/cdis2lz6.cre~ ~override~
       ~iwdification/cre/cdis2lz7.cre~ ~override~
    SAY 0x08 @3163
    SAY 0x0c @3163  

  LAF cd_animation STR_VAR code = e0b0 END // 57520 MTRO troll_blue - MTRO doubles with bg2 troll
  COPY ~iwdification/cre/cdis3tr7.cre~ ~override~
       ~iwdification/cre/cdis3tr8.cre~ ~override~
    WRITE_LONG  0x08 string_troll
    WRITE_LONG  0x0c string_troll
    WRITE_LONG  0x28 anim_btroll
    WRITE_ASCII 0x258 ~~ #8 // blank old die-revive troll script

  LAF cd_animation STR_VAR code = e0d0 END // 57552 MUMB umber_hulk_elder - MUMB doubles with bg2 umber hulk
  COPY ~iwdification/cre/cdis3um8.cre~ ~override~
       ~iwdification/cre/cdis3um9.cre~ ~override~
    SAY 0x08 @3272
    SAY 0x0c @3272
    WRITE_LONG 0x28 anim_uhulk

 COPY ~iwdification/itm/cdiumbhk.itm~ ~override~
      ~iwdification/itm/cdim1d7s.itm~ ~override~
    WRITE_LONG 0x08 string_attack
    WRITE_LONG 0x0c string_attack
  
  COPY ~iwdification/itm/cdir1hp2.itm~ ~override~
    LPF DELETE_EFFECT INT_VAR match_opcode = 206 END // old iwd vorpal protections
    LPF DELETE_EFFECT INT_VAR match_opcode = 267 END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 232 STR_VAR resource = cditrdie END
    END ELSE BEGIN
      PATCH_FOR_EACH op IN 232 208 BEGIN // nuke everything but regen
        LPF DELETE_EFFECT INT_VAR match_opcode = op END
      END
    END

  COPY ~iwdification/bam/cdia629a.bam~ ~override~
       ~iwdification/bam/cdia629b.bam~ ~override~
       ~iwdification/bam/cdia629c.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdimsm1x.bam~ ~override~
       ~iwdification/itm/cdisumam.itm~ ~override~
       ~iwdification/itm/cdisumrn.itm~ ~override~
       ~iwdification/itm/cditrn40.itm~ ~override~
       ~iwdification/itm/cditrn60.itm~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~
       ~iwdification/vvc/cdimsm1x.vvc~ ~override~

  COPY ~iwdification/2da/cdishade.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// WIZARD_DARTS_OF_BONE                             \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_DARTS_OF_BONE~) OR override_arcane) BEGIN

  ADD_SPELL ~iwdification/spl/cdia630.spl~ 2 6 WIZARD_DARTS_OF_BONE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3280 // name
    SAY 0x50 @3281 // descript

  COPY ~iwdification/itm/blank.itm~ ~override/cdia630.itm~
    SAY 0x0c @3280
    SAY 0x54 @3281
    LPF cd_scroll INT_VAR unusable1 = BIT2 target_hdr = 5 range = 1 target_eff = 1 price = 600 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/itm/cdidbone.itm~ ~override~
    SAY 0x08 @3280
    SAY 0x0c @3282

  COPY ~iwdification/bam/cdia630a.bam~ ~override~
       ~iwdification/bam/cdia630b.bam~ ~override~
       ~iwdification/bam/cdia630c.bam~ ~override~
       ~iwdification/bam/cdidbone.bam~ ~override~
       ~iwdification/vvc/cdinecro.vvc~ ~override~
       ~iwdification/bam/cdinecro.bam~ ~override~
       ~iwdification/wav/cdiem07.wav~  ~override~

END

/////                                                  \\\\\
///// WIZARD_SOUL_EATER                                \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SOUL_EATER~) OR override_arcane)) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi299.pro~

  ADD_SPELL ~iwdification/spl/cdia631.spl~ 2 6 WIZARD_SOUL_EATER
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3290 // name
    SAY 0x50 @3291 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi299 END
    LPF ALTER_EFFECT STR_VAR match_resource = cdia631 resource = EVAL ~%DEST_RES%~ END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia631.itm~
    SAY 0x0c @3290
    SAY 0x54 @3291
    LPF cd_scroll INT_VAR unusable1 = BIT2 target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 1800 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COMPILE ~iwdification/baf/cdi3sklm.baf~

  LAF cd_animation STR_VAR code = 6403 END // 25603 MSKL skeleton
  COPY ~iwdification/cre/cdi3sklm.cre~ ~override~
    WRITE_LONG  0x08 string_skelly
    WRITE_LONG  0x0c string_skelly
    WRITE_ASCII 0x248 ~cdi3sklm~ #8

  COPY ~iwdification/bam/cdia631a.bam~ ~override~
       ~iwdification/bam/cdia631b.bam~ ~override~
       ~iwdification/bam/cdia631c.bam~ ~override~
       ~iwdification/bam/cdiseata.bam~ ~override~
       ~iwdification/bam/cdiseath.bam~ ~override~
       ~iwdification/spl/cdi3sklm.spl~ ~override~
       ~iwdification/spl/cdia631b.spl~ ~override~
       ~iwdification/vvc/cdiseata.vvc~ ~override~
       ~iwdification/vvc/cdiseath.vvc~ ~override~
       ~iwdification/wav/cdiarm18.wav~ ~override~
       ~iwdification/wav/cdiem104.wav~ ~override~

END

/////                                                  \\\\\
///// WIZARD_TROLLISH_FORTITUDE                        \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_TROLLISH_FORTITUDE~) OR override_arcane) BEGIN

  ADD_SPELL ~iwdification/spl/cdia632.spl~ 2 6 WIZARD_TROLLISH_FORTITUDE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3300 // name
    SAY 0x50 @3301 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdia632 resource = EVAL ~%DEST_RES%~ END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 142 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = EVAL ~%DEST_RES%~ END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia632.itm~
    SAY 0x0c @3300
    SAY 0x54 @3301
    LPF cd_scroll INT_VAR unusable1 = BIT2 target_hdr = 5 range = 1 target_eff = 1 price = 600 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia632a.bam~ ~override~
       ~iwdification/bam/cdia632b.bam~ ~override~
       ~iwdification/bam/cdia632c.bam~ ~override~
       ~iwdification/eff/cditroll.eff~ ~override~

END

/////                                                  \\\\\
///// WIZARD_MONSTER_SUMMONING_5                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_MONSTER_SUMMONING_5~) OR override_arcane) BEGIN

  LAF cd_new_summon_table STR_VAR descript = "Monster_summoning_V" 2da_file = cdimsum5 RET table END

  ADD_SPELL ~iwdification/spl/cdia706.spl~ 2 7 WIZARD_MONSTER_SUMMONING_5
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3310 // name
    SAY 0x50 @3311 // descript    
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 probability1 = 33 dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum5 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 probability1 = 67 dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum5 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0                   dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum5 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia706.itm~
    SAY 0x0c @3310
    SAY 0x54 @3311
    LPF cd_scroll INT_VAR unusable1 = (BIT0 + BIT3) target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 2100 STR_VAR spell = EVAL ~%current_spell_res%~ END

//  LAF cd_animation STR_VAR code = 7a00 END // 31232 MSPI_GI spider_giant
  COPY ~iwdification/cre/cdi5gspi.cre~ ~override~
    WRITE_LONG  0x08 string_gspider
    WRITE_LONG  0x0c string_gspider

  LAF cd_animation STR_VAR code = ee00 END // 60928 MZO2 zombie_yellow
  COPY ~iwdification/cre/cdi5jzom.cre~ ~override~
    SAY  0x08 @3312
    SAY  0x0c @3312
    WRITE_LONG 0x28 anim_jzombie

  LAF cd_animation STR_VAR code = e070 END // 57456 MMIN minotaur - MMIN doubles with bg2 mindflayer
  COPY ~iwdification/cre/cdi5mino.cre~ ~override~
    SAY  0x08 @3313
    SAY  0x0c @3313

  COPY ~iwdification/itm/cdis18ml.itm~ ~override~
    WRITE_LONG  0x08 string_attack
    WRITE_LONG  0x0c string_attack

  COPY ~iwdification/bam/cdia706a.bam~ ~override~
       ~iwdification/bam/cdia706b.bam~ ~override~
       ~iwdification/bam/cdia706c.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdimsm1x.bam~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~
       ~iwdification/vvc/cdimsm1x.vvc~ ~override~

  COPY ~iwdification/2da/cdimsum5.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// WIZARD_MALAVONS_RAGE                             \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_MALAVONS_RAGE~) OR override_arcane) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi209.pro~

  ADD_SPELL ~iwdification/spl/cdia709.spl~ 2 7 WIZARD_MALAVONS_RAGE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3320 // name
    SAY 0x50 @3321 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi209 END
    PATCH_IF !ee_game BEGIN
      LPF CD_SPLIT_SAVE_DAMAGE END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia709.itm~
    SAY 0x0c @3320
    SAY 0x54 @3321
    LPF cd_scroll INT_VAR unusable1 = BIT1 target_hdr = 5 range = 50 price = 2100 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia709a.bam~ ~override~
       ~iwdification/bam/cdia709b.bam~ ~override~
       ~iwdification/bam/cdia709c.bam~ ~override~
       ~iwdification/bam/cdimagrx.bam~ ~override~
       ~iwdification/bam/cdimrage.bam~ ~override~
       ~iwdification/vvc/cdimalrg.vvc~ ~override~
       ~iwdification/vvc/cdimrage.vvc~ ~override~

END

/////                                                  \\\\\
///// WIZARD_ACID_STORM                                \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_ACID_STORM~) OR override_arcane) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi211.pro~
    
  END ELSE BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi211a.pro~

  END

  ADD_SPELL ~iwdification/spl/cdia724.spl~ 2 7 WIZARD_ACID_STORM
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3330 // name
    SAY 0x50 @3331 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi211 END
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi211a END
      LPF ALTER_EFFECT INT_VAR match_opcode = 12 match_dicesize = 4 dicesize = 2 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 12 match_dicesize = 6 dicesize = 3 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 12 match_dicesize = 8 dicesize = 4 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 12 savingthrow = BIT24 END
      PATCH_FOR_EACH res IN 0 1 2 3 4 5 6 7 8 9 x y z BEGIN // simulating clouds in bg2 sucks
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 215 target = 1 parameter2 = 2 resist_dispel = 3 STR_VAR resource = EVAL ~cdia724%res%~ END
      END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia724.itm~
    SAY 0x0c @3330
    SAY 0x54 @3331
    LPF cd_scroll INT_VAR unusable1 = BIT1 target_hdr = 4 range = 40 opcode = 148 target_eff = 1 price = 2100 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia724a.bam~ ~override~
       ~iwdification/bam/cdia724b.bam~ ~override~
       ~iwdification/bam/cdia724c.bam~ ~override~
       ~iwdification/bam/cdiastra.bam~ ~override~
       ~iwdification/bam/cdiastrx.bam~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/vvc/cdia7240.vvc~ ~override~
         ~iwdification/vvc/cdia7241.vvc~ ~override~
         ~iwdification/vvc/cdia7242.vvc~ ~override~
         ~iwdification/vvc/cdia7243.vvc~ ~override~
         ~iwdification/vvc/cdia7244.vvc~ ~override~
         ~iwdification/vvc/cdia7245.vvc~ ~override~
         ~iwdification/vvc/cdia7246.vvc~ ~override~
         ~iwdification/vvc/cdia7247.vvc~ ~override~
         ~iwdification/vvc/cdia7248.vvc~ ~override~
         ~iwdification/vvc/cdia7249.vvc~ ~override~
         ~iwdification/vvc/cdia724x.vvc~ ~override~
         ~iwdification/vvc/cdia724y.vvc~ ~override~
         ~iwdification/vvc/cdia724z.vvc~ ~override~

  END

END

/////                                                  \\\\\
///// WIZARD_SEVEN_EYES                                \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SHOUT~)) AND // eye of fortitude requires shout, no vanilla
          (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SEVEN_EYES~) OR override_arcane)) BEGIN

  ADD_SPELL ~iwdification/spl/cdia725.spl~ 2 7 WIZARD_SEVEN_EYES
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3340 // name
    SAY 0x50 @3341 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdia725 resource = EVAL ~%DEST_RES%~ END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia725.itm~
    SAY 0x0c @3340
    SAY 0x54 @3341
    LPF cd_scroll INT_VAR unusable1 = BIT5 target_hdr = 5 range = 1 target_eff = 1 price = 700 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/spl/cdia725t.spl~ ~override~
    SAY 0x08 @3342 // name
    SAY 0x50 @3343 // descript

  COPY ~iwdification/spl/cdia725u.spl~ ~override~
    SAY 0x08 @3344 // name
    SAY 0x50 @3345 // descript

  COPY ~iwdification/spl/cdia725v.spl~ ~override~
    SAY 0x08 @3346 // name
    SAY 0x50 @3347 // descript

  COPY ~iwdification/spl/cdia725w.spl~ ~override~
    SAY 0x08 @3348 // name
    SAY 0x50 @3349 // descript

  COPY ~iwdification/spl/cdia725x.spl~ ~override~
    SAY 0x08 @3350 // name
    SAY 0x50 @3351 // descript

  COPY ~iwdification/spl/cdia725y.spl~ ~override~
    SAY 0x08 @3352 // name
    SAY 0x50 @3353 // descript

  COPY ~iwdification/spl/cdia725z.spl~ ~override~
    SAY 0x08 @3354 // name
    SAY 0x50 @3355 // descript

  COPY ~iwdification/2da/7eyes.2da~    ~override~
    REPLACE ~21648~ @3356
    REPLACE ~21649~ @3357
    REPLACE ~21650~ @3358
    REPLACE ~21651~ @3359
    REPLACE ~21652~ @3360
    REPLACE ~21653~ @3361
    REPLACE ~21654~ @3362

  COPY ~iwdification/bam/cdia725a.bam~ ~override~
       ~iwdification/bam/cdia725b.bam~ ~override~
       ~iwdification/bam/cdia725c.bam~ ~override~
       ~iwdification/bam/cdi7eyc1.bam~ ~override~
       ~iwdification/bam/cdi7eyc2.bam~ ~override~
       ~iwdification/bam/cdia725t.bam~ ~override~
       ~iwdification/bam/cdia725u.bam~ ~override~
       ~iwdification/bam/cdia725v.bam~ ~override~
       ~iwdification/bam/cdia725w.bam~ ~override~
       ~iwdification/bam/cdia725x.bam~ ~override~
       ~iwdification/bam/cdia725y.bam~ ~override~
       ~iwdification/bam/cdia725z.bam~ ~override~
       ~iwdification/vvc/cdi7ey.vvc~   ~override~
       ~iwdification/vvc/cdi7ey1a.vvc~ ~override~
       ~iwdification/vvc/cdi7ey1b.vvc~ ~override~
       ~iwdification/vvc/cdi7ey1c.vvc~ ~override~
       ~iwdification/vvc/cdi7ey1d.vvc~ ~override~
       ~iwdification/vvc/cdi7ey1e.vvc~ ~override~
       ~iwdification/vvc/cdi7ey1f.vvc~ ~override~
       ~iwdification/vvc/cdi7ey1g.vvc~ ~override~
       ~iwdification/vvc/cdi7ey2a.vvc~ ~override~
       ~iwdification/vvc/cdi7ey2b.vvc~ ~override~
       ~iwdification/vvc/cdi7ey2c.vvc~ ~override~
       ~iwdification/vvc/cdi7ey2d.vvc~ ~override~
       ~iwdification/vvc/cdi7ey2e.vvc~ ~override~
       ~iwdification/vvc/cdi7ey2f.vvc~ ~override~
       ~iwdification/vvc/cdi7ey2g.vvc~ ~override~
       ~iwdification/wav/cdiafm13.wav~ ~override~
       ~iwdification/wav/cdiafm15.wav~ ~override~
       ~iwdification/wav/cdiafm16.wav~ ~override~
       ~iwdification/wav/cdiafm17.wav~ ~override~

END

/////                                                  \\\\\
///// WIZARD_SUFFOCATE                                 \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_SUFFOCATE~) OR override_arcane) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi317.pro~
  
  END ELSE BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi317a.pro~

  END

  ADD_SPELL ~iwdification/spl/cdia726.spl~ 2 7 WIZARD_SUFFOCATE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3370 // name
    SAY 0x50 @3371 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi317 END
      LPF ALTER_EFFECT STR_VAR match_resource = cdia726 resource = EVAL ~%DEST_RES%~ END
    END ELSE BEGIN
      LPF DELETE_EFFECT END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 timing = 1 parameter2 = 2 STR_VAR resource = cdia726 END
      LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia726.itm~
    SAY 0x0c @3370
    SAY 0x54 @3371
    LPF cd_scroll INT_VAR unusable2 = BIT6 target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 2100 STR_VAR spell = EVAL ~%current_spell_res%~ END


  COPY ~iwdification/bam/cdia726a.bam~ ~override~
       ~iwdification/bam/cdia726b.bam~ ~override~
       ~iwdification/bam/cdia726c.bam~ ~override~
       ~iwdification/bam/cdisuffo.bam~ ~override~

  ACTION_IF ee_game BEGIN
  
    APPEND ~clearair.2da~ ~Suffocate %cdi317%~

    COPY ~iwdification/vvc/cdisuffo.vvc~ ~override~
         ~iwdification/wav/cdiafm18.wav~ ~override~

  END ELSE BEGIN
  
    APPEND ~clearair.2da~ ~Suffocate %cdi317a%~

    LAUNCH_ACTION_FUNCTION cd_create_cloud INT_VAR visloop = 5 cloud_dur = 60 zosa = 1 STR_VAR code = CDIA726 anim = cdisuffo END

    COPY ~iwdification/spl/cdia726.spl~ ~override~
      WRITE_LONG 0x08 "-1" // name
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi317a END
      LPF CLONE_EFFECT INT_VAR match_opcode = 321 opcode = 206 duration = 6 STR_VAR insert = last END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  9 opcode = 177 parameter1 = 145 parameter2 = 4 STR_VAR resource = cdixa726 END // race = elemental
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 27 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixa726 END // race = golem
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 31 opcode = 177 parameter1 = 121 parameter2 = 4 STR_VAR resource = cdixa726 END // race = demonic
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 31 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixa726 END // general = undead
      LPF CD_SPLIT_SAVE_DAMAGE END

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixa726.eff~
      WRITE_ASCII 0x30 ~cdia726~ #8

  END

END

/////                                                  \\\\\
///// WIZARD_MONSTER_SUMMONING_6                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_MONSTER_SUMMONING_6~) OR override_arcane) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdisalau.pro~

  LAF cd_new_summon_table STR_VAR descript = "Monster_summoning_VI" 2da_file = cdimsum6 RET table END

  ADD_SPELL ~iwdification/spl/cdia801.spl~ 2 8 WIZARD_MONSTER_SUMMONING_6
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3380 // name
    SAY 0x50 @3381 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 probability1 = 33 dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum6 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 probability1 = 67 dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum6 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0                   dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum6 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia801.itm~
    SAY 0x0c @3380
    SAY 0x54 @3381
    LPF cd_scroll INT_VAR unusable1 = (BIT0 + BIT3) target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 2400 STR_VAR spell = EVAL ~%current_spell_res%~ END
    
  COMPILE ~iwdification/baf/cdisalfi.baf~
          ~iwdification/baf/cdisalfr.baf~
          ~iwdification/baf/cdipspid.baf~

//  LAF cd_animation STR_VAR code = a100 END // 41216 MCAR carrion_crawler
  COPY ~iwdification/cre/cdi6crwl.cre~ ~override~
    WRITE_LONG  0x08 string_crawler
    WRITE_LONG  0x0c string_crawler

//  LAF cd_animation STR_VAR code = 7a02 END // 31234 MSPI_PH spider_phase
  COPY ~iwdification/cre/cdi6pspi.cre~ ~override~
    WRITE_LONG  0x08 string_pspider
    WRITE_LONG  0x0c string_pspider

  LAF cd_animation STR_VAR code = e910 END // 59664 MSA2 salamander_frost
  COPY ~iwdification/cre/cdi6salc.cre~ ~override~
    SAY  0x08 @3383
    SAY  0x0c @3383

  LAF cd_animation STR_VAR code = e900 END // 59648 MSAL salamander_fire
  COPY ~iwdification/cre/cdi6salf.cre~ ~override~
    SAY  0x08 @3382
    SAY  0x0c @3382

  COPY ~iwdification/itm/cdisalfi.itm~ ~override~
       ~iwdification/itm/cdisalfr.itm~ ~override~
    WRITE_LONG  0x08 string_attack
    WRITE_LONG  0x0c string_attack
    WRITE_ASCII 0x3a ~isper01~ #8
    WRITE_ASCII 0x76 ~isper01~ #8
    LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 215 target = 1 parameter2 = 1 timing = 2 duration = 0 STR_VAR resource = EVAL ~%SOURCE_RES%~ END

  COPY ~iwdification/spl/cdifire6.spl~ ~override~
       ~iwdification/spl/cdifros6.spl~ ~override~
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdisalau END
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 318 END
    END

  COPY ~iwdification/spl/cdisalfi.spl~ ~override~
       ~iwdification/spl/cdisalfr.spl~ ~override~
    PATCH_IF !ee_game BEGIN // change from EE's 232 distance check to straight once-per-round spam; needs effs copied below
      LPF ALTER_EFFECT INT_VAR match_opcode = 232 opcode = 272 target = 1 parameter1 = 6 parameter2 = 3 END
    END

  COPY ~iwdification/bam/cdia801a.bam~ ~override~
       ~iwdification/bam/cdia801b.bam~ ~override~
       ~iwdification/bam/cdia801c.bam~ ~override~
       ~iwdification/bam/cdidoorh.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdimsm1x.bam~ ~override~
       ~iwdification/bam/cdisalfi.bam~ ~override~
       ~iwdification/bam/cdisalfr.bam~ ~override~
       ~iwdification/spl/cdiphase.spl~ ~override~
       ~iwdification/vvc/cdidoorh.vvc~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~
       ~iwdification/vvc/cdimsm1x.vvc~ ~override~
       ~iwdification/vvc/cdisalfi.vvc~ ~override~
       ~iwdification/vvc/cdisalfr.vvc~ ~override~

  COPY ~iwdification/2da/cdimsum6.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/spl/cdifire6.spl~ ~override/cdifire0.spl~
         ~iwdification/spl/cdifros6.spl~ ~override/cdifros0.spl~
      WRITE_BYTE 0x7e 1
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdisalau END
      LPF DELETE_EFFECT END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%SOURCE_RES%~ END

    COPY ~iwdification/eff/cdifire6.eff~ ~override/cdifire6.eff~
         ~iwdification/eff/cdifire6.eff~ ~override/cdifros6.eff~
      WRITE_ASCIIE 0x30 ~%DEST_RES%~ #8
      WRITE_ASCII  0x37 ~0~ #1

    COPY_EXISTING ~cdisalfi.itm~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 STR_VAR resource = cdifire6 END

    COPY_EXISTING ~cdisalfr.itm~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 STR_VAR resource = cdifros6 END

  END

END

/////                                                  \\\\\
///// WIZARD_MIND_BLANK                                \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_MIND_BLANK~) OR override_arcane) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@3390) STR_VAR bam_file = cdia802d RET icon END

  ADD_SPELL ~iwdification/spl/cdia802.spl~ 2 8 WIZARD_MIND_BLANK
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3390 // name
    SAY 0x50 @3391 // descript
//    LPF ALTER_EFFECT STR_VAR match_resource = confush resource = cdiconfh END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14102 parameter1 = string_held END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 17392 parameter1 = string_dcharmed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 20568 parameter1 = string_mf_panic END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35484 parameter1 = string_panic END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35542 parameter1 = string_paralyzed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35544 parameter1 = string_dominated END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35606 parameter1 = string_held END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37603 parameter1 = string_rthinking END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37604 parameter1 = string_confused END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37605 parameter1 = string_berserk END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37606 parameter1 = string_intoxicated END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37801 parameter1 = string_charmed END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 166 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 166 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia802.itm~
    SAY 0x0c @3390
    SAY 0x54 @3391
    LPF cd_scroll INT_VAR unusable1 = BIT5 target_hdr = 5 range = 1 target_eff = 1 price = 800 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia802a.bam~ ~override~
       ~iwdification/bam/cdia802b.bam~ ~override~
       ~iwdification/bam/cdia802c.bam~ ~override~
       ~iwdification/bam/cdia802d.bam~ ~override~
       ~iwdification/bam/cdiabjur.bam~ ~override~
       ~iwdification/vvc/cdiabjur.vvc~ ~override~
       ~iwdification/wav/cdiem02.wav~  ~override~

END

/////                                                  \\\\\
///// WIZARD_GREAT_SHOUT                               \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_GREAT_SHOUT~) OR override_arcane)) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi319.pro~

  ADD_SPELL ~iwdification/spl/cdia806.spl~ 2 8 WIZARD_GREAT_SHOUT
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3400 // name
    SAY 0x50 @3401 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi319 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37340 parameter1 = string_uncon END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 35568 parameter1 = string_stunned END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14073 parameter1 = string_deafness END
    PATCH_IF !ee_game BEGIN
      LPF CD_SPLIT_SAVE_DAMAGE END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia806.itm~
    SAY 0x0c @3400
    SAY 0x54 @3401
    LPF cd_scroll INT_VAR unusable1 = BIT1 target_hdr = 4 range = 22 opcode = 148 target_eff = 1 price = 2400 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdia806a.bam~ ~override~
       ~iwdification/bam/cdia806b.bam~ ~override~
       ~iwdification/bam/cdia806c.bam~ ~override~
       ~iwdification/bam/cdigshou.bam~ ~override~
       ~iwdification/wav/cdiem101.wav~ ~override~
       ~iwdification/wav/cditra08.wav~ ~override~

END

/////                                                  \\\\\
///// WIZARD_IRON_BODY                                 \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_IRON_BODY~) OR override_arcane) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@3410) STR_VAR bam_file = cdia814d RET icon END

  ADD_SPELL ~iwdification/spl/cdia814.spl~ 2 8 WIZARD_IRON_BODY
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3410 // name
    SAY 0x50 @3411 // descript
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37607 parameter1 = string_poisoned END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 36317 parameter1 = string_poison END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35593 parameter1 = string_diseased END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 39752 parameter1 = string_stricken END
    LPF CLONE_EFFECT INT_VAR match_opcode = 206 STR_VAR match_resource = spwi502 resource = spin673 END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdia814 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 172 parameter2 = icon END
      LPF CLONE_EFFECT INT_VAR match_opcode = 206 opcode = 318 parameter2 = 0 STR_VAR match_resource = spwi502 resource = wand13 END
    END ELSE BEGIN // move spell effects to 'paw'
      READ_LONG 0x6a fx_off
      SET fx_num = ((SOURCE_SIZE - fx_off) / 0x30)
      READ_ASCII fx_off fx (fx_num * 0x30)
      LPF DELETE_EFFECT END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 111 target = 1 power = 8 duration = 120 STR_VAR resource = cdiibody END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 174 target = 1 power = 8 timing = 1     STR_VAR resource = cdiem102 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia814.itm~
    SAY 0x0c @3410
    SAY 0x54 @3411
    LPF cd_scroll INT_VAR unusable2 = BIT6 target_hdr = 5 range = 1 target_eff = 1 price = 800 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/itm/cdiibody.itm~ ~override~
    SAY 0x08 @3412
    SAY 0x0c @3412
    PATCH_IF !ee_game BEGIN // move spell effects to 'paw'
      READ_LONG   0x64 abil_off ELSE 0
      READ_SHORT  0x68 abil_num ELSE 0
      READ_LONG   0x6a fx_off
      WRITE_SHORT 0x70 (THIS + fx_num)
      FOR (index = 0 ; index < abil_num ; ++index) BEGIN // start iterating through abilities
        WRITE_SHORT  (abil_off + 0x20 + (0x28 * index)) (THIS + fx_num)
      END
      INSERT_BYTES fx_off (fx_num * 0x30)
      WRITE_ASCIIE fx_off ~%fx%~
      PATCH_FOR_EACH op IN 321 111 174 BEGIN
        LPF DELETE_EFFECT INT_VAR match_opcode = op END
      END
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 172 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 1 multi_match = 1 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 318 opcode = 206 parameter1 = 0 END
      LPF ALTER_EFFECT INT_VAR timing = 2 END
    END

  COPY ~iwdification/bam/cdia814a.bam~ ~override~
       ~iwdification/bam/cdia814b.bam~ ~override~
       ~iwdification/bam/cdia814c.bam~ ~override~
       ~iwdification/bam/cdia814d.bam~ ~override~
       ~iwdification/bam/cdiibody.bam~ ~override~
       ~iwdification/wav/cdiem102.wav~ ~override~

END

/////                                                  \\\\\
///// WIZARD_MONSTER_SUMMONING_7                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_MONSTER_SUMMONING_7~) OR override_arcane) BEGIN

  LAF cd_new_summon_table STR_VAR descript = "Monster_summoning_VII" 2da_file = cdimsum7 RET table END

  ADD_SPELL ~iwdification/spl/cdia901.spl~ 2 9 WIZARD_MONSTER_SUMMONING_7
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @3420 // name
    SAY 0x50 @3421 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 probability1 = 49 dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum7 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0                   dicesize = 0 dicenumber = 0 STR_VAR resource = cdimsum7 END
    END

  COPY ~iwdification/itm/blank.itm~ ~override/cdia901.itm~
    SAY 0x0c @3420
    SAY 0x54 @3421
    LPF cd_scroll INT_VAR unusable1 = (BIT0 + BIT3) target_hdr = 4 range = 20 opcode = 148 target_eff = 1 price = 2700 STR_VAR spell = EVAL ~%current_spell_res%~ END

  ACTION_IF ee_game BEGIN // use iwdee gaze for ee games

    ADD_PROJECTILE ~iwdification/pro/cdi281.pro~

    COMPILE ~iwdification/baf/cdiuhgaz.baf~

    COPY ~iwdification/spl/cdiumbr1.spl~ ~override~ // gaze staging
    COPY ~iwdification/spl/cdiumbr2.spl~ ~override~ // actual gaze
      SAY 0xce @3273
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi281 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37604 parameter1 = string_confused END
  
  END ELSE BEGIN
  
    COPY_EXISTING ~umbhul01.bcs~ ~override/cdiuhgaz.bcs~ // use bg2 umber hulk scripting
      DECOMPILE_AND_PATCH BEGIN
        REPLACE_TEXTUALLY ~AreaCheck("AR1106")~ ~False()~
      END

  END

  LAF cd_animation STR_VAR code = eb20 END // 60192 MSKB skeleton_fiend
  COPY ~iwdification/cre/cdi7bgrd.cre~ ~override~
    SAY  0x08 @3422
    SAY  0x0c @3422

  LAF cd_animation STR_VAR code = e0d0 END // 57552 MUMB umber_hulk_elder - MUMB doubles with bg2 umber hulk
  COPY ~iwdification/cre/cdi7umbh.cre~ ~override~
    SAY  0x08 @3272
    SAY  0x0c @3272
    WRITE_LONG 0x28 anim_uhulk

 COPY ~iwdification/itm/cdiumbhk.itm~ ~override~
    WRITE_LONG 0x08 string_attack
    WRITE_LONG 0x0c string_attack

  COPY ~iwdification/bam/cdia901a.bam~ ~override~
       ~iwdification/bam/cdia901b.bam~ ~override~
       ~iwdification/bam/cdia901c.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdimsm1x.bam~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~
       ~iwdification/vvc/cdimsm1x.vvc~ ~override~

  COPY ~iwdification/2da/cdimsum7.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// arcane spell crosspatching                       \\\\\
/////                                                  \\\\\

OUTER_SET NUM_a411 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_EMOTION_HOPELESSNESS~)) - 2000)
OUTER_SET NUM_a422 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_BELTYNS_BURNING_BLOOD~)) - 2000)
OUTER_SET NUM_a427 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_EMOTION_COURAGE~)) - 2000)
OUTER_SET NUM_a428 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_EMOTION_FEAR~)) - 2000)
OUTER_SET NUM_a429 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_EMOTION_HOPE~)) - 2000)
OUTER_SET NUM_a431 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_SHOUT~)) - 2000)
OUTER_SET NUM_a432 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_VITRIOLIC_SPHERE~)) - 2000)
OUTER_SET NUM_a524 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_SHROUD_OF_FLAME~)) - 2000)
OUTER_SET NUM_a610 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_ANTIMAGIC_SHELL~)) - 2000)
OUTER_SET NUM_a631 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_SOUL_EATER~)) - 2000)
OUTER_SET NUM_a724 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_ACID_STORM~)) - 2000)
OUTER_SET NUM_a726 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_SUFFOCATE~)) - 2000)
OUTER_SET NUM_a814 = ((IDS_OF_SYMBOL (~spell~ ~WIZARD_IRON_BODY~)) - 2000)

ACTION_IF ((NUM_a411 > 0) AND (NUM_a429 > 0)) BEGIN

  COPY_EXISTING ~spwi%NUM_a411%.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia429 resource = EVAL ~spwi%NUM_a429%~ END
    BUT_ONLY

  COPY_EXISTING ~spwi%NUM_a429%.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia411 resource = EVAL ~spwi%NUM_a411%~ END
    BUT_ONLY

END

ACTION_IF ((NUM_a427 > 0) AND (NUM_a428 > 0)) BEGIN

  COPY_EXISTING ~spwi%NUM_a427%.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia428 resource = EVAL ~spwi%NUM_a428%~ END
    BUT_ONLY

  COPY_EXISTING ~spwi%NUM_a428%.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia427 resource = EVAL ~spwi%NUM_a427%~ END
    BUT_ONLY

END

ACTION_IF NUM_a610 > 0 BEGIN

  COPY_EXISTING ~spwi%NUM_a610%.spl~ ~override~
    PATCH_IF NUM_a726 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia726 resource = EVAL ~spwi%NUM_a726%~ END
    END
    PATCH_IF NUM_a724 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia724 resource = EVAL ~spwi%NUM_a724%~ END
    END
    PATCH_IF NUM_a631 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia631 resource = EVAL ~spwi%NUM_a631%~ END
    END
    PATCH_IF NUM_a524 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia524 resource = EVAL ~spwi%NUM_a524%~ END
    END
    PATCH_IF NUM_a432 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia432 resource = EVAL ~spwi%NUM_a432%~ END
    END
    BUT_ONLY

END

ACTION_IF NUM_a431 > 0 BEGIN

  COPY_EXISTING ~cdia725y.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia431 resource = EVAL ~spwi%NUM_a431%~ END
    BUT_ONLY IF_EXISTS

END

ACTION_IF NUM_a814 > 0 BEGIN

  COPY_EXISTING ~spwi%NUM_a814%.spl~ ~override~
    PATCH_IF NUM_a726 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia726 resource = EVAL ~spwi%NUM_a726%~ END
    END
    PATCH_IF NUM_a422 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdia724 resource = EVAL ~spwi%NUM_a422%~ END
    END
    BUT_ONLY

END

ACTION_IF !ee_game BEGIN

  COPY_EXISTING ~cdidbone.bam~ ~override~
                ~cdideca.bam~  ~override~
                ~cdiibody.bam~ ~override~
                ~cdiltou.bam~  ~override~
                ~cdiplybb.bam~ ~override~
                ~cdiplypb.bam~ ~override~
                ~cdiplyww.bam~ ~override~
                ~cdismcud.bam~ ~override~
    READ_LONG 0x0c frame_off
    WRITE_LONG frame_off + 0x04 0
    IF_EXISTS

END

/////                                                  \\\\\
///// arcane-divine cross-patching                     \\\\\
/////                                                  \\\\\

ACTION_IF MOD_IS_INSTALLED ~IWDIFICATION/SETUP-IWDIFICATION.TP2~ ~40~ THEN BEGIN

  INCLUDE ~iwdification/lib/cross_patch_both.tpa~

END

/////                                                  \\\\\
///// add scrolls to stores                            \\\\\
/////                                                  \\\\\

COPY_EXISTING_REGEXP GLOB ~^[_h]ighhedg\.sto$~ ~override~  // adds lev 1, 2 scrolls to High Hedge
                          ~^_?sto0703\.sto$~   ~override~  // adds lev 1, 2 scrolls to Sorcerous Sundries
                          ~^bdsorcsc\.sto$~    ~override~  // adds lev 1, 2 scrolls to SoD Sorcerous Sundries
                          ~^bdbeleg3\.sto$~    ~override~  // adds lev 1, 2 scrolls to SoD Quartermaster
                          ~^bpding01\.sto$~    ~override~  // adds lev 1, 2 scrolls to Dinguer the Mad (Black Pits)
  PATCH_IF FILE_EXISTS_IN_GAME cdia126.itm BEGIN ADD_STORE_ITEM ~cdia126~ AFTER ~scrl84 _scrl84~ #1 #0 #0 ~IDENTIFIED~ #2 END // expeditious retreat
  PATCH_IF FILE_EXISTS_IN_GAME cdia204.itm BEGIN ADD_STORE_ITEM ~cdia204~ AFTER ~scrl89 _scrl89~ #1 #0 #0 ~IDENTIFIED~ #2 END // Snilloc's Snowball Swarm
  PATCH_IF FILE_EXISTS_IN_GAME cdia216.itm BEGIN ADD_STORE_ITEM ~cdia216~ AFTER ~scrl89 _scrl89~ #1 #0 #0 ~IDENTIFIED~ #2 END // decastave
  PATCH_IF FILE_EXISTS_IN_GAME cdia225.itm BEGIN ADD_STORE_ITEM ~cdia225~ AFTER ~scrl89 _scrl89~ #1 #0 #0 ~IDENTIFIED~ #2 END // cats grace
  BUT_ONLY IF_EXISTS

COPY_EXISTING_REGEXP GLOB ~^_?sto0703\.sto$~ ~override~  // adds lev 3, 4, 5 scrolls to Sorcerous Sundries
                          ~^bdsorcsc\.sto$~  ~override~  // adds lev 3, 4, 5 scrolls to SoD Sorcerous Sundries
                          ~^bdbeleg3\.sto$~  ~override~  // adds lev 3, 4, 5 scrolls to SoD Quartermaster
                          ~^bpding01\.sto$~  ~override~  // adds lev 3, 4, 5 scrolls to Dinguer the Mad (Black Pits)
  PATCH_IF FILE_EXISTS_IN_GAME cdia327.itm BEGIN ADD_STORE_ITEM ~cdia327~ AFTER ~scrl1k _scrl1k~ #1 #0 #0 ~IDENTIFIED~ #2 END // Icelance
  PATCH_IF FILE_EXISTS_IN_GAME cdia328.itm BEGIN ADD_STORE_ITEM ~cdia328~ AFTER ~scrl1k _scrl1k~ #1 #0 #0 ~IDENTIFIED~ #2 END // Lance of Disruption
  PATCH_IF FILE_EXISTS_IN_GAME cdia422.itm BEGIN ADD_STORE_ITEM ~cdia422~ AFTER ~scrl5g _scrl5g~ #1 #0 #0 ~IDENTIFIED~ #2 END // Beltyn's Burning Blood
  PATCH_IF FILE_EXISTS_IN_GAME cdia426.itm BEGIN ADD_STORE_ITEM ~cdia426~ AFTER ~scrl5g _scrl5g~ #1 #0 #0 ~IDENTIFIED~ #2 END // Shadow Monsters
  PATCH_IF FILE_EXISTS_IN_GAME cdia427.itm BEGIN ADD_STORE_ITEM ~cdia427~ AFTER ~scrl5g _scrl5g~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Courage
  PATCH_IF FILE_EXISTS_IN_GAME cdia428.itm BEGIN ADD_STORE_ITEM ~cdia428~ AFTER ~scrl5g _scrl5g~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Fear
  PATCH_IF FILE_EXISTS_IN_GAME cdia429.itm BEGIN ADD_STORE_ITEM ~cdia429~ AFTER ~scrl5g _scrl5g~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Hope
  PATCH_IF FILE_EXISTS_IN_GAME cdia430.itm BEGIN ADD_STORE_ITEM ~cdia430~ AFTER ~scrl5g _scrl5g~ #1 #0 #0 ~IDENTIFIED~ #2 END // mordenkainen's force missiles
  PATCH_IF FILE_EXISTS_IN_GAME cdia432.itm BEGIN ADD_STORE_ITEM ~cdia432~ AFTER ~scrl5g _scrl5g~ #1 #0 #0 ~IDENTIFIED~ #2 END // Vitriolic Sphere
  PATCH_IF FILE_EXISTS_IN_GAME cdia524.itm BEGIN ADD_STORE_ITEM ~cdia524~ AFTER ~scrl5k _scrl5k~ #1 #0 #0 ~IDENTIFIED~ #1 END // shroud of flame
  PATCH_IF FILE_EXISTS_IN_GAME cdia525.itm BEGIN ADD_STORE_ITEM ~cdia525~ AFTER ~scrl5k _scrl5k~ #1 #0 #0 ~IDENTIFIED~ #1 END // Demi-Shadow Monsters
  PATCH_IF FILE_EXISTS_IN_GAME cdia526.itm BEGIN ADD_STORE_ITEM ~cdia526~ AFTER ~scrl5k _scrl5k~ #1 #0 #0 ~IDENTIFIED~ #1 END // Summon Shadow
  PATCH_IF FILE_EXISTS_IN_GAME cdia528.itm BEGIN ADD_STORE_ITEM ~cdia528~ AFTER ~scrl5k _scrl5k~ #1 #0 #0 ~IDENTIFIED~ #1 END // contact other plane
  PATCH_IF FILE_EXISTS_IN_GAME cdia533.itm BEGIN ADD_STORE_ITEM ~cdia533~ AFTER ~scrl5k _scrl5k~ #1 #0 #0 ~IDENTIFIED~ #1 END // Conjure water elemental
  BUT_ONLY IF_EXISTS

COPY_EXISTING ~25spell.sto~  ~override~ // arcana archives
              ~25spell2.sto~ ~override~ // arcana archives
              ~ohbmhsm.sto~  ~override~ // Book Merchant (BG2EE Black Pits 2)
              ~ohnmhsm.sto~  ~override~ // Book Merchant (BG2EE Neera's Quest)
  PATCH_IF FILE_EXISTS_IN_GAME cdia126.itm BEGIN ADD_STORE_ITEM ~cdia126~ AFTER ~scrl84~ #1 #0 #0 ~IDENTIFIED~ #2 END // expeditious retreat
  PATCH_IF FILE_EXISTS_IN_GAME cdia204.itm BEGIN ADD_STORE_ITEM ~cdia204~ AFTER ~scrl93~ #1 #0 #0 ~IDENTIFIED~ #2 END // Snilloc's Snowball Swarm
  PATCH_IF FILE_EXISTS_IN_GAME cdia216.itm BEGIN ADD_STORE_ITEM ~cdia216~ AFTER ~scrl93~ #1 #0 #0 ~IDENTIFIED~ #2 END // decastave
  PATCH_IF FILE_EXISTS_IN_GAME cdia225.itm BEGIN ADD_STORE_ITEM ~cdia225~ AFTER ~scrl93~ #1 #0 #0 ~IDENTIFIED~ #2 END // cats grace
  PATCH_IF FILE_EXISTS_IN_GAME cdia327.itm BEGIN ADD_STORE_ITEM ~cdia327~ AFTER ~scrl1e~ #1 #0 #0 ~IDENTIFIED~ #2 END // Icelance
  PATCH_IF FILE_EXISTS_IN_GAME cdia328.itm BEGIN ADD_STORE_ITEM ~cdia328~ AFTER ~scrl1e~ #1 #0 #0 ~IDENTIFIED~ #2 END // Lance of Disruption
  PATCH_IF FILE_EXISTS_IN_GAME cdia422.itm BEGIN ADD_STORE_ITEM ~cdia422~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Beltyn's Burning Blood
  PATCH_IF FILE_EXISTS_IN_GAME cdia426.itm BEGIN ADD_STORE_ITEM ~cdia426~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Shadow Monsters
  PATCH_IF FILE_EXISTS_IN_GAME cdia427.itm BEGIN ADD_STORE_ITEM ~cdia427~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Courage
  PATCH_IF FILE_EXISTS_IN_GAME cdia428.itm BEGIN ADD_STORE_ITEM ~cdia428~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Fear
  PATCH_IF FILE_EXISTS_IN_GAME cdia429.itm BEGIN ADD_STORE_ITEM ~cdia429~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Hope
  PATCH_IF FILE_EXISTS_IN_GAME cdia430.itm BEGIN ADD_STORE_ITEM ~cdia430~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // mordenkainen's force missiles
  PATCH_IF FILE_EXISTS_IN_GAME cdia432.itm BEGIN ADD_STORE_ITEM ~cdia432~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Vitriolic Sphere
  PATCH_IF FILE_EXISTS_IN_GAME cdia524.itm BEGIN ADD_STORE_ITEM ~cdia524~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #2 END // Shroud of Flame
  PATCH_IF FILE_EXISTS_IN_GAME cdia525.itm BEGIN ADD_STORE_ITEM ~cdia525~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #2 END // Demi-Shadow Monsters
  PATCH_IF FILE_EXISTS_IN_GAME cdia526.itm BEGIN ADD_STORE_ITEM ~cdia526~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #2 END // Summon Shadow
  PATCH_IF FILE_EXISTS_IN_GAME cdia528.itm BEGIN ADD_STORE_ITEM ~cdia528~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #2 END // Contact Other Plane
  PATCH_IF FILE_EXISTS_IN_GAME cdia533.itm BEGIN ADD_STORE_ITEM ~cdia533~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #2 END // Conjure water elemental
  PATCH_IF FILE_EXISTS_IN_GAME cdia610.itm BEGIN ADD_STORE_ITEM ~cdia610~ AFTER ~scrl7p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Antimagic Shell
  PATCH_IF FILE_EXISTS_IN_GAME cdia626.itm BEGIN ADD_STORE_ITEM ~cdia626~ AFTER ~scrl7p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Lich Touch
  PATCH_IF FILE_EXISTS_IN_GAME cdia627.itm BEGIN ADD_STORE_ITEM ~cdia627~ AFTER ~scrl7p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Monster Summoning IV
  PATCH_IF FILE_EXISTS_IN_GAME cdia628.itm BEGIN ADD_STORE_ITEM ~cdia628~ AFTER ~scrl7p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Otiluke's Freezing Sphere
  PATCH_IF FILE_EXISTS_IN_GAME cdia629.itm BEGIN ADD_STORE_ITEM ~cdia629~ AFTER ~scrl7p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Shades
  PATCH_IF FILE_EXISTS_IN_GAME cdia630.itm BEGIN ADD_STORE_ITEM ~cdia630~ AFTER ~scrl7p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Darts of Bone
  PATCH_IF FILE_EXISTS_IN_GAME cdia631.itm BEGIN ADD_STORE_ITEM ~cdia631~ AFTER ~scrl7p~ #1 #0 #0 ~IDENTIFIED~ #2 END // soul eater
  PATCH_IF FILE_EXISTS_IN_GAME cdia632.itm BEGIN ADD_STORE_ITEM ~cdia632~ AFTER ~scrl7p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Trollish Fortitude
  PATCH_IF FILE_EXISTS_IN_GAME cdia706.itm BEGIN ADD_STORE_ITEM ~cdia706~ AFTER ~scrl8p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Monster Summoning V
  PATCH_IF FILE_EXISTS_IN_GAME cdia709.itm BEGIN ADD_STORE_ITEM ~cdia709~ AFTER ~scrl8p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Malavon's Rage
  PATCH_IF FILE_EXISTS_IN_GAME cdia724.itm BEGIN ADD_STORE_ITEM ~cdia724~ AFTER ~scrl8p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Acid Storm
  PATCH_IF FILE_EXISTS_IN_GAME cdia725.itm BEGIN ADD_STORE_ITEM ~cdia725~ AFTER ~scrl8p~ #1 #0 #0 ~IDENTIFIED~ #2 END // seven eyes
  PATCH_IF FILE_EXISTS_IN_GAME cdia726.itm BEGIN ADD_STORE_ITEM ~cdia726~ AFTER ~scrl8p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Suffocate
  PATCH_IF FILE_EXISTS_IN_GAME cdia801.itm BEGIN ADD_STORE_ITEM ~cdia801~ AFTER ~scrl8p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Monster Summoning VI
  PATCH_IF FILE_EXISTS_IN_GAME cdia802.itm BEGIN ADD_STORE_ITEM ~cdia802~ AFTER ~scrl8p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Mind Blank
  PATCH_IF FILE_EXISTS_IN_GAME cdia806.itm BEGIN ADD_STORE_ITEM ~cdia806~ AFTER ~scrl8p~ #1 #0 #0 ~IDENTIFIED~ #2 END // great shout
  PATCH_IF FILE_EXISTS_IN_GAME cdia814.itm BEGIN ADD_STORE_ITEM ~cdia814~ AFTER ~scrl8p~ #1 #0 #0 ~IDENTIFIED~ #2 END // Iron Body
  PATCH_IF FILE_EXISTS_IN_GAME cdia901.itm BEGIN ADD_STORE_ITEM ~cdia901~ AFTER ~scrlb4~ #1 #0 #0 ~IDENTIFIED~ #2 END // Monster Summoning VII
  BUT_ONLY IF_EXISTS

COPY_EXISTING ~scrolls.sto~  ~override~ // yuth
  PATCH_IF FILE_EXISTS_IN_GAME cdia126.itm BEGIN ADD_STORE_ITEM ~cdia126~ AFTER ~scrl84~ #1 #0 #0 ~IDENTIFIED~ #2 END // expeditious retreat
  PATCH_IF FILE_EXISTS_IN_GAME cdia204.itm BEGIN ADD_STORE_ITEM ~cdia204~ AFTER ~scrl93~ #1 #0 #0 ~IDENTIFIED~ #2 END // Snilloc's Snowball Swarm
  PATCH_IF FILE_EXISTS_IN_GAME cdia216.itm BEGIN ADD_STORE_ITEM ~cdia216~ AFTER ~scrl93~ #1 #0 #0 ~IDENTIFIED~ #2 END // decastave
  PATCH_IF FILE_EXISTS_IN_GAME cdia225.itm BEGIN ADD_STORE_ITEM ~cdia225~ AFTER ~scrl93~ #1 #0 #0 ~IDENTIFIED~ #2 END // cats grace
  PATCH_IF FILE_EXISTS_IN_GAME cdia327.itm BEGIN ADD_STORE_ITEM ~cdia327~ AFTER ~scrl1e~ #1 #0 #0 ~IDENTIFIED~ #2 END // Icelance
  PATCH_IF FILE_EXISTS_IN_GAME cdia328.itm BEGIN ADD_STORE_ITEM ~cdia328~ AFTER ~scrl1e~ #1 #0 #0 ~IDENTIFIED~ #2 END // Lance of Disruption
  PATCH_IF FILE_EXISTS_IN_GAME cdia422.itm BEGIN ADD_STORE_ITEM ~cdia422~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #3 END // Beltyn's Burning Blood
  PATCH_IF FILE_EXISTS_IN_GAME cdia426.itm BEGIN ADD_STORE_ITEM ~cdia426~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Shadow Monsters
  PATCH_IF FILE_EXISTS_IN_GAME cdia427.itm BEGIN ADD_STORE_ITEM ~cdia427~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Courage
  PATCH_IF FILE_EXISTS_IN_GAME cdia428.itm BEGIN ADD_STORE_ITEM ~cdia428~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Fear
  PATCH_IF FILE_EXISTS_IN_GAME cdia429.itm BEGIN ADD_STORE_ITEM ~cdia429~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Hope
  PATCH_IF FILE_EXISTS_IN_GAME cdia430.itm BEGIN ADD_STORE_ITEM ~cdia430~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // mordenkainen's force missiles
  PATCH_IF FILE_EXISTS_IN_GAME cdia432.itm BEGIN ADD_STORE_ITEM ~cdia432~ AFTER ~scrl1y~ #1 #0 #0 ~IDENTIFIED~ #2 END // Vitriolic Sphere
  PATCH_IF FILE_EXISTS_IN_GAME cdia524.itm BEGIN ADD_STORE_ITEM ~cdia524~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #4 END // Shroud of Flame
  PATCH_IF FILE_EXISTS_IN_GAME cdia525.itm BEGIN ADD_STORE_ITEM ~cdia525~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #3 END // Demi-Shadow Monsters
  PATCH_IF FILE_EXISTS_IN_GAME cdia526.itm BEGIN ADD_STORE_ITEM ~cdia526~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #2 END // Summon Shadow
  PATCH_IF FILE_EXISTS_IN_GAME cdia528.itm BEGIN ADD_STORE_ITEM ~cdia528~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #2 END // Contact Other Plane
  PATCH_IF FILE_EXISTS_IN_GAME cdia533.itm BEGIN ADD_STORE_ITEM ~cdia533~ AFTER ~scrl6v~ #1 #0 #0 ~IDENTIFIED~ #2 END // Conjure water elemental
  PATCH_IF FILE_EXISTS_IN_GAME cdia610.itm BEGIN ADD_STORE_ITEM ~cdia610~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // Antimagic Shell
  PATCH_IF FILE_EXISTS_IN_GAME cdia626.itm BEGIN ADD_STORE_ITEM ~cdia626~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // Lich Touch
  PATCH_IF FILE_EXISTS_IN_GAME cdia627.itm BEGIN ADD_STORE_ITEM ~cdia627~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // Monster Summoning IV
  PATCH_IF FILE_EXISTS_IN_GAME cdia628.itm BEGIN ADD_STORE_ITEM ~cdia628~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #3 END // Otiluke's Freezing Sphere
  PATCH_IF FILE_EXISTS_IN_GAME cdia629.itm BEGIN ADD_STORE_ITEM ~cdia629~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // Shades
  PATCH_IF FILE_EXISTS_IN_GAME cdia630.itm BEGIN ADD_STORE_ITEM ~cdia630~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #3 END // Darts of Bone
  PATCH_IF FILE_EXISTS_IN_GAME cdia631.itm BEGIN ADD_STORE_ITEM ~cdia631~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // soul eater
  PATCH_IF FILE_EXISTS_IN_GAME cdia632.itm BEGIN ADD_STORE_ITEM ~cdia632~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // Trollish Fortitude
  PATCH_IF FILE_EXISTS_IN_GAME cdia706.itm BEGIN ADD_STORE_ITEM ~cdia706~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // Monster Summoning V
  PATCH_IF FILE_EXISTS_IN_GAME cdia709.itm BEGIN ADD_STORE_ITEM ~cdia709~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // Malavon's Rage
  PATCH_IF FILE_EXISTS_IN_GAME cdia724.itm BEGIN ADD_STORE_ITEM ~cdia724~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #3 END // Acid Storm
  PATCH_IF FILE_EXISTS_IN_GAME cdia725.itm BEGIN ADD_STORE_ITEM ~cdia725~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // seven eyes
  PATCH_IF FILE_EXISTS_IN_GAME cdia726.itm BEGIN ADD_STORE_ITEM ~cdia726~ AFTER ~scrlal~ #1 #0 #0 ~IDENTIFIED~ #2 END // Suffocate
  PATCH_IF FILE_EXISTS_IN_GAME cdia901.itm BEGIN ADD_STORE_ITEM ~cdia901~ AFTER ~scrlan~ #1 #0 #0 ~IDENTIFIED~ #2 END // Monster Summoning VII
  PATCH_IF FILE_EXISTS_IN_GAME cdia801.itm BEGIN ADD_STORE_ITEM ~cdia801~ AFTER ~scrlan~ #1 #0 #0 ~IDENTIFIED~ #2 END // Monster Summoning VI
  PATCH_IF FILE_EXISTS_IN_GAME cdia802.itm BEGIN ADD_STORE_ITEM ~cdia802~ AFTER ~scrlan~ #1 #0 #0 ~IDENTIFIED~ #3 END // Mind Blank
  PATCH_IF FILE_EXISTS_IN_GAME cdia806.itm BEGIN ADD_STORE_ITEM ~cdia806~ AFTER ~scrlan~ #1 #0 #0 ~IDENTIFIED~ #2 END // great shout
  PATCH_IF FILE_EXISTS_IN_GAME cdia814.itm BEGIN ADD_STORE_ITEM ~cdia814~ AFTER ~scrlan~ #1 #0 #0 ~IDENTIFIED~ #2 END // Iron Body
  BUT_ONLY IF_EXISTS

COPY_EXISTING ~shop08.sto~  ~override~ // galoomp
  PATCH_IF FILE_EXISTS_IN_GAME cdia126.itm BEGIN ADD_STORE_ITEM ~cdia126~ AFTER ~scrl84~ #1 #0 #0 ~IDENTIFIED~ #2 END // expeditious retreat
  PATCH_IF FILE_EXISTS_IN_GAME cdia204.itm BEGIN ADD_STORE_ITEM ~cdia204~ AFTER ~scrl93~ #1 #0 #0 ~IDENTIFIED~ #4 END // Snilloc's Snowball Swarm
  PATCH_IF FILE_EXISTS_IN_GAME cdia216.itm BEGIN ADD_STORE_ITEM ~cdia216~ AFTER ~scrl93~ #1 #0 #0 ~IDENTIFIED~ #2 END // decastave
  PATCH_IF FILE_EXISTS_IN_GAME cdia225.itm BEGIN ADD_STORE_ITEM ~cdia225~ AFTER ~scrl93~ #1 #0 #0 ~IDENTIFIED~ #2 END // cats grace
  PATCH_IF FILE_EXISTS_IN_GAME cdia327.itm BEGIN ADD_STORE_ITEM ~cdia327~ AFTER ~scrl1e~ #1 #0 #0 ~IDENTIFIED~ #2 END // Icelance
  PATCH_IF FILE_EXISTS_IN_GAME cdia328.itm BEGIN ADD_STORE_ITEM ~cdia328~ AFTER ~scrl1e~ #1 #0 #0 ~IDENTIFIED~ #2 END // Lance of Disruption
  PATCH_IF FILE_EXISTS_IN_GAME cdia422.itm BEGIN ADD_STORE_ITEM ~cdia422~ AFTER ~scrl5m~ #1 #0 #0 ~IDENTIFIED~ #2 END // Beltyn's Burning Blood
  PATCH_IF FILE_EXISTS_IN_GAME cdia426.itm BEGIN ADD_STORE_ITEM ~cdia426~ AFTER ~scrl5m~ #1 #0 #0 ~IDENTIFIED~ #3 END // Shadow Monsters
  PATCH_IF FILE_EXISTS_IN_GAME cdia427.itm BEGIN ADD_STORE_ITEM ~cdia427~ AFTER ~scrl5m~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Courage
  PATCH_IF FILE_EXISTS_IN_GAME cdia428.itm BEGIN ADD_STORE_ITEM ~cdia428~ AFTER ~scrl5m~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Fear
  PATCH_IF FILE_EXISTS_IN_GAME cdia429.itm BEGIN ADD_STORE_ITEM ~cdia429~ AFTER ~scrl5m~ #1 #0 #0 ~IDENTIFIED~ #2 END // Emotion: Hope
  PATCH_IF FILE_EXISTS_IN_GAME cdia430.itm BEGIN ADD_STORE_ITEM ~cdia430~ AFTER ~scrl5m~ #1 #0 #0 ~IDENTIFIED~ #2 END // mordenkainen's force missiles
  PATCH_IF FILE_EXISTS_IN_GAME cdia432.itm BEGIN ADD_STORE_ITEM ~cdia432~ AFTER ~scrl5m~ #1 #0 #0 ~IDENTIFIED~ #3 END // Vitriolic Sphere
  PATCH_IF FILE_EXISTS_IN_GAME cdia524.itm BEGIN ADD_STORE_ITEM ~cdia524~ AFTER ~scrl2f~ #1 #0 #0 ~IDENTIFIED~ #3 END // Shroud of Flame
  PATCH_IF FILE_EXISTS_IN_GAME cdia525.itm BEGIN ADD_STORE_ITEM ~cdia525~ AFTER ~scrl2f~ #1 #0 #0 ~IDENTIFIED~ #2 END // Demi-Shadow Monsters
  PATCH_IF FILE_EXISTS_IN_GAME cdia526.itm BEGIN ADD_STORE_ITEM ~cdia526~ AFTER ~scrl2f~ #1 #0 #0 ~IDENTIFIED~ #2 END // Summon Shadow
  PATCH_IF FILE_EXISTS_IN_GAME cdia528.itm BEGIN ADD_STORE_ITEM ~cdia528~ AFTER ~scrl2f~ #1 #0 #0 ~IDENTIFIED~ #1 END // Contact Other Plane
  PATCH_IF FILE_EXISTS_IN_GAME cdia533.itm BEGIN ADD_STORE_ITEM ~cdia533~ AFTER ~scrl2f~ #1 #0 #0 ~IDENTIFIED~ #2 END // Conjure water elemental
  BUT_ONLY IF_EXISTS
