APPEND ~clabba01.2da~ ~ABILITYX AP_CDIBAR0 **** GA_CDIBAR1 **** **** **** **** **** **** **** **** CDREPLACE
ABILITYY **** **** GA_CDIBAR2 **** GA_CDIBAR3 **** GA_CDIBAR4 **** GA_CDIBAR5 **** GA_CDIBAR6 CDREPLACE~

COPY_EXISTING ~clabba01.2da~ ~override~
  COUNT_2DA_COLS cols
  FOR (index = 13 ; index < cols ; ++index) BEGIN
    REPLACE_TEXTUALLY ~CDREPLACE~ ~**** CDREPLACE~
  END
  REPLACE_TEXTUALLY ~CDREPLACE~ ~****~
  SET "ability" = 0
  REPLACE_EVALUATE ~^\(ABILITY[0-9A-Z]+\)[ %TAB%]~ BEGIN
    SET "ability" = ("%ability%" + 1)
  END
  ~ABILITY%ability% ~
  PRETTY_PRINT_2DA

ACTION_IF FILE_EXISTS_IN_GAME luba0.2da THEN BEGIN

  COPY_EXISTING ~luba0.2da~ ~override~ // remove enhanced bard song from HLAs
    REPLACE_TEXTUALLY ~^\([0-9]+[ %TAB%]+AP_SPCL920[ %TAB%]+\*[ %TAB%]+\*[ %TAB%]+[0-9]+[ %TAB%]+[0-9]+[ %TAB%]+[0-9]+[ %TAB%]+\)\*\([ %TAB%]+\*[ %TAB%]+\*\)~
      ~\1SPCL920\2~ // create self-reference, never allowing it to be selected
    PRETTY_PRINT_2DA

END

ADD_PROJECTILE ~iwdification/pro/cdivrnp.pro~ // visual range, non-party for siren's yearning

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@5002) STR_VAR bam_file = cdibar0 RET cdibarap = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@5005) STR_VAR bam_file = cdibar0 RET cdibarbp = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@5008) STR_VAR bam_file = cdibar0 RET cdibarcp = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@5011) STR_VAR bam_file = cdibar0 RET cdibardp = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@5014) STR_VAR bam_file = cdibar0 RET cdibarep = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@5018) STR_VAR bam_file = cdibar0 RET cdibarfp = icon END

COPY ~iwdification/bam/cdibar0.bam~  ~override~
     ~iwdification/bam/cdibara.bam~  ~override~
     ~iwdification/bam/cdibarb.bam~  ~override~
     ~iwdification/bam/cdibarc.bam~  ~override~
     ~iwdification/bam/cdibard.bam~  ~override~
     ~iwdification/bam/cdibare.bam~  ~override~
     ~iwdification/bam/cdibarf.bam~  ~override~
     ~iwdification/spl/cdibar0.spl~  ~override~

ACTION_IF ee_game BEGIN

  STRING_SET 9562 @5020

  COPY ~iwdification/bam/cdibar0.bam~  ~override~
       ~iwdification/spl/cdibare0.spl~ ~override~

END ELSE BEGIN

  COPY ~iwdification/eff/immunity.eff~ ~override/cdibarex.eff~
    WRITE_ASCII 0x30 ~cdibare~ #8

END

COPY ~iwdification/spl/cdibar1.spl~ ~override~ // The Ballad of Three Heroes - Combat Bonuses
  SAY 0x08 @5001
  SAY 0x0c @5001
  SAY 0x50 @5003
  SAY 0x54 @5003

COPY ~iwdification/spl/cdibara.spl~ ~override~
  SAY 0x08 @5002
  SAY 0x0c @5002
  SAY 0x50 @5003
  SAY 0x54 @5003
  PATCH_IF ee_game BEGIN
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 177 parameter2 = cdibarap END
  END ELSE BEGIN
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
    LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 177 parameter2 = 40 END
    LPF ALTER_EFFECT INT_VAR match_duration = 7 timing = 10 duration = 100 END
  END

COPY ~iwdification/spl/cdibar2.spl~ ~override~ // The Tale of Curran Strongheart - Immunity Fear
  SAY 0x08 @5004
  SAY 0x0c @5004
  SAY 0x50 @5006
  SAY 0x54 @5006

COPY ~iwdification/spl/cdibarb.spl~ ~override~
  SAY 0x08 @5005
  SAY 0x0c @5005
  SAY 0x50 @5006
  SAY 0x54 @5006
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 111111 parameter1 = string_mf_panic END
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 222222 parameter1 = string_panic END
  PATCH_IF ee_game BEGIN
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 178 parameter2 = cdibarbp END
  END ELSE BEGIN
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
    LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 318 opcode = 206 parameter1 = 0 parameter2 = 0 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 178 parameter2 = 40 END
    LPF ALTER_EFFECT INT_VAR match_duration = 7 timing = 10 duration = 100 END
  END

COPY ~iwdification/spl/cdibar3.spl~ ~override~ // Tymora's Melody - Luck and Skill Bonuses
  SAY 0x08 @5007
  SAY 0x0c @5007
  SAY 0x50 @5009
  SAY 0x54 @5009

COPY ~iwdification/spl/cdibarc.spl~ ~override~
  SAY 0x08 @5008
  SAY 0x0c @5008
  SAY 0x50 @5009
  SAY 0x54 @5009
  PATCH_IF ee_game BEGIN
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 179 parameter2 = cdibarcp END
  END ELSE BEGIN
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
    LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 179 parameter2 = 40 END
    LPF ALTER_EFFECT INT_VAR match_duration = 7 timing = 10 duration = 100 END
  END

COPY ~iwdification/spl/cdibar4.spl~ ~override~ // The Song of Kaudies - Resistant to Sound Attacks
  SAY 0x08 @5010
  SAY 0x0c @5010
  SAY 0x50 @5012
  SAY 0x54 @5012

COPY ~iwdification/spl/cdibard.spl~ ~override~
  SAY 0x08 @5011
  SAY 0x0c @5011
  SAY 0x50 @5012
  SAY 0x54 @5012
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14002 parameter1 = string_silence END
  LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14676 parameter1 = string_silenced END
  LPF ALTER_EFFECT INT_VAR match_opcode = 206 match_parameter1 =  4742 parameter1 = string_ineffective END
  PATCH_FOR_EACH res IN 
    POWERWORD_KILL POWERWORD_STUN POWERWORD_BLIND PLAYER1_WORD_OF_POWER IRENICUS_WORD_OF_POWER DEMILICH_DEATH MOON_DOG_FEAR BANSHEE_WAIL ELVEN_GUARD_WAIL // bg2ee, bgee
    WIZARD_SHOUT WIZARD_GREAT_SHOUT INNATE_MOURNFUL_WAIL INNATE_DEATH_KNELL INNATE_WAR_CRY INNATE_UNDYING_LAMENT INNATE_GREAT_ROAR INNATE_HARPY_WAIL_INTERNAL // iwdee, iwdification
  BEGIN
    SET num = IDS_OF_SYMBOL (~spell~ ~%res%~)
    PATCH_IF num > 3999 BEGIN SET num -= 4000 SPRINT prefix spcl END
    PATCH_IF num > 2999 BEGIN SET num -= 3000 SPRINT prefix spin END
    PATCH_IF num > 1999 BEGIN SET num -= 2000 SPRINT prefix spwi END
    PATCH_IF num >  999 BEGIN SET num -= 1000 SPRINT prefix sppr END
    PATCH_IF num >  0 BEGIN
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 3 parameter1 = string_ineffective duration = 7 probability1 = 50 STR_VAR resource = EVAL ~%prefix%%num%~  END
    END
  END
  PATCH_IF ee_game BEGIN
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 180 parameter2 = cdibardp END
  END ELSE BEGIN
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
    LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 180 parameter2 = 40 END
    LPF ALTER_EFFECT INT_VAR match_duration = 7 timing = 10 duration = 100 END
  END

COPY ~iwdification/spl/cdibar5.spl~ ~override~ // The Siren's Yearning - Enthralls Creatures
  SAY 0x08 @5013
  SAY 0x0c @5013
  SAY 0x50 @5015
  SAY 0x54 @5015

COPY ~iwdification/spl/cdibare.spl~ ~override~
  SAY 0x08 @5014
  SAY 0x0c @5014
  SAY 0x50 @5015
  SAY 0x54 @5015
  SAY 0x2ae @5016
  LPF ALTER_SPELL_HEADER INT_VAR projectile = cdivrnp END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 267 match_parameter1 = 1280 parameter1 = string_stunned END
  PATCH_IF ee_game BEGIN
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 181 parameter2 = cdibarep END
  END ELSE BEGIN
    LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdibarex END // race = golem
    LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdibarex END // general = undead
    LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  15 opcode = 177 parameter1 =   2 parameter2 = 4 STR_VAR resource = cdibarex END // race = elf
    LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  19 opcode = 177 parameter1 =   3 parameter2 = 4 STR_VAR resource = cdibarex END // race = halfelf
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
    LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
    LPF DELETE_EFFECT INT_VAR match_opcode = 232 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 181 parameter2 = 40 END
    LPF ALTER_EFFECT INT_VAR match_duration = 7 timing = 10 duration = 100 END
  END

COPY ~iwdification/spl/cdibar6.spl~ ~override~ // War Chant of Sith - Armor Bonuses and Regeneration
  SAY 0x08 @5017
  SAY 0x0c @5017
  SAY 0x50 @5019
  SAY 0x54 @5019

COPY ~iwdification/spl/cdibarf.spl~ ~override~
  SAY 0x08 @5018
  SAY 0x0c @5018
  SAY 0x50 @5019
  SAY 0x54 @5019
  PATCH_IF ee_game BEGIN
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 182 parameter2 = cdibarfp END
  END ELSE BEGIN
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
    LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 182 parameter2 = 40 END
    LPF ALTER_EFFECT INT_VAR match_duration = 7 timing = 10 duration = 100 END
  END
