INCLUDE ~iwdification/lib/spell_prep.tpa~

/////                                                  \\\\\
///// CLERIC_CURSE                                     \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_CURSE~) OR override_divine) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi237.pro~

  ADD_SPELL ~iwdification/spl/cdid112.spl~ 1 1 CLERIC_CURSE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4010 // name
    SAY 0x50 @4011 // descript
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14406 parameter1 = string_cursed END
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi237 END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdid112 resource = EVAL ~%DEST_RES%~ END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = EVAL ~%DEST_RES%~ END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid112.itm~
    SAY 0x0c @4010
    SAY 0x54 @4011
    LPF cd_scroll INT_VAR target_hdr = 4 range = 40 opcode = 148 target_eff = 1 price = 100 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdid112a.bam~ ~override~
       ~iwdification/bam/cdid112b.bam~ ~override~
       ~iwdification/bam/cdid112c.bam~ ~override~
       ~iwdification/bam/cdiare1x.bam~ ~override~
       ~iwdification/bam/cdicurse.bam~ ~override~
       ~iwdification/vvc/cdibless.vvc~ ~override~
       ~iwdification/vvc/cdicurse.vvc~ ~override~
       ~iwdification/wav/cdiee04.wav~  ~override~
       ~iwdification/wav/cdiep32.wav~  ~override~
       ~iwdification/wav/cdiep99.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_CAUSE_LIGHT_WOUNDS                        \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_CAUSE_LIGHT_WOUNDS~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid114.spl~ 1 1 CLERIC_CAUSE_LIGHT_WOUNDS
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4020 // name
    SAY 0x50 @4021 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid114 resource = EVAL ~%DEST_RES%~ END
    PATCH_IF !ee_game BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixd114 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixd114 END // general = undead
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 104 opcode = 177                  parameter2 = 4 STR_VAR resource = cdixd114 END // race = parameter1
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid114.itm~
    SAY 0x0c @4020
    SAY 0x54 @4021
    LPF cd_scroll INT_VAR unusable0 = (BIT2 + BIT12 + BIT21 + BIT30) range = 1 price = 100 STR_VAR spell = EVAL ~%current_spell_res%~ END // non-good, cleric

  COPY ~iwdification/bam/cdid114a.bam~ ~override~
       ~iwdification/bam/cdid114b.bam~ ~override~
       ~iwdification/bam/cdid114c.bam~ ~override~
       ~iwdification/bam/cdicldam.bam~ ~override~
       ~iwdification/vvc/cdicldam.vvc~ ~override~
       ~iwdification/wav/cdiem103.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd114.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_SUNSCORCH                                 \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_SUNSCORCH~) OR override_divine) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdisunsc.pro~
  
  END

  ADD_SPELL ~iwdification/spl/cdid115.spl~ 1 1 CLERIC_SUNSCORCH
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4030 // name
    SAY 0x50 @4031 // descript
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37800 parameter1 = string_blinded END
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdisunsc END
    END ELSE BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 326 opcode = 177 parameter1 =   4 parameter2 = 3 END // general = undead
      LPF ALTER_EFFECT INT_VAR match_opcode = 326 opcode = 177 parameter1 = 164 parameter2 = 4 END // race = myconid
      READ_SHORT 0x68 abil_num
      FOR (index = 0 ; index < abil_num ; ++index) BEGIN
        LPF ALTER_EFFECT INT_VAR header = index match_opcode = 12 parameter1 = ((index + 1) / 2) dicesize = 3 special = 0 END
        LPF CLONE_EFFECT INT_VAR header = index match_opcode = 12 parameter1 = ((index + 0) / 2) savingthrow = 0 END
      END
      PATCH_FOR_EACH res IN cdid1151 cdid1152 cdid1153 cdid1154 BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 215 target = 2 power = 1 timing = 1 resist_dispel = 3 STR_VAR resource = EVAL ~%res%~ END
      END  
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid115.itm~
    SAY 0x0c @4030
    SAY 0x54 @4031
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) range = 100 price = 100 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

    COPY ~iwdification/bam/cdid115a.bam~ ~override~
         ~iwdification/bam/cdid115b.bam~ ~override~
         ~iwdification/bam/cdid115c.bam~ ~override~
         ~iwdification/bam/cdisunsc.bam~ ~override~
         ~iwdification/spl/cdid115d.spl~ ~override~
         ~iwdification/wav/cdiep39.wav~  ~override~

  ACTION_IF ee_game BEGIN

    COPY ~iwdification/vvc/cdisunsc.vvc~ ~override~

  END ELSE BEGIN

    COPY ~iwdification/vvc/cdid1151.vvc~ ~override~
         ~iwdification/vvc/cdid1152.vvc~ ~override~
         ~iwdification/vvc/cdid1153.vvc~ ~override~
         ~iwdification/vvc/cdid1154.vvc~ ~override~
    
    COPY ~iwdification/eff/326.eff~ ~override/cdid115d.eff~
      WRITE_ASCII 0x30 ~cdid115d~

  END

END

/////                                                  \\\\\
///// CLERIC_CURE_MODERATE_WOUNDS                      \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_CURE_MODERATE_WOUNDS~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid217.spl~ 1 2 CLERIC_CURE_MODERATE_WOUNDS
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4040 // name
    SAY 0x50 @4041 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid217 resource = EVAL ~%DEST_RES%~ END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14022 parameter1 = string_healed END
    PATCH_IF !ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 61 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixd114 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixd114 END // general = undead
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 104 opcode = 177                  parameter2 = 4 STR_VAR resource = cdixd114 END // race = parameter1
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid217.itm~
    SAY 0x0c @4040
    SAY 0x54 @4041
    LPF cd_scroll INT_VAR range = 1 price = 200 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdid217a.bam~ ~override~
       ~iwdification/bam/cdid217b.bam~ ~override~
       ~iwdification/bam/cdid217c.bam~ ~override~
       ~iwdification/bam/cdicmwou.bam~ ~override~
       ~iwdification/vvc/cdicmwou.vvc~ ~override~
       ~iwdification/wav/cdiep26.wav~  ~override~
    
  // add as option to temples that offer cure light wounds
  OUTER_SET desc = RESOLVE_STR_REF(@4042)
  APPEND ~speldesc.2da~ ~sppr217 %desc%~
  COPY_EXISTING_REGEXP GLOB ~^.+\.sto$~ ~override~
    READ_LONG 0x70 cure_off
    READ_LONG 0x74 cure_num
    SET insert_cost = 0
    SET insert_off = 0
    FOR (index = 0 ; index < cure_num ; ++index) BEGIN
      READ_ASCII (cure_off +        (index * 0x0c)) spell
      PATCH_IF ("%spell%" STRING_COMPARE_REGEXP "sppr1[0-9][0-9]" = 0) BEGIN
        SET insert_off =  (cure_off +        ((index + 1) * 0x0c))
        PATCH_IF ("%spell%" STRING_COMPARE_CASE "sppr103" = 0) BEGIN
          READ_LONG (cure_off + 0x08 + (index * 0x0c)) insert_cost
        END
      END
    END
    PATCH_IF insert_off AND insert_cost BEGIN
      INSERT_BYTES   (insert_off       ) 0x0c
        WRITE_ASCIIE (insert_off       ) ~%current_spell_res%~ #8
        WRITE_LONG   (insert_off + 0x08) (insert_cost * 2)
      WRITE_LONG 0x74 (THIS + 1)
      PATCH_FOR_EACH off IN 0x2c 0x34 0x4c BEGIN // item, sale, drink offsets
        READ_LONG off val                        // read offset
        PATCH_IF val > cure_off BEGIN            // if after cure list...
          WRITE_LONG off (THIS + 0x0c)           // push back for new cure
        END
      END
    END
    BUT_ONLY

END

/////                                                  \\\\\
///// CLERIC_ALICORN_LANCE                             \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_ALICORN_LANCE~) OR override_divine) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi298.pro~

  ADD_SPELL ~iwdification/spl/cdid218.spl~ 1 2 CLERIC_ALICORN_LANCE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4050 // name
    SAY 0x50 @4051 // descript
    SAY 0x2ae @4052
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi298 END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdid218 resource = EVAL ~%DEST_RES%~ END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF CD_SPLIT_SAVE_DAMAGE END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid218.itm~
    SAY 0x0c @4050
    SAY 0x54 @4051
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) range = 100 price = 200 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/bam/cdid218a.bam~ ~override~
       ~iwdification/bam/cdid218b.bam~ ~override~
       ~iwdification/bam/cdid218c.bam~ ~override~
       ~iwdification/bam/cdilanct.bam~ ~override~
       ~iwdification/wav/cdiee08.wav~  ~override~
       ~iwdification/wav/cditra57.wav~ ~override~

END

/////                                                  \\\\\
///// CLERIC_BEAST_CLAW                                \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_BEAST_CLAW~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid219.spl~ 1 2 CLERIC_BEAST_CLAW
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4060 // name
    SAY 0x50 @4061 // descript

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid219.itm~
    SAY 0x0c @4060
    SAY 0x54 @4061
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 5 range = 1 price = 200 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/itm/cdibclaw.itm~ ~override~
    SAY 0x08 @4060
    SAY 0x0c @4060

  COPY ~iwdification/bam/cdid219a.bam~ ~override~
       ~iwdification/bam/cdid219b.bam~ ~override~
       ~iwdification/bam/cdid219c.bam~ ~override~
       ~iwdification/bam/cdialter.bam~ ~override~
       ~iwdification/bam/cdibclaw.bam~ ~override~
       ~iwdification/vvc/cdialter.vvc~ ~override~
       ~iwdification/wav/cdiep07.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_CAUSE_MODERATE_WOUNDS                     \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_CAUSE_MODERATE_WOUNDS~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid220.spl~ 1 2 CLERIC_CAUSE_MODERATE_WOUNDS
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4070 // name
    SAY 0x50 @4071 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid220 resource = EVAL ~%DEST_RES%~ END
    PATCH_IF !ee_game BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixd220 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixd220 END // general = undead
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 104 opcode = 177                  parameter2 = 4 STR_VAR resource = cdixd220 END // race = parameter1
      LPF CD_SPLIT_SAVE_DAMAGE END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid220.itm~
    SAY 0x0c @4070
    SAY 0x54 @4071
    LPF cd_scroll INT_VAR unusable0 = (BIT2 + BIT12 + BIT21 + BIT30) range = 1 price = 200 STR_VAR spell = EVAL ~%current_spell_res%~ END // non-good cleric

  COPY ~iwdification/bam/cdid220a.bam~ ~override~
       ~iwdification/bam/cdid220b.bam~ ~override~
       ~iwdification/bam/cdid220c.bam~ ~override~
       ~iwdification/bam/cdicmdam.bam~ ~override~
       ~iwdification/vvc/cdicmdam.vvc~ ~override~
       ~iwdification/wav/cdiem103.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd220.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_PRAYER                                    \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_PRAYER~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4080) STR_VAR bam_file = cdid316d RET icon END

  ADD_PROJECTILE ~iwdification/pro/cdivrnp.pro~
  ADD_PROJECTILE ~iwdification/pro/cdivrpo.pro~

  ADD_SPELL ~iwdification/spl/cdid316.spl~ 1 3 CLERIC_PRAYER
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4080 // name
    SAY 0x50 @4081 // descript

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid316.itm~
    SAY 0x0c @4080
    SAY 0x54 @4081
    LPF cd_scroll INT_VAR unusable0 = (BIT12 + BIT21 + BIT30) target_hdr = 5 range = 40 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // cleric

  COPY ~iwdification/spl/cdid316b.spl~ ~override~
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdivrnp END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 40257 parameter1 = RESOLVE_STR_REF(@4082) END
    PATCH_IF !ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = cdid316b END
      LPF CD_CONVERT_9_255 END
    END

  COPY ~iwdification/spl/cdid316g.spl~ ~override~
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdivrpo END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 40256 parameter1 = RESOLVE_STR_REF(@4083) END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 183 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 183 parameter2 = 18 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = cdid316g END
      LPF CD_CONVERT_9_255 END
    END

  COPY ~iwdification/bam/cdid316a.bam~ ~override~
       ~iwdification/bam/cdid316b.bam~ ~override~
       ~iwdification/bam/cdid316c.bam~ ~override~
       ~iwdification/bam/cdid316d.bam~ ~override~
       ~iwdification/bam/cdiprayh.bam~ ~override~
       ~iwdification/vvc/cdiprayg.vvc~ ~override~
       ~iwdification/vvc/cdiprayh.vvc~ ~override~
       ~iwdification/wav/cdiep31.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_CAUSE_DISEASE                             \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_CAUSE_DISEASE~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid320.spl~ 1 3 CLERIC_CAUSE_DISEASE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4090 // name
    SAY 0x50 @4091 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid320 resource = EVAL ~%DEST_RES%~ END
    PATCH_IF !ee_game BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixd320 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixd320 END // general = undead
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 104 opcode = 177                  parameter2 = 4 STR_VAR resource = cdixd320 END // race = parameter1
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid320.itm~
    SAY 0x0c @4090
    SAY 0x54 @4091
    LPF cd_scroll INT_VAR unusable0 = (BIT2 + BIT12 + BIT21 + BIT30) range = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // non-good cleric

  COPY ~iwdification/bam/cdid320a.bam~ ~override~
       ~iwdification/bam/cdid320b.bam~ ~override~
       ~iwdification/bam/cdid320c.bam~ ~override~
       ~iwdification/bam/cdidise.bam~  ~override~
       ~iwdification/vvc/cdidise.vvc~  ~override~
       ~iwdification/wav/cdiep108.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd320.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_EXALTATION                                \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_EXALTATION~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4100) STR_VAR bam_file = cdid321d RET icon END

  ADD_SPELL ~iwdification/spl/cdid321.spl~ 1 3 CLERIC_EXALTATION
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4100 // name
    SAY 0x50 @4101 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid321 resource = EVAL ~%DEST_RES%~ END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 20568 parameter1 = string_mf_panic END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35484 parameter1 = string_panic END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37340 parameter1 = string_uncon END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37603 parameter1 = string_rthinking END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37604 parameter1 = string_confused END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37605 parameter1 = string_berserk END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37606 parameter1 = string_intoxicated END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37613 parameter1 = string_sleep END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 174 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 174 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 opcode = 206 target = 1 parameter1 = 0 parameter2 = 0 END // prevent self-cast
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid321.itm~
    SAY 0x0c @4100
    SAY 0x54 @4101
    LPF cd_scroll INT_VAR unusable0 = (BIT12 + BIT21 + BIT30) range = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // cleric

  COPY ~iwdification/bam/cdid321a.bam~ ~override~
       ~iwdification/bam/cdid321b.bam~ ~override~
       ~iwdification/bam/cdid321c.bam~ ~override~
       ~iwdification/bam/cdid321d.bam~ ~override~
       ~iwdification/bam/cdiexalt.bam~ ~override~
       ~iwdification/vvc/cdiexalt.vvc~ ~override~
       ~iwdification/wav/cdiep106.wav~ ~override~

END

/////                                                  \\\\\
///// CLERIC_MOONBLADE                                 \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_MOONBLADE~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid322.spl~ 1 3 CLERIC_MOONBLADE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4110 // name
    SAY 0x50 @4111 // descript

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid322.itm~
    SAY 0x0c @4110
    SAY 0x54 @4111
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 5 range = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/itm/cdimoonb.itm~ ~override~
    SAY 0x08 @4110
    SAY 0x0c @4110
    LPF ALTER_EFFECT STR_VAR match_resource = moonbla resource = cdimoonb END
    PATCH_IF !ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 12 match_parameter1 = 0 END // delete undead damage, since it's going through an EFF
      LPF ALTER_EFFECT INT_VAR match_opcode = 318 opcode = 177 parameter1 = 4 parameter2 = 3 timing = 1 duration = 0 END
    END

  COPY ~iwdification/bam/cdid322a.bam~ ~override~
       ~iwdification/bam/cdid322b.bam~ ~override~
       ~iwdification/bam/cdid322c.bam~ ~override~
       ~iwdification/bam/cdiinvoc.bam~ ~override~
       ~iwdification/bam/cdimoonb.bam~ ~override~
       ~iwdification/vvc/cdiinvoc.vvc~ ~override~
       ~iwdification/wav/cdiem06.wav~  ~override~  
  
  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/cdimoonb.eff~ ~override~

  END

END

/////                                                  \\\\\
///// CLERIC_CIRCLE_OF_BONES                           \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_CIRCLE_OF_BONES~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid323.spl~ 1 3 CLERIC_CIRCLE_OF_BONES
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4120 // name
    SAY 0x50 @4121 // descript
    LPF ALTER_EFFECT INT_VAR match_opcode = 126 opcode = 176 END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid323.itm~
    SAY 0x0c @4120
    SAY 0x54 @4121
    LPF cd_scroll INT_VAR unusable0 = (BIT2 + BIT12 + BIT21 + BIT30) target_hdr = 5 range = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // non-good cleric

  COPY ~iwdification/bam/cdid323a.bam~ ~override~
       ~iwdification/bam/cdid323b.bam~ ~override~
       ~iwdification/bam/cdid323c.bam~ ~override~
       ~iwdification/bam/cdibone1.bam~ ~override~
       ~iwdification/bam/cdibone2.bam~ ~override~
       ~iwdification/spl/cdid323d.spl~ ~override~
       ~iwdification/vvc/cdibone1.vvc~ ~override~
       ~iwdification/vvc/cdibone2.vvc~ ~override~
       ~iwdification/wav/cdiafp22.wav~ ~override~
       ~iwdification/wav/cdiarp21.wav~ ~override~
       ~iwdification/wav/cdiep101.wav~ ~override~

END

/////                                                  \\\\\
///// CLERIC_SPIKE_GROWTH                              \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_SPIKE_GROWTH~) OR override_divine) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi300.pro~
  
  END ELSE BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi300a.pro~

  END

  ADD_SPELL ~iwdification/spl/cdid324.spl~ 1 3 CLERIC_SPIKE_GROWTH
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4130 // name
    SAY 0x50 @4131 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi300 END
    END ELSE BEGIN
      LPF DELETE_EFFECT END
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi300a END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 1 parameter2 = 2 STR_VAR resource = cdid324 END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 215 target = 1 parameter2 = 2 timing = 1 STR_VAR resource = cdisgrwa END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid324.itm~
    SAY 0x0c @4130
    SAY 0x54 @4131
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/bam/cdid324a.bam~ ~override~
       ~iwdification/bam/cdid324b.bam~ ~override~
       ~iwdification/bam/cdid324c.bam~ ~override~
       ~iwdification/bam/cdisgrwa.bam~ ~override~
       ~iwdification/bam/cdisgrwx.bam~ ~override~
       ~iwdification/vvc/cdisgrwa.vvc~ ~override~
       ~iwdification/vvc/cdisgrwx.vvc~ ~override~
       ~iwdification/wav/cdiafp24.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    LAUNCH_ACTION_FUNCTION cd_create_cloud INT_VAR visloop = 5 cloud_dur = 60 STR_VAR code = cdid324 anim = cdisgrwa END

    COPY ~iwdification/spl/cdid324.spl~ ~override~
      WRITE_LONG 0x08 "-1" // name
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi300a END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 215 target = 2 duration = 3 STR_VAR resource = cdisgrwx END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 2 duration = 6 STR_VAR resource = cdid324  END

  END

END

/////                                                  \\\\\
///// CLERIC_CLOUDBURST                                \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_CLOUDBURST~) OR override_divine) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi301.pro~
  
  END ELSE BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi301a.pro~

  END

  ADD_SPELL ~iwdification/spl/cdid325.spl~ 1 3 CLERIC_CLOUDBURST
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4140 // name
    SAY 0x50 @4141 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi301 END
      PATCH_FOR_EACH res IN firau1d2 firau3d6 frostd10 spin187 spin128 BEGIN // leftover iwdee references
        LPF DELETE_EFFECT STR_VAR match_resource = EVAL ~%res%~ END
      END
      LPF ALTER_EFFECT STR_VAR match_resource = cdid325 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT STR_VAR match_resource = fsalring resource = cdisalfi END // iwdifcation moves aura visuals to weapons
      LPF ALTER_EFFECT STR_VAR match_resource = csalring resource = cdisalfr END // iwdifcation moves aura visuals to weapons
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi301a END
      LPF DELETE_EFFECT END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 timing = 1 parameter2 = 2 STR_VAR resource = cdid325 END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid325.itm~
    SAY 0x0c @4140
    SAY 0x54 @4141
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/bam/cdid325a.bam~ ~override~
       ~iwdification/bam/cdid325b.bam~ ~override~
       ~iwdification/bam/cdid325c.bam~ ~override~
       ~iwdification/wav/cdiarp24.wav~ ~override~

  ACTION_IF ee_game BEGIN

    COPY ~iwdification/bam/cdibacld.bam~ ~override~
         ~iwdification/bam/cdibhcld.bam~ ~override~
         ~iwdification/vvc/cdibhcld.vvc~ ~override~

  END ELSE BEGIN

    LAUNCH_ACTION_FUNCTION cd_create_cloud INT_VAR visloop = 1 cloud_dur = 12 zosa = 1 STR_VAR code = cdid325 anim = cdibacld END

    COPY_EXISTING ~iwdification/spl/cdid325.spl~ ~override~
      WRITE_LONG 0x08 "-1" // name
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi301a END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 318 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 206 END
      LPF CD_SPLIT_SAVE_DAMAGE END
      PATCH_FOR_EACH res IN cdifire6 cdifros6 cdia524 cdia524b BEGIN // leftover iwdee references
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 2 duration = 6 STR_VAR resource = EVAL ~%res%~ END
      END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 2 power = 3 parameter1 = 187 parameter2 = 5 timing = 1 resist_dispel = 1 STR_VAR resource = cdid325c END // extra dam for class: fire elemental
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 2 power = 3 parameter1 = 146 parameter2 = 5 timing = 1 resist_dispel = 1 STR_VAR resource = cdid325c END // extra dam for class: winter wolf
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 2 duration = 6 STR_VAR resource = cdid325 END

    COPY ~iwdification/bam/cdid325v.bam~ ~override/cdibacld.bam~
         ~iwdification/eff/cdid325c.eff~ ~override~

  END

END

/////                                                  \\\\\
///// CLERIC_MOLD_TOUCH                                \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_MOLD_TOUCH~) OR override_divine)) BEGIN

  ADD_SPELL ~iwdification/spl/cdid326.spl~ 1 3 CLERIC_MOLD_TOUCH
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4150 // name
    SAY 0x50 @4151 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid326 resource = EVAL ~%DEST_RES%~ END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid326.itm~
    SAY 0x0c @4150
    SAY 0x54 @4151
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) range = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/bam/cdid326a.bam~ ~override~
       ~iwdification/bam/cdid326b.bam~ ~override~
       ~iwdification/bam/cdid326c.bam~ ~override~
       ~iwdification/bam/cdimoldt.bam~ ~override~
       ~iwdification/vvc/cdimoldt.vvc~ ~override~
       ~iwdification/wav/cdiep107.wav~ ~override~

END

/////                                                  \\\\\
///// CLERIC_STORM_SHELL                               \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_STORM_SHELL~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4160) STR_VAR bam_file = cdid327d RET icon END

  ADD_SPELL ~iwdification/spl/cdid327.spl~ 1 3 CLERIC_STORM_SHELL
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4160 // name
    SAY 0x50 @4161 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 140 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 140 END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid327.itm~
    SAY 0x0c @4160
    SAY 0x54 @4161
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 5 range = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/bam/cdid327a.bam~ ~override~
       ~iwdification/bam/cdid327b.bam~ ~override~
       ~iwdification/bam/cdid327c.bam~ ~override~
       ~iwdification/bam/cdid327d.bam~ ~override~
       ~iwdification/bam/cdisshel.bam~ ~override~
       ~iwdification/vvc/cdistorm.vvc~ ~override~
       ~iwdification/wav/cdiafp25.wav~ ~override~

END

/////                                                  \\\\\
///// CLERIC_CAUSE_MEDIUM_WOUNDS                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_CAUSE_MEDIUM_WOUNDS~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid330.spl~ 1 3 CLERIC_CAUSE_MEDIUM_WOUNDS
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4170 // name
    SAY 0x50 @4171 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid330 resource = EVAL ~%DEST_RES%~ END
    PATCH_IF !ee_game BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixd330 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixd330 END // general = undead
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 104 opcode = 177                  parameter2 = 4 STR_VAR resource = cdixd330 END // race = parameter1
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid330.itm~
    SAY 0x0c @4170
    SAY 0x54 @4171
    LPF cd_scroll INT_VAR unusable0 = (BIT2 + BIT12 + BIT21 + BIT30) range = 1 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // non-good cleric

  COPY ~iwdification/bam/cdid330a.bam~ ~override~
       ~iwdification/bam/cdid330b.bam~ ~override~
       ~iwdification/bam/cdid330c.bam~ ~override~
       ~iwdification/bam/cdicmdam.bam~ ~override~
       ~iwdification/vvc/cdicmdam.vvc~ ~override~
       ~iwdification/wav/cdiem103.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd330.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_FAVOR_OF_ILMATER                          \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_FAVOR_OF_ILMATER~) OR override_divine)) BEGIN

  ADD_SPELL ~iwdification/spl/cdid331.spl~ 1 3 CLERIC_FAVOR_OF_ILMATER
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4180 // name
    SAY 0x50 @4181 // descript
    LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = sppr315 resource = EVAL ~%DEST_RES%~ END // iwdee nightly has bug here
    LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdid331 resource = EVAL ~%DEST_RES%~ END // for when bug is fixed

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid331.itm~
    SAY 0x0c @4180
    SAY 0x54 @4181
    LPF cd_scroll INT_VAR unusable0 = (BIT1 + BIT12 + BIT21 + BIT30) range = 1 opcode = 146 target_eff = 2 price = 300 STR_VAR spell = EVAL ~%current_spell_res%~ END // non-evil cleric

  COPY ~iwdification/bam/cdid331a.bam~ ~override~
       ~iwdification/bam/cdid331b.bam~ ~override~
       ~iwdification/bam/cdid331c.bam~ ~override~
       ~iwdification/bam/cdicmdam.bam~ ~override~
       ~iwdification/bam/cdicmwou.bam~ ~override~
       ~iwdification/vvc/cdicmdam.vvc~ ~override~
       ~iwdification/vvc/cdicmwou.vvc~ ~override~
       ~iwdification/wav/cdiem103.wav~ ~override~
       ~iwdification/wav/cdiep26.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_GIANT_INSECT                              \\\\\
/////                                                  \\\\\

ACTION_IF (anim_beetle AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_GIANT_INSECT~) OR override_divine)) BEGIN // requires beetle animation, either EE or vanilla + infinity animations

  ADD_PROJECTILE ~iwdification/pro/cdi282.pro~

  LAF cd_new_summon_table STR_VAR descript = "Giant_insect" 2da_file = cdiinsct RET table END

  ADD_SPELL ~iwdification/spl/cdid418.spl~ 1 4 CLERIC_GIANT_INSECT
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4190 // name
    SAY 0x50 @4191 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 parameter2 = table END
    END ELSE BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 215 parameter2 = 2 STR_VAR resource = cdimsm1h END
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0 probability1 = 49 dicesize = 0 dicenumber = 0 STR_VAR resource = cdiinsct END
      LPF CLONE_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0                   dicesize = 0 dicenumber = 0 STR_VAR resource = cdiinsct END
      LPF ALTER_EFFECT INT_VAR match_opcode = 331 opcode = 127 parameter1 = 1 parameter2 = 0                   dicesize = 0 dicenumber = 0 STR_VAR resource = cdiinsct END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid418.itm~
    SAY 0x0c @4190
    SAY 0x54 @4191
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 opcode = 148 target_eff = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid
    
  COPY_EXISTING ~cdi282.pro~ ~override~
    SAY 0x30 @4193
    
  COMPILE ~iwdification/baf/cdibbcld.baf~

  COPY ~iwdification/spl/cdibombb.spl~ ~override~
    SAY 0xce @4193
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi282 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 35568 parameter1 = string_stunned END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14073 parameter1 = string_deafness END

  LAF cd_animation STR_VAR code = e220 END // 57888 MBBM beetle_black
  COPY ~iwdification/cre/cdiibomb.cre~ ~override~
    SAY 0x08 @4192
    SAY 0x0c @4192
    WRITE_LONG 0x28 anim_beetle
  
  COPY ~iwdification/cre/cdiiborb.cre~ ~override~
    SAY 0x08 @3013
    SAY 0x0c @3013
    WRITE_LONG 0x28 anim_beetle
  
  COPY ~iwdification/itm/cdis5-20.itm~ ~override~
    WRITE_LONG 0x08 string_attack
    WRITE_LONG 0x0c string_attack
  
  COPY ~iwdification/itm/cdifring.itm~ ~override~
    LPF ALTER_EFFECT STR_VAR match_resource = spin191 resource = cdibombb END

  COPY ~iwdification/bam/cdid418a.bam~ ~override~
       ~iwdification/bam/cdid418b.bam~ ~override~
       ~iwdification/bam/cdid418c.bam~ ~override~
       ~iwdification/bam/cdiasm1x.bam~ ~override~
       ~iwdification/bam/cdimsm1h.bam~ ~override~
       ~iwdification/bam/cdisclda.bam~ ~override~
       ~iwdification/bam/cdiscldr.bam~ ~override~
       ~iwdification/vvc/cdiasm1x.vvc~ ~override~
       ~iwdification/vvc/cdimsm1h.vvc~ ~override~
       ~iwdification/wav/cdiem47.wav~  ~override~

  COPY ~iwdification/2da/cdiinsct.2da~ ~override~
    PATCH_IF !ee_game BEGIN// delete 2nd & 3rd columns for vanilla summon tables
      REPLACE_TEXTUALLY ~[ %TAB%]+HitAnimation[ %TAB%]+AreaHitAnimation~ ~~
      REPLACE_TEXTUALLY ~[ %TAB%]+cdimsm1h[ %TAB%]+.+$~ ~~
    END

END

/////                                                  \\\\\
///// CLERIC_PRODUCE_FIRE                              \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_PRODUCE_FIRE~) OR override_divine) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi215.pro~

  ADD_SPELL ~iwdification/spl/cdid419.spl~ 1 4 CLERIC_PRODUCE_FIRE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4200 // name
    SAY 0x50 @4201 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi215 END
    LPF ALTER_EFFECT STR_VAR match_resource = cdid419 resource = EVAL ~%DEST_RES%~ END
    PATCH_IF !ee_game BEGIN
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 215 target = 1 parameter2 = 2 timing = 1 resist_dispel = 3 STR_VAR resource = cdiprfir END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid419.itm~
    SAY 0x0c @4200
    SAY 0x54 @4201
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 40 opcode = 148 target_eff = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/bam/cdid419a.bam~ ~override~
       ~iwdification/bam/cdid419b.bam~ ~override~
       ~iwdification/bam/cdid419c.bam~ ~override~
       ~iwdification/bam/cdipfira.bam~ ~override~
       ~iwdification/bam/cdipfirx.bam~ ~override~
       ~iwdification/vvc/cdiprfir.vvc~ ~override~
       ~iwdification/wav/cdiarp03.wav~ ~override~
       ~iwdification/wav/cdiep45.wav~  ~override~

  ACTION_IF !ee_game BEGIN
    
    COPY_EXISTING ~cdi215.pro~ ~override~
      WRITE_BYTE 0x217 255
  
  END

END

/////                                                  \\\\\
///// CLERIC_STATIC_CHARGE                             \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_STATIC_CHARGE~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4210) STR_VAR bam_file = cdid420d RET icon END

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdistatc.pro~
  
  END

  ADD_SPELL ~iwdification/spl/cdid420.spl~ 1 4 CLERIC_STATIC_CHARGE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4210 // name
    SAY 0x50 @4211 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid420 resource = EVAL ~%DEST_RES%~ END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 333 STR_VAR resource = cdid420b END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 42 parameter2 = icon END
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR target = 1 projectile = 1 range = 30 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 42 END
      LPF ALTER_EFFECT INT_VAR target = 2 dicenumber = 0 dicesize = 0 END
      LPF CD_CONVERT_333 STR_VAR 333spell = cdid420b END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid420.itm~
    SAY 0x0c @4210
    SAY 0x54 @4211
    PATCH_IF ee_game BEGIN
      LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 5 range = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid
    END ELSE BEGIN
      LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 1 range = 30 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid
    END

  COPY ~iwdification/spl/cdid420b.spl~ ~override~
    SAY 0x9e @4212
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdistatc END
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR target = 1 projectile = 1 range = 30 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 12 dicenumber = 4 dicesize = 8 special = 0 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 12 dicenumber = 5 savingthrow = 0 END
      LPF CD_EXTEND-O-MATIC INT_VAR base_dur = 0 step_dur = 0 level_cap = 20 min_lev_alt = 7 END
      READ_SHORT 0x68 abil_num
      FOR (index = 0 ; index < abil_num ; ++index) BEGIN
        LPF ALTER_EFFECT INT_VAR header = index match_opcode = 12 match_savingthrow = 0    dicenumber = ((index +  9) / 2) END
        LPF ALTER_EFFECT INT_VAR header = index match_opcode = 12 match_savingthrow = BIT0 dicenumber = ((index + 10) / 2) END
      END
    END

  COPY ~iwdification/bam/cdid420a.bam~ ~override~
       ~iwdification/bam/cdid420b.bam~ ~override~
       ~iwdification/bam/cdid420c.bam~ ~override~
       ~iwdification/bam/cdid420d.bam~ ~override~
       ~iwdification/bam/cdistath.bam~ ~override~
       ~iwdification/vvc/cdistath.vvc~ ~override~
       ~iwdification/wav/cdiep42.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_RECITATION                                \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_RECITATION~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4220) STR_VAR bam_file = cdid316d RET icon END

  ADD_PROJECTILE ~iwdification/pro/cdivrnp.pro~
  ADD_PROJECTILE ~iwdification/pro/cdivrpo.pro~

  ADD_SPELL ~iwdification/spl/cdid421.spl~ 1 4 CLERIC_RECITATION
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4220 // name
    SAY 0x50 @4221 // descript

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid421.itm~
    SAY 0x0c @4220
    SAY 0x54 @4221
    LPF cd_scroll INT_VAR unusable0 = (BIT12 + BIT21 + BIT30) target_hdr = 5 range = 40 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // cleric

  COPY ~iwdification/spl/cdid421b.spl~ ~override~
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdivrnp END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 40257 parameter1 = RESOLVE_STR_REF(@4082) END
    PATCH_IF !ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = cdid421b END
      LPF CD_CONVERT_9_255 END
    END

  COPY ~iwdification/spl/cdid421g.spl~ ~override~
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdivrpo END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 40256 parameter1 = RESOLVE_STR_REF(@4083) END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 175 parameter2 = icon END
    END ELSE BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 175 parameter2 = 18 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = cdid421g END
      LPF CD_CONVERT_9_255 END
    END

  COPY ~iwdification/bam/cdid421a.bam~ ~override~
       ~iwdification/bam/cdid421b.bam~ ~override~
       ~iwdification/bam/cdid421c.bam~ ~override~
       ~iwdification/bam/cdid316d.bam~ ~override~
       ~iwdification/bam/cdirecih.bam~ ~override~
       ~iwdification/vvc/cdirecig.vvc~ ~override~
       ~iwdification/vvc/cdirecih.vvc~ ~override~
       ~iwdification/wav/cdiep44.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_BLOOD_RAGE                                \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_BLOOD_RAGE~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4230) STR_VAR bam_file = cdid422d RET icon END

  ADD_SPELL ~iwdification/spl/cdid422.spl~ 1 4 CLERIC_BLOOD_RAGE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4230 // name
    SAY 0x50 @4231 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid422 resource = EVAL ~%DEST_RES%~ END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 =  1280 parameter1 = string_stunned END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14022 parameter1 = string_healed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14043 parameter1 = string_stun END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14102 parameter1 = string_held END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 17392 parameter1 = string_dcharmed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 20568 parameter1 = string_mf_panic END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35473 parameter1 = string_healed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35484 parameter1 = string_panic END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35542 parameter1 = string_paralyzed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35544 parameter1 = string_dominated END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35606 parameter1 = string_held END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37340 parameter1 = string_uncon END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37603 parameter1 = string_rthinking END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37604 parameter1 = string_confused END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37613 parameter1 = string_sleep END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37801 parameter1 = string_charmed END
    PATCH_IF ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 318 STR_VAR match_resource = cdid422 END // should be last
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 176 parameter2 = icon END
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 opcode = 318 match_parameter2 = 50 parameter2 = 0 STR_VAR insert = last END // reinserting as last
    END ELSE BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 opcode = 206 match_parameter2 = 50 parameter2 = 0 STR_VAR insert = last END // reinserting as last
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 328 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 318 opcode = 206 parameter1 = 0 parameter2 = 0 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 176 parameter2 = 4 END
      PATCH_FOR_EACH ea IN 0 1 28 29 30 31 126 128 199 200 201 202 254 255 BEGIN // all ea values except charmed, controlled, ally, familiar, pc
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 2 power = 4 parameter1 = ea parameter2 = 2 resist_dispel = 3 duration = 120 insert_point = 0 STR_VAR resource = cdixd422 END
      END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 2 power = 4 parameter1 = 16 parameter2 = 8 resist_dispel = 3 duration = 120 insert_point = 0 STR_VAR resource = cdixd422 END // lawful
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid422.itm~
    SAY 0x0c @4230
    SAY 0x54 @4231
    LPF cd_scroll INT_VAR unusable0 = (BIT4 + BIT12 + BIT21 + BIT30) price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // non-lawful cleric

  COPY ~iwdification/bam/cdid422a.bam~ ~override~
       ~iwdification/bam/cdid422b.bam~ ~override~
       ~iwdification/bam/cdid422c.bam~ ~override~
       ~iwdification/bam/cdid422d.bam~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd422.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_CLOUD_OF_PESTILENCE                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_CLOUD_OF_PESTILENCE~) OR override_divine) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi309.pro~

  END ELSE BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi309a.pro~

  END

  ADD_SPELL ~iwdification/spl/cdid423.spl~ 1 4 CLERIC_CLOUD_OF_PESTILENCE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4240 // name
    SAY 0x50 @4241 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi309 END
      LPF ALTER_EFFECT STR_VAR match_resource = cdid423 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37800 parameter1 = string_blinded END
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi309a END
      LPF DELETE_EFFECT END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 timing = 1 parameter2 = 2 STR_VAR resource = cdid423 END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 duration = 24 STR_VAR resource = cdid423 END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid423.itm~
    SAY 0x0c @4240
    SAY 0x54 @4241
    LPF cd_scroll INT_VAR unusable0 = (BIT2 + BIT3 + BIT12 + BIT21 + BIT30) target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // evil cleric

  COPY ~iwdification/bam/cdid423a.bam~ ~override~
       ~iwdification/bam/cdid423b.bam~ ~override~
       ~iwdification/bam/cdid423c.bam~ ~override~
       ~iwdification/bam/cdicopes.bam~ ~override~
       ~iwdification/wav/cdiarp25.wav~ ~override~

  ACTION_IF ee_game BEGIN

    APPEND ~clearair.2da~ ~Cloud_of_Pest %cdi309%~

  END ELSE BEGIN

    APPEND ~clearair.2da~ ~Cloud_of_Pest %cdi309a%~
  
    LAUNCH_ACTION_FUNCTION cd_create_cloud INT_VAR visloop = 9 cloud_dur = 24 zosa = 1 STR_VAR code = cdid423 anim = cdicopes END

    COPY ~iwdification/spl/cdid423.spl~ ~override~
      WRITE_LONG 0x08 "-1" // name
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi309a END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 2 duration = 6 STR_VAR resource = cdid423 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 318 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 39 END // class = paladin, but bg2 paladins don't have disease immunity
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37800 parameter1 = string_blinded END
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  9 opcode = 177 parameter1 = 145 parameter2 = 4 STR_VAR resource = cdixd423 END // race = elemental
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 27 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixd423 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  1 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixd423 END // general = undead

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd423.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_UNFAILING_ENDURANCE                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_UNFAILING_ENDURANCE~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid424.spl~ 1 4 CLERIC_UNFAILING_ENDURANCE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4250 // name
    SAY 0x50 @4251 // descript

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid424.itm~
    SAY 0x0c @4250
    SAY 0x54 @4251
    LPF cd_scroll INT_VAR unusable0 = (BIT12 + BIT21 + BIT30) range = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // cleric

  COPY ~iwdification/bam/cdid424a.bam~ ~override~
       ~iwdification/bam/cdid424b.bam~ ~override~
       ~iwdification/bam/cdid424c.bam~ ~override~
       ~iwdification/bam/cdinecro.bam~ ~override~
       ~iwdification/vvc/cdinecro.vvc~ ~override~
       ~iwdification/wav/cdiep112.wav~ ~override~

END

/////                                                  \\\\\
///// CLERIC_STAR_METAL_CUDGEL                         \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_STAR_METAL_CUDGEL~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid425.spl~ 1 4 CLERIC_STAR_METAL_CUDGEL
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4260 // name
    SAY 0x50 @4261 // descript

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid425.itm~
    SAY 0x0c @4260
    SAY 0x54 @4261
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 5 range = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/itm/cdismcud.itm~ ~override~
    SAY 0x08 @4260
    SAY 0x0c @4260

  COPY ~iwdification/bam/cdid425a.bam~ ~override~
       ~iwdification/bam/cdid425b.bam~ ~override~
       ~iwdification/bam/cdid425c.bam~ ~override~
       ~iwdification/bam/cdiconju.bam~ ~override~
       ~iwdification/bam/cdismcud.bam~ ~override~
       ~iwdification/eff/cdismcud.eff~ ~override~
       ~iwdification/vvc/cdiconju.vvc~ ~override~
       ~iwdification/wav/cdiep02.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_SMASHING_WAVE                             \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_SMASHING_WAVE~) OR override_divine)) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdiswave.pro~

  ADD_SPELL ~iwdification/spl/cdid426.spl~ 1 4 CLERIC_SMASHING_WAVE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4270 // name
    SAY 0x50 @4271 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdiswave END
    LPF ALTER_EFFECT STR_VAR match_resource = cdid426 resource = EVAL ~%DEST_RES%~ END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 35568 parameter1 = string_stunned END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37340 parameter1 = string_uncon END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 20438 parameter1 = string_uncon END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid426.itm~
    SAY 0x0c @4270
    SAY 0x54 @4271
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/bam/cdid426a.bam~ ~override~
       ~iwdification/bam/cdid426b.bam~ ~override~
       ~iwdification/bam/cdid426c.bam~ ~override~
       ~iwdification/bam/cdiswavh.bam~ ~override~
       ~iwdification/bam/cdiswavx.bam~ ~override~
       ~iwdification/vvc/cdiswavh.vvc~ ~override~
       ~iwdification/wav/cdiep110.wav~ ~override~
       ~iwdification/wav/cditra56.wav~ ~override~

END

/////                                                  \\\\\
///// CLERIC_THORN_SPRAY                               \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_THORN_SPRAY~) OR override_divine) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi303.pro~

  ADD_SPELL ~iwdification/spl/cdid427.spl~ 1 4 CLERIC_THORN_SPRAY
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4280 // name
    SAY 0x50 @4281 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi303 END
    PATCH_IF !ee_game BEGIN
      LPF CD_SPLIT_SAVE_DAMAGE END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid427.itm~
    SAY 0x0c @4280
    SAY 0x54 @4281
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 30 opcode = 148 target_eff = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/bam/cdid427a.bam~ ~override~
       ~iwdification/bam/cdid427b.bam~ ~override~
       ~iwdification/bam/cdid427c.bam~ ~override~
       ~iwdification/bam/cditspra.bam~ ~override~
       ~iwdification/wav/cditra61.wav~ ~override~

  ACTION_IF !ee_game BEGIN
    
    COPY_EXISTING ~cdi303.pro~ ~override~
      WRITE_BYTE 0x217 11 // re-use cone of cold
      WRITE_BYTE 0x218 0
  
  END

END

/////                                                  \\\\\
///// CLERIC_WALL_OF_MOONLIGHT                         \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_WALL_OF_MOONLIGHT~) OR override_divine)) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdiwallm.pro~

  ADD_SPELL ~iwdification/spl/cdid428.spl~ 1 4 CLERIC_WALL_OF_MOONLIGHT
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4290 // name
    SAY 0x50 @4291 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdiwallm END
    LPF ALTER_EFFECT STR_VAR match_resource = cdid428 resource = EVAL ~%DEST_RES%~ END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid428.itm~
    SAY 0x0c @4290
    SAY 0x54 @4291
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 400 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/bam/cdid428a.bam~ ~override~
       ~iwdification/bam/cdid428b.bam~ ~override~
       ~iwdification/bam/cdid428c.bam~ ~override~
       ~iwdification/bam/cdimoonx.bam~ ~override~
       ~iwdification/spl/cdid428a.spl~ ~override~
       ~iwdification/spl/cdid428b.spl~ ~override~
       ~iwdification/vvc/cdimoonx.vvc~ ~override~
       ~iwdification/wav/cdiafp21.wav~ ~override~
       ~iwdification/wav/cdiarp22.wav~ ~override~

END

/////                                                  \\\\\
///// CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL           \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4300) STR_VAR bam_file = cdid316d RET icon END

  ADD_PROJECTILE ~iwdification/pro/cdi266.pro~

  ADD_SPELL ~iwdification/spl/cdid518.spl~ 1 5 CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4300 // name
    SAY 0x50 @4301 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi266 END
    PATCH_IF !ee_game BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 318 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = cdirwf00 END
      PATCH_FOR_EACH align IN 17 18 19 33 34 35 49 50 51 BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 power = 5 parameter1 = align parameter2 = 8 timing = 1 resist_dispel = 3 STR_VAR resource = EVAL ~cdirwf%align%~ END
      END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid518.itm~
    SAY 0x0c @4300
    SAY 0x54 @4301
    LPF cd_scroll INT_VAR unusable0 = (BIT12 + BIT21 + BIT30) target_hdr = 5 range = 40 price = 500 STR_VAR spell = EVAL ~%current_spell_res%~ END // cleric

  COPY ~iwdification/spl/cdirwf00.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 17392 parameter1 = string_dcharmed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35542 parameter1 = string_paralyzed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35544 parameter1 = string_dominated END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35606 parameter1 = string_held END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 36035 parameter1 = string_hasted END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37801 parameter1 = string_charmed END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 184 parameter2 = icon END
    END ELSE BEGIN // in non-ee, characters will get 00 AND 99 if matching alignment, so need to strip out anything already covered in 99
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 184 END
      PATCH_FOR_EACH op IN 321 8 174 215 18 93 BEGIN // cosmetics, sound, fatigue, hp bonus
        LPF DELETE_EFFECT INT_VAR match_opcode = op END
      END
      PATCH_FOR_EACH op IN 54 33 34 35 36 37 BEGIN // already get +1 from 99, so only bump another +1 here
        LPF ALTER_EFFECT INT_VAR match_opcode = op parameter1 = 1 END
      END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = cdirwf00 END
    END

  COPY ~iwdification/spl/cdirwf99.spl~ ~override~
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 184 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 184 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = cdirwf99 END
      LPF CD_CONVERT_9_255 END
    END

  COPY ~iwdification/bam/cdid518a.bam~ ~override~
       ~iwdification/bam/cdid518b.bam~ ~override~
       ~iwdification/bam/cdid518c.bam~ ~override~
       ~iwdification/bam/cdid316d.bam~ ~override~
       ~iwdification/bam/cdiabjux.bam~ ~override~
       ~iwdification/bam/cdirwtfh.bam~ ~override~
       ~iwdification/vvc/cdigabju.vvc~ ~override~
       ~iwdification/vvc/cdirwtfg.vvc~ ~override~
       ~iwdification/vvc/cdirwtfh.vvc~ ~override~
       ~iwdification/wav/cdiarm20.wav~ ~override~
       ~iwdification/wav/cdiee01.wav~  ~override~
       ~iwdification/wav/cdiep36.wav~  ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/cdirwf17.eff~ ~override/cdirwf00.eff~
      WRITE_ASCIIE 0x30 ~cdirwf00~

    ACTION_FOR_EACH align IN 17 18 19 33 34 35 49 50 51 BEGIN

      COPY ~iwdification/eff/cdirwf17.eff~ ~override/cdirwf%align%.eff~
        WRITE_ASCIIE 0x30 ~cdirwf%align%~

      COPY ~iwdification/spl/cdirwf17.spl~ ~override/cdirwf%align%.spl~
        WRITE_LONG 0x9e align
        LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi266 END
    
    END
  
  END

END

/////                                                  \\\\\
///// CLERIC_SPIKE_STONES                              \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_SPIKE_STONES~) OR override_divine) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi213.pro~
  
  END ELSE BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi213a.pro~

  END

  ADD_SPELL ~iwdification/spl/cdid519.spl~ 1 5 CLERIC_SPIKE_STONES
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4310 // name
    SAY 0x50 @4311 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi213 END
      LPF DELETE_EFFECT STR_VAR match_resource = ~#sston~ END
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi213a END
      LPF DELETE_EFFECT END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 timing = 1 parameter2 = 2 STR_VAR resource = cdid519 END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid519.itm~
    SAY 0x0c @4310
    SAY 0x54 @4311
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 40 opcode = 148 target_eff = 1 price = 1500 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid only

  COPY ~iwdification/bam/cdid519a.bam~ ~override~
       ~iwdification/bam/cdid519b.bam~ ~override~
       ~iwdification/bam/cdid519c.bam~ ~override~
       ~iwdification/bam/cdistone.bam~ ~override~
       ~iwdification/vvc/cdistone.vvc~ ~override~
       ~iwdification/wav/cdiarp04.wav~ ~override~
       ~iwdification/wav/cdicp03.wav~  ~override~
       ~iwdification/wav/cdiep48.wav~  ~override~

  ACTION_IF ee_game BEGIN

    COPY ~iwdification/vvc/cdistone.vvc~ ~override~
    
  END ELSE BEGIN
  
    LAUNCH_ACTION_FUNCTION cd_create_cloud INT_VAR visloop = 5 cloud_dur = 72 STR_VAR code = cdid519 anim = cdistone END

    COPY ~iwdification/spl/cdid519.spl~ ~override~
      WRITE_LONG 0x08 "-1" // name
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi213a END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 2 duration = 6 STR_VAR resource = cdid519 END

  END

END

/////                                                  \\\\\
///// CLERIC_SHIELD_OF_LATHANDER                       \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_SHIELD_OF_LATHANDER~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4320) STR_VAR bam_file = cdid520d RET icon END

  ADD_SPELL ~iwdification/spl/cdid520.spl~ 1 5 CLERIC_SHIELD_OF_LATHANDER
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4320 // name
    SAY 0x50 @4321 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 STR_VAR resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 164 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 164 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 opcode = 177 parameter1 = 3 parameter2 = 8 STR_VAR resource = cdixd520 END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid520.itm~
    SAY 0x0c @4320
    SAY 0x54 @4321
    LPF cd_scroll INT_VAR unusable0 = (BIT1 + BIT12 + BIT21 + BIT30) range = 1 price = 500 STR_VAR spell = EVAL ~%current_spell_res%~ END // non-evil cleric

  COPY ~iwdification/bam/cdid520a.bam~ ~override~
       ~iwdification/bam/cdid520b.bam~ ~override~
       ~iwdification/bam/cdid520c.bam~ ~override~
       ~iwdification/bam/cdid520d.bam~ ~override~
       ~iwdification/bam/cdisol1.bam~  ~override~
       ~iwdification/bam/cdisol2.bam~  ~override~
       ~iwdification/vvc/cdilatl1.vvc~ ~override~
       ~iwdification/vvc/cdilatl2.vvc~ ~override~
       ~iwdification/wav/cdiafp20.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd520.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_UNDEAD_WARD                               \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_UNDEAD_WARD~) OR override_divine) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdiuward.pro~

  END ELSE BEGIN
    
    OUTER_SET cdiuward = 1

  END

  ADD_SPELL ~iwdification/spl/cdid521.spl~ 1 5 CLERIC_UNDEAD_WARD
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4330 // name
    SAY 0x50 @4331 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdiuward END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdid521 resource = EVAL ~%DEST_RES%~ END
    END ELSE BEGIN
      LPF DELETE_EFFECT END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 215 target = 1 power = 5                resist_dispel = 2 duration = 60 STR_VAR resource = cdiuwrdx END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 power = 5 parameter2 = 2 resist_dispel = 2 duration = 60 END
      LPF CD_EXTEND-O-MATIC INT_VAR base_dur = 60 step_dur = 0 level_cap = 30 min_lev_alt = 9 END
      READ_SHORT 0x68 abil_num
      FOR (index = 9 ; index < (abil_num + 9) ; ++index) BEGIN
        LPF ALTER_EFFECT INT_VAR header = (index - 9) match_opcode = 177 STR_VAR resource = EVAL ~cdiuwr%index%~ END
      END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid521.itm~
    SAY 0x0c @4330
    SAY 0x54 @4331
    LPF cd_scroll INT_VAR unusable0 = (BIT12 + BIT21 + BIT30) target_hdr = 5 range = 1 price = 500 STR_VAR spell = EVAL ~%current_spell_res%~ END // cleric

  COPY ~iwdification/bam/cdid521a.bam~ ~override~
       ~iwdification/bam/cdid521b.bam~ ~override~
       ~iwdification/bam/cdid521c.bam~ ~override~
       ~iwdification/bam/cdiuwrdx.bam~ ~override~
       ~iwdification/vvc/cdiuwrdx.vvc~ ~override~
       ~iwdification/wav/cdiafp27.wav~ ~override~
       ~iwdification/wav/cdiarp28.wav~ ~override~
       
  ACTION_IF !ee_game BEGIN

    COMPILE ~iwdification/baf/cdid521.baf~

    OUTER_FOR (index = 9 ; index < 31 ; ++index) BEGIN

      COPY ~iwdification/eff/cdiuwr9.eff~ ~override/cdiuwr%index%.eff~
        WRITE_ASCIIE 0x30 "%DEST_RES%" #8

      COPY ~iwdification/cre/cdiuwr9.cre~ ~override/cdiuwr%index%.cre~
        WRITE_BYTE 0x234 index
        
    END

  END

END

/////                                                  \\\\\
///// CLERIC_ANIMAL_RAGE                               \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_ANIMAL_RAGE~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4340) STR_VAR bam_file = cdid522d RET icon END

  ADD_SPELL ~iwdification/spl/cdid522.spl~ 1 5 CLERIC_ANIMAL_RAGE
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4340 // name
    SAY 0x50 @4341 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdid522 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 173 parameter2 = icon END
      LPF ALTER_EFFECT INT_VAR match_opcode = 333 STR_VAR resource = cdid522b END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 173 parameter2 = 83 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 33 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = EVAL ~%DEST_RES%~ END
      LPF CD_CONVERT_333 STR_VAR 333spell = cdid522b END
      LPF CD_CONVERT_9_255 END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid522.itm~
    SAY 0x0c @4340
    SAY 0x54 @4341
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) range = 1 price = 500 STR_VAR spell = EVAL ~%current_spell_res%~ END // druid

  COPY ~iwdification/spl/cdid522b.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37605 parameter1 = string_berserk END

  COPY ~iwdification/bam/cdid522a.bam~ ~override~
       ~iwdification/bam/cdid522b.bam~ ~override~
       ~iwdification/bam/cdid522c.bam~ ~override~
       ~iwdification/bam/cdid522d.bam~ ~override~

END

/////                                                  \\\\\
///// CLERIC_MASS_CAUSE_LIGHT_WOUNDS                   \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_MASS_CAUSE_LIGHT_WOUNDS~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid523.spl~ 1 5 CLERIC_MASS_CAUSE_LIGHT_WOUNDS
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4350 // name
    SAY 0x50 @4351 // descript
    LPF ALTER_EFFECT STR_VAR match_resource = cdid523 resource = EVAL ~%DEST_RES%~ END
    PATCH_IF !ee_game BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixd523 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixd523 END // general = undead
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 104 opcode = 177                  parameter2 = 4 STR_VAR resource = cdixd523 END // race = parameter1
      LPF CD_SPLIT_SAVE_DAMAGE END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid523.itm~
    SAY 0x0c @4350
    SAY 0x54 @4351
    LPF cd_scroll INT_VAR unusable0 = (BIT2 + BIT3) target_hdr = 5 range = 20 price = 500 STR_VAR spell = EVAL ~%current_spell_res%~ END // evil only

  COPY ~iwdification/bam/cdid523a.bam~ ~override~
       ~iwdification/bam/cdid523b.bam~ ~override~
       ~iwdification/bam/cdid523c.bam~ ~override~
       ~iwdification/bam/cdicldam.bam~ ~override~
       ~iwdification/vvc/cdicldam.vvc~ ~override~
       ~iwdification/wav/cdiem103.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd523.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_ENTROPY_SHIELD                            \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_ENTROPY_SHIELD~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4360) STR_VAR bam_file = cdid615d RET icon END

  ADD_SPELL ~iwdification/spl/cdid615.spl~ 1 6 CLERIC_ENTROPY_SHIELD
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4360 // name
    SAY 0x50 @4361 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdid615 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 56 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 56 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 318 opcode = 206 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 30 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = EVAL ~%DEST_RES%~ END
      // iwdee/bgee/bg2ee/vanilla all match in projectiles until the 1pp slots for EE, so remove 1pp refs for vanilla (EEs all match, fortunately)
      FOR (index = 282 ; index < 319 ; ++index) BEGIN
        LPF DELETE_EFFECT INT_VAR match_opcode = 83 match_parameter2 = index END
      END
      PATCH_IF FILE_EXISTS_IN_GAME ~1arow01.pro~ BEGIN // if 1pp is installed, re-add the references manually since they still may not sync with EE
        PATCH_FOR_EACH proj IN // 1pp stuff
          1stafm0c 1arow01 1arow02 1arow03 1arow04 1arow05 1arow07 1arow10 1arow11 1arow15 1axe05 1axe08 1axe09 1axe10 1axe16 1bolt01 1bolt02 1bolt03 1bolt04
          1bolt05 1bolt06 1bolt09 1bull02 1bull03 1bull04 1bull05 1bull06 1dagg05 1dagg11 1dagg12 1dagg16 1dart01 1dart02 1dart03 1dart04 1dart05 1dart08
        BEGIN
          SET projids = IDS_OF_SYMBOL (~projectl~ ~%proj%~)
          PATCH_IF projids > 0 BEGIN
            LPF CLONE_EFFECT INT_VAR match_opcode = 83 match_parameter2 = 1 parameter2 = projids END
          END
        END
      END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid615.itm~
    SAY 0x0c @4360
    SAY 0x54 @4361
    LPF cd_scroll INT_VAR target_hdr = 5 range = 1 price = 600 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdid615a.bam~ ~override~
       ~iwdification/bam/cdid615b.bam~ ~override~
       ~iwdification/bam/cdid615c.bam~ ~override~
       ~iwdification/bam/cdid615d.bam~ ~override~
       ~iwdification/bam/cdiabjur.bam~ ~override~
       ~iwdification/bam/cdieshld.bam~ ~override~
       ~iwdification/vvc/cdiabjur.vvc~ ~override~
       ~iwdification/vvc/cdientro.vvc~ ~override~
       ~iwdification/wav/cdiafp03.wav~ ~override~

END

/////                                                  \\\\\
///// CLERIC_WHIRLWIND                                 \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_WHIRLWIND~) OR override_divine) BEGIN

  ACTION_IF ee_game BEGIN
  
    ADD_PROJECTILE ~iwdification/pro/cdiwhirl.pro~
    
  END ELSE BEGIN
  
    ADD_PROJECTILE ~iwdification/pro/cdiwhira.pro~

  END

  ADD_SPELL ~iwdification/spl/cdid617.spl~ 1 6 CLERIC_WHIRLWIND
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4370 // name
    SAY 0x50 @4371 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdiwhirl END
      LPF ALTER_EFFECT STR_VAR match_resource = cdid617 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 35568 parameter1 = string_stunned END
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
      LPF DELETE_EFFECT END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 resist_dispel = 2 duration = 120 STR_VAR resource = cdid617 END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid617.itm~
    SAY 0x0c @4370
    SAY 0x54 @4371
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 600 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdid617a.bam~ ~override~
       ~iwdification/bam/cdid617b.bam~ ~override~
       ~iwdification/bam/cdid617c.bam~ ~override~
       ~iwdification/bam/cdiwhirx.bam~ ~override~
       ~iwdification/wav/cdiep105.wav~ ~override~

  ACTION_IF !ee_game BEGIN  
  
    COPY ~iwdification/spl/cdid617.spl~ ~override/cdid617b.spl~
      WRITE_LONG 0x08 "-1"
      LPF DELETE_EFFECT INT_VAR match_opcode = 318 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 324 END
      LPF ALTER_EFFECT STR_VAR match_resource = cdid617 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 35568 parameter1 = string_stunned END
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdiwhira END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 265 target = 1 parameter1 = 1 timing = 1 insert_point = 0 STR_VAR resource = cdizosa END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 273 target = 1 timing = 1 resist_dispel = 3 insert_point = 0 STR_VAR resource = cdizosa END
      PATCH_FOR_EACH race IN 146 118 119 142 101 102 145 144 127 199 BEGIN // dragon, syverns, slimes, giants, ankheg, basilisk, elemental, golem, otyugh, ettin
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 2 parameter1 = race parameter2 = 4 duration = 1 insert_point = 0 STR_VAR resource = cdixd617 END
      END

    COMPILE ~iwdification/baf/cdid617.baf~

    COPY ~iwdification/cre/cdid617.cre~  ~override~
         ~iwdification/eff/cdid617.eff~  ~override~
         ~iwdification/eff/cdid617b.eff~ ~override~
         ~iwdification/vvc/cdiwhirx.vvc~ ~override~

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd617.eff~
      WRITE_ASCII 0x30 ~cdid617b~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_SPIRITUAL_WRATH                           \\\\\
/////                                                  \\\\\

ACTION_IF (ee_game AND (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_SPIRITUAL_WRATH~) OR override_divine)) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi207.pro~
  ADD_PROJECTILE ~iwdification/pro/cdi312.pro~

  ADD_SPELL ~iwdification/spl/cdid618.spl~ 1 6 CLERIC_SPIRITUAL_WRATH
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4380 // name
    SAY 0x50 @4381 // descript
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi312 END
    LPF ALTER_EFFECT STR_VAR match_resource = cdid618 resource = EVAL ~%DEST_RES%~ END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid618.itm~
    SAY 0x0c @4380
    SAY 0x54 @4381
    LPF cd_scroll INT_VAR unusable0 = (BIT12 + BIT21 + BIT30) target_hdr = 5 range = 100 price = 600 STR_VAR spell = EVAL ~%current_spell_res%~ END
    
  COPY_EXISTING ~cdi312.pro~ ~override~
    WRITE_SHORT 0x21a cdi207

  COPY ~iwdification/bam/cdid618a.bam~ ~override~
       ~iwdification/bam/cdid618b.bam~ ~override~
       ~iwdification/bam/cdid618c.bam~ ~override~
       ~iwdification/bam/cdiliten.bam~ ~override~
       ~iwdification/vvc/cdiinvoc.vvc~ ~override~
       ~iwdification/wav/cdiep05.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_SYMBOL_OF_PAIN                            \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_SYMBOL_OF_PAIN~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4393) STR_VAR bam_file = cdid714d RET icon END

  ADD_SPELL ~iwdification/spl/cdid714.spl~ 1 7 CLERIC_SYMBOL_OF_PAIN
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4390 // name
    SAY 0x50 @4391 // descript
    SAY 0x21e @4392
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdid714 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 169 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 328 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 206 parameter1 = 0 parameter2 = 0 STR_VAR insert = last resource = EVAL ~%DEST_RES%~ END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid714.itm~
    SAY 0x0c @4390
    SAY 0x54 @4391
    LPF cd_scroll INT_VAR unusable0 = (BIT12 + BIT21 + BIT30) target_hdr = 4 range = 35 opcode = 148 target_eff = 1 price = 700 STR_VAR spell = EVAL ~%current_spell_res%~ END // unusable by druid

  COPY ~iwdification/bam/cdid714a.bam~ ~override~
       ~iwdification/bam/cdid714b.bam~ ~override~
       ~iwdification/bam/cdid714c.bam~ ~override~
       ~iwdification/bam/cdid714d.bam~ ~override~
       ~iwdification/wav/cdiee04.wav~  ~override~
       ~iwdification/wav/cdiep02.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_SYMBOL_OF_HOPELESSNESS                    \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_SYMBOL_OF_HOPELESSNESS~) OR override_divine) BEGIN

  ADD_PROJECTILE ~iwdification/pro/cdi277.pro~

  ADD_SPELL ~iwdification/spl/cdid716.spl~ 1 7 CLERIC_SYMBOL_OF_HOPELESSNESS
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4400 // name
    SAY 0x50 @4401 // descript
    SAY 0x1be @3003
    LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi277 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 1280 parameter1 = string_stunned END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid716.itm~
    SAY 0x0c @4400
    SAY 0x54 @4401
    LPF cd_scroll INT_VAR unusable0 = (BIT12 + BIT21 + BIT30) target_hdr = 4 opcode = 148 target_eff = 1 price = 700 STR_VAR spell = EVAL ~%current_spell_res%~ END // cleric

  COPY ~iwdification/bam/cdid716a.bam~ ~override~
       ~iwdification/bam/cdid716b.bam~ ~override~
       ~iwdification/bam/cdid716c.bam~ ~override~
       ~iwdification/bam/cdiparal.bam~ ~override~
       ~iwdification/bam/cdishglp.bam~ ~override~
       ~iwdification/bam/cdisohx.bam~  ~override~
       ~iwdification/vvc/cdiparal.vvc~ ~override~
       ~iwdification/vvc/cdishglp.vvc~ ~override~
       ~iwdification/vvc/cdisohx.vvc~  ~override~
       ~iwdification/wav/cdiee04.wav~  ~override~
       ~iwdification/wav/cdiep02.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_IMPERVIOUS_SANCTITY_OF_MIND               \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_IMPERVIOUS_SANCTITY_OF_MIND~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4410) STR_VAR bam_file = cdid733d RET icon END

  ADD_SPELL ~iwdification/spl/cdid733.spl~ 1 7 CLERIC_IMPERVIOUS_SANCTITY_OF_MIND
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4410 // name
    SAY 0x50 @4411 // descript
    LPF ALTER_EFFECT INT_VAR match_opcode = 206 match_parameter1 = 4742 parameter1 = 0 END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37613 parameter1 = string_sleep END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37340 parameter1 = string_uncon END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37605 parameter1 = string_berserk END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35544 parameter1 = string_dominated END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 17392 parameter1 = string_dcharmed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37801 parameter1 = string_charmed END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 20568 parameter1 = string_mf_panic END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35484 parameter1 = string_panic END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37606 parameter1 = string_intoxicated END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37604 parameter1 = string_confused END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37603 parameter1 = string_rthinking END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 14102 parameter1 = string_held END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35606 parameter1 = string_held END
    LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35542 parameter1 = string_paralyzed END
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 170 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 170 END
      LPF DELETE_EFFECT INT_VAR match_opcode = 321 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 318 opcode = 206 parameter1 = 0 parameter2 = 0 END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid733.itm~
    SAY 0x0c @4410
    SAY 0x54 @4411
    LPF cd_scroll INT_VAR target_hdr = 5 price = 700 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdid733a.bam~ ~override~
       ~iwdification/bam/cdid733b.bam~ ~override~
       ~iwdification/bam/cdid733c.bam~ ~override~
       ~iwdification/bam/cdid733d.bam~ ~override~
       ~iwdification/bam/cdiabjur.bam~ ~override~
       ~iwdification/vvc/cdiabjur.vvc~ ~override~
       ~iwdification/wav/cdiee03.wav~  ~override~
       ~iwdification/wav/cdiep01.wav~  ~override~

END

/////                                                  \\\\\
///// CLERIC_DESTRUCTION                               \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_DESTRUCTION~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid734.spl~ 1 7 CLERIC_DESTRUCTION
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4420 // name
    SAY 0x50 @4421 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdid734 resource = EVAL ~%DEST_RES%~ END
    END ELSE BEGIN
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 opcode = 177 parameter1 = 4 parameter2 = 3 STR_VAR resource = cdixd734 END // undead are immune
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid734.itm~
    SAY 0x0c @4420
    SAY 0x54 @4421
    LPF cd_scroll INT_VAR unusable0 = (BIT2 + BIT3) range = 1 price = 700 STR_VAR spell = EVAL ~%current_spell_res%~ END // evil

  COPY ~iwdification/bam/cdid734a.bam~ ~override~
       ~iwdification/bam/cdid734b.bam~ ~override~
       ~iwdification/bam/cdid734c.bam~ ~override~
       ~iwdification/bam/cdidestr.bam~ ~override~
       ~iwdification/vvc/cdidestr.vvc~ ~override~
       ~iwdification/wav/cdiep113.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd734.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_GREATER_SHIELD_OF_LATHANDER               \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_GREATER_SHIELD_OF_LATHANDER~) OR override_divine) BEGIN

  LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@4430) STR_VAR bam_file = cdid735d RET icon END

  ADD_SPELL ~iwdification/spl/cdid735.spl~ 1 7 CLERIC_GREATER_SHIELD_OF_LATHANDER
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4430 // name
    SAY 0x50 @4431 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdid735 resource = EVAL ~%DEST_RES%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 165 parameter2 = icon END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 165 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 opcode = 177 parameter1 = 3 parameter2 = 8 STR_VAR resource = cdixd735 END // evil are immune
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid735.itm~
    SAY 0x0c @4430
    SAY 0x54 @4431
    LPF cd_scroll INT_VAR unusable0 = (BIT1 + BIT3 + BIT12 + BIT21 + BIT30) range = 1 price = 700 STR_VAR spell = EVAL ~%current_spell_res%~ END // good cleric

  COPY ~iwdification/bam/cdid735a.bam~ ~override~
       ~iwdification/bam/cdid735b.bam~ ~override~
       ~iwdification/bam/cdid735c.bam~ ~override~
       ~iwdification/bam/cdid735d.bam~ ~override~
       ~iwdification/bam/cdigsol1.bam~ ~override~
       ~iwdification/bam/cdigsol2.bam~ ~override~
       ~iwdification/vvc/cdilatg1.vvc~ ~override~
       ~iwdification/vvc/cdilatg2.vvc~ ~override~
       ~iwdification/wav/cdiafp26.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd735.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_MIST_OF_ELDATH                            \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_MIST_OF_ELDATH~) OR override_divine) BEGIN

  ACTION_IF ee_game BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi307.pro~
  
  END ELSE BEGIN

    ADD_PROJECTILE ~iwdification/pro/cdi307a.pro~

  END

  ADD_SPELL ~iwdification/spl/cdid736.spl~ 1 7 CLERIC_MIST_OF_ELDATH
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4440 // name
    SAY 0x50 @4441 // descript
    PATCH_IF ee_game BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi307 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14022 parameter1 = string_healed END
    END ELSE BEGIN
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi307a END
      LPF DELETE_EFFECT END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 timing = 1 parameter2 = 2 STR_VAR resource = cdid736 END
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid736.itm~
    SAY 0x0c @4440
    SAY 0x54 @4441
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 700 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdid736a.bam~ ~override~
       ~iwdification/bam/cdid736b.bam~ ~override~
       ~iwdification/bam/cdid736c.bam~ ~override~
       ~iwdification/bam/cdimoeld.bam~ ~override~
       ~iwdification/wav/cdiep104.wav~ ~override~

  ACTION_IF !ee_game BEGIN

    LAUNCH_ACTION_FUNCTION cd_create_cloud INT_VAR visloop = 7 cloud_dur = 6 zosa = 1 STR_VAR code = cdid736 anim = cdimoeld END

    COPY ~iwdification/spl/cdid736.spl~ ~override~
      WRITE_LONG 0x08 "-1" // name
      LPF ALTER_SPELL_HEADER INT_VAR projectile = cdi307a END
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14022 parameter1 = string_healed END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 2 duration = 6 STR_VAR resource = cdid736 END

  END

END

/////                                                  \\\\\
///// CLERIC_STALKER                                   \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_STALKER~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid737.spl~ 1 7 CLERIC_STALKER
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4450 // name
    SAY 0x50 @4451 // descript

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid737.itm~
    SAY 0x0c @4450
    SAY 0x54 @4451
    LPF cd_scroll INT_VAR unusable0 = (BIT7 + BIT8 + BIT9 + BIT14 + BIT15 + BIT20 + BIT29) target_hdr = 4 range = 100 opcode = 148 target_eff = 1 price = 700 STR_VAR spell = EVAL ~%current_spell_res%~ END
    
  COMPILE ~iwdification/baf/cdishamb.baf~  

  LAF cd_animation STR_VAR code = 7302 END // 29442 MEAE_SH shambling_mound
  COPY ~iwdification/cre/cdishamb.cre~ ~override~
    SAY 0x08 @4452
    SAY 0x0c @4452

  COPY ~iwdification/itm/cdishmbl.itm~ ~override~
    WRITE_LONG 0x08 string_attack
    WRITE_LONG 0x0c string_attack
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = shmblr resource = cdishmbl END
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37709 parameter1 = string_entangled savingthrow = BIT1 END
      LPF ALTER_EFFECT INT_VAR match_opcode = 12 savingthrow = BIT1 END
    END ELSE BEGIN
      LPF DELETE_EFFECT INT_VAR check_globals = 0 END
      LPF ADD_ITEM_EFFECT INT_VAR type = 1 opcode = 177 target = 2 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixd737 END // general = undead
      LPF ADD_ITEM_EFFECT INT_VAR type = 1 opcode = 177 target = 2 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixd737 END // race = golem
      LPF ADD_ITEM_EFFECT INT_VAR type = 1 opcode = 177 target = 2 parameter1 = 145 parameter2 = 4 STR_VAR resource = cdixd737 END // race = elemental
      LPF ADD_ITEM_EFFECT INT_VAR type = 1 opcode = 177 target = 2 parameter1 = 164 parameter2 = 4 STR_VAR resource = cdixd737 END // race = myconid
      LPF ADD_ITEM_EFFECT INT_VAR type = 1 opcode = 146 target = 2 parameter2 = 1 STR_VAR resource = cdishmbl END
    END

  COPY ~iwdification/bam/cdid737a.bam~ ~override~
       ~iwdification/bam/cdid737b.bam~ ~override~
       ~iwdification/bam/cdid737c.bam~ ~override~
       ~iwdification/bam/cdishmbl.bam~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/spl/cdishmbl.spl~ ~override~
      LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 37709 parameter1 = string_entangled END

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd737.eff~
      WRITE_ASCII 0x30 ~cdishmbl~ #8

  END

END

/////                                                  \\\\\
///// CLERIC_ENERGY_DRAIN                              \\\\\
/////                                                  \\\\\

ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~CLERIC_ENERGY_DRAIN~) OR override_divine) BEGIN

  ADD_SPELL ~iwdification/spl/cdid739.spl~ 1 7 CLERIC_ENERGY_DRAIN
    SPRINT current_spell_res "%DEST_RES%"
    SAY 0x08 @4460 // name
    SAY 0x50 @4461 // descript
    SAY 0x2ae @4462
    PATCH_IF ee_game BEGIN
      LPF ALTER_EFFECT STR_VAR match_resource = cdid739 resource = EVAL ~%DEST_RES%~ END
    END ELSE BEGIN
      LPF CLONE_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 = 144 parameter2 = 4 STR_VAR resource = cdixd739 END // race = golem
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 =  55 opcode = 177 parameter1 =   4 parameter2 = 3 STR_VAR resource = cdixd739 END // general = undead
      LPF ALTER_EFFECT INT_VAR match_opcode = 324 match_parameter2 = 104 opcode = 177                  parameter2 = 4 STR_VAR resource = cdixd739 END // race = parameter1
    END

  COPY ~iwdification/itm/blankpr.itm~ ~override/cdid739.itm~
    SAY 0x0c @4460
    SAY 0x54 @4461
    LPF cd_scroll INT_VAR unusable0 = (BIT2 + BIT3 + BIT12 + BIT21 + BIT30) range = 1 price = 700 STR_VAR spell = EVAL ~%current_spell_res%~ END

  COPY ~iwdification/bam/cdid739a.bam~ ~override~
       ~iwdification/bam/cdid739b.bam~ ~override~
       ~iwdification/bam/cdid739c.bam~ ~override~

  ACTION_IF !ee_game BEGIN

    COPY ~iwdification/eff/immunity.eff~ ~override/cdixd739.eff~
      WRITE_ASCIIE 0x30 ~%current_spell_res%~ #8

  END

END

/////                                                  \\\\\
///// joinable spellbook adjustments                   \\\\\
/////                                                  \\\\\

OUTER_SET NUM_d112 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_CURSE~)) - 1000)
OUTER_SET NUM_d114 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_CAUSE_LIGHT_WOUNDS~)) - 1000)
OUTER_SET NUM_d115 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_SUNSCORCH~)) - 1000)
OUTER_SET NUM_d217 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_CURE_MODERATE_WOUNDS~)) - 1000)
OUTER_SET NUM_d218 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_ALICORN_LANCE~)) - 1000)
OUTER_SET NUM_d219 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_BEAST_CLAW~)) - 1000)
OUTER_SET NUM_d220 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_CAUSE_MODERATE_WOUNDS~)) - 1000)
OUTER_SET NUM_d316 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_PRAYER~)) - 1000)
OUTER_SET NUM_d320 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_CAUSE_DISEASE~)) - 1000)
OUTER_SET NUM_d321 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_EXALTATION~)) - 1000)
OUTER_SET NUM_d322 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_MOONBLADE~)) - 1000)
OUTER_SET NUM_d323 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_CIRCLE_OF_BONES~)) - 1000)
OUTER_SET NUM_d324 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_SPIKE_GROWTH~)) - 1000)
OUTER_SET NUM_d325 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_CLOUDBURST~)) - 1000)
OUTER_SET NUM_d326 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_MOLD_TOUCH~)) - 1000)
OUTER_SET NUM_d327 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_STORM_SHELL~)) - 1000)
OUTER_SET NUM_d330 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_CAUSE_MEDIUM_WOUNDS~)) - 1000)
OUTER_SET NUM_d331 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_FAVOR_OF_ILMATER~)) - 1000)
OUTER_SET NUM_d418 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_GIANT_INSECT~)) - 1000)
OUTER_SET NUM_d419 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_PRODUCE_FIRE~)) - 1000)
OUTER_SET NUM_d420 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_STATIC_CHARGE~)) - 1000)
OUTER_SET NUM_d421 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_RECITATION~)) - 1000)
OUTER_SET NUM_d422 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_BLOOD_RAGE~)) - 1000)
OUTER_SET NUM_d423 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_CLOUD_OF_PESTILENCE~)) - 1000)
OUTER_SET NUM_d424 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_UNFAILING_ENDURANCE~)) - 1000)
OUTER_SET NUM_d425 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_STAR_METAL_CUDGEL~)) - 1000)
OUTER_SET NUM_d426 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_SMASHING_WAVE~)) - 1000)
OUTER_SET NUM_d427 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_THORN_SPRAY~)) - 1000)
OUTER_SET NUM_d428 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_WALL_OF_MOONLIGHT~)) - 1000)
OUTER_SET NUM_d518 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL~)) - 1000)
OUTER_SET NUM_d519 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_SPIKE_STONES~)) - 1000)
OUTER_SET NUM_d520 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_SHIELD_OF_LATHANDER~)) - 1000)
OUTER_SET NUM_d521 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_UNDEAD_WARD~)) - 1000)
OUTER_SET NUM_d522 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_ANIMAL_RAGE~)) - 1000)
OUTER_SET NUM_d523 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_MASS_CAUSE_LIGHT_WOUNDS~)) - 1000)
OUTER_SET NUM_d615 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_ENTROPY_SHIELD~)) - 1000)
OUTER_SET NUM_d617 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_WHIRLWIND~)) - 1000)
OUTER_SET NUM_d618 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_SPIRITUAL_WRATH~)) - 1000)
OUTER_SET NUM_d714 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_SYMBOL_OF_PAIN~)) - 1000)
OUTER_SET NUM_d716 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_SYMBOL_OF_HOPELESSNESS~)) - 1000)
OUTER_SET NUM_d733 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_IMPERVIOUS_SANCTITY_OF_MIND~)) - 1000)
OUTER_SET NUM_d734 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_DESTRUCTION~)) - 1000)
OUTER_SET NUM_d735 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_GREATER_SHIELD_OF_LATHANDER~)) - 1000)
OUTER_SET NUM_d736 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_MIST_OF_ELDATH~)) - 1000)
OUTER_SET NUM_d737 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_STALKER~)) - 1000)
OUTER_SET NUM_d739 = ((IDS_OF_SYMBOL (~spell~ ~CLERIC_ENERGY_DRAIN~)) - 1000)

ACTION_FOR_EACH scroll IN 
  112 114 115 217 218 219 220 316 320 321 322 323 324 325 326 327 330 331 418 419 420 421 422 423 424 425 426 427 428 518 519 520 521 522 523 615 617 618 714 716 734 735 736 737 738 
BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~cdid%scroll%.itm~ BEGIN

    COPY ~iwdification/lib/divine_spellbooks.tpa~ ~iwdification/lib/divine_spellbooks.tpa~
      REPLACE_TEXTUALLY ~//NUM_d%scroll% ~ ~~ // could I be more lazy? maaaaaaybe.

  END

END

REINCLUDE ~iwdification/lib/divine_spellbooks.tpa~

COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
  READ_LONG 0x1cc bio
  PATCH_IF ((bio > 0) AND (bio < 999999)) BEGIN // joinable...ish
    LPF CD_IWDIFICATION_SPELLBOOKS END
  END
  BUT_ONLY

/////                                                  \\\\\
///// divine spell crosspatching                       \\\\\
/////                                                  \\\\\

ACTION_IF NUM_d422 > 0 BEGIN

  COPY_EXISTING ~sppr%NUM_d422%.spl~ ~override~
    PATCH_IF NUM_d714 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdid714 resource = EVAL ~sppr%NUM_d714%~ END
    END
    PATCH_IF NUM_d716 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdid716 resource = EVAL ~sppr%NUM_d716%~ END
    END
    BUT_ONLY

  ACTION_IF NUM_d321 > 0 BEGIN
  
    COPY_EXISTING ~sppr%NUM_d321%.spl~ ~override~
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdid422 resource = EVAL ~sppr%NUM_a422%~ END
      BUT_ONLY
  
  END

END

ACTION_IF NUM_d733 > 0 BEGIN

  COPY_EXISTING ~sppr%NUM_d733%.spl~ ~override~
    PATCH_IF NUM_d422 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdid422 resource = EVAL ~sppr%NUM_d422%~ END
    END
    PATCH_IF NUM_d716 > 0 BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = cdid716 resource = EVAL ~sppr%NUM_d716%~ END
    END
    BUT_ONLY

END

ACTION_IF !ee_game BEGIN

  COPY_EXISTING ~cdibclaw.bam~ ~override~
                ~cdimoonb.bam~ ~override~
                ~cdismcud.bam~ ~override~
    READ_LONG 0x0c frame_off
    WRITE_LONG frame_off + 0x04 0
    IF_EXISTS
    
END

/////                                                  \\\\\
///// arcane-divine cross-patching                     \\\\\
/////                                                  \\\\\

ACTION_IF MOD_IS_INSTALLED ~IWDIFICATION/SETUP-IWDIFICATION.TP2~ ~30~ THEN BEGIN

  INCLUDE ~iwdification/lib/cross_patch_both.tpa~

END
